### ISSUE TITLE
undocumented skew method on images

### ISSUE THREAD

**Issue by passenger94** [Shoes3/shoes3#103]
```ruby
Shoes.app do
    img = image "#{DIR}/static/man-ele-image.png", left: 50, top: 50
    img.skew 7.5, 9.5  # accepts 1 or 2 args
end
```

![skew](https://cloud.githubusercontent.com/assets/10730930/6989169/bd5c1fda-da58-11e4-8c63-3a078dd1fbd5.jpg)

also rotate and scale

for shapes and images works also like this : (no methods on shapes)
```ruby
Shoes.app do
   skew 12.25
   image "#{DIR}/static/man-ele-image.png", left: 50, top: 50
   rect 50,50,86,39
end
```
skew is mentioned for shapes in transform method but not documented and scale is also not documented for shapes

**Comment by ccoupe** [comment]
So many undocumented features. The manual is going to get bigger and bigger.
