### ISSUE TITLE
Hpricot or download bug

### ISSUE THREAD

**Issue by ccoupe** [Shoes3/shoes3#105]
Later builds of Shoes 3.2.22+ have a bug with samples/expert-funnies. The rss is downloaded (ok) but the image is never displayed.  No error message on the Shoes console but the OSX console has one:

4/4/15 1:55:51.477 AM shoes-bin[46090]: assertion failed: 14C1514: libxpc.dylib + 97940 [876216DC-D5D3-381E-8AF9-49AE464E5107]: 0x87

That message doesn't help much and what that libxpc.dylib is used for is unclear.

**Comment by ccoupe** [comment]
libxpc.dylib has nothing to do with this bug. That error is from from open app from the splash screen.

The bug appears to be the image download. I now suspect a threading problem.

**Comment by passenger94** [comment]
i have this in console (since a very long time btw)
>Error in <unknown> line 0 | 2015-04-05 10:44:53 +0200
>cannot load such file -- hpricot
~/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
~/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
expert-funnies.rb:1:in `<main>'
~/Git/shoes3_gtk3/dist/lib/shoes.rb:476:in `eval'
~/Git/shoes3_gtk3/dist/lib/shoes.rb:476:in `visit'
eval:1:in `<main>'

allways thought it was related to the outdated hpricot library ?

**Comment by ccoupe** [comment]
@passenger94 odds are very high that you have a "Loose" shoes build which does not include any gems - It uses your normal rvm gems. There's lot of wiki articles that talk about the different between tight and loose shoes. Basically you can't distribute your Shoes across the net because it's compiled and linked against your ruby in your /home/username/.rvm and username doesn't exist on other systems . so just 'gem install hpricot' or what ever other gems you want in Shoes. Loose shoes also does some symbolic linking in dist/ so you don't have to rebuild Shoes just to change a manual page or something in lib. Also it's easier to use with gdb.

**Comment by passenger94** [comment]
oh, my bad, didn't thought about this !
works from downloaded 3.2.22 on linux

**Comment by BackOrder** [comment]
[samples/expert-funnies.rb](https://github.com/Shoes3/shoes3/blob/master/samples/expert-funnies.rb) now supports **Nokogiri**. Doesn't it make this issue irrelevant?

**Comment by BackOrder** [comment]
`hpricot` has been now removed from Shoes and fully replaced by Nokogiri. Closing this issue.
