### ISSUE TITLE
Shoes 3.2.22: squares instead of characters

### ISSUE THREAD

**Issue by Dassadar** [Shoes3/shoes3#106]
Hello,

My previous Shoes 3.2 was no longer launching, so I decided to install the latest 3.2.22.
However all my characters are now displayed as characters and I feel lost as what to do:
![image](https://cloud.githubusercontent.com/assets/11810481/6998945/3b3b8274-dbf3-11e4-9379-43591f6cede4.png)

Can you please help?

Thx & regards,
David

**Comment by ccoupe** [comment]
Shoes 3.2.22 font handling changed some things on Windows - apparently not for the better.  At install time, fc-cache.exe is run to build a list of all fonts (it takes a minute or two).  Does the manual look OK?

Sometimes you can get better error messages from the command line program cshoes.exe (it can also trigger a font cache rebuild sometimes.

**Comment by ccoupe** [comment]
@Dassadar , a couple of questions that would help. If you open a cmd terminal and run cshoes.exe and get a Cannot load default config file then I'd like to know what the FONTCONFIG_FILE env var is set to. 
```
C:\Users\Cecil>set FONTCONFIG_FILE
FONTCONFIG_FILE=C:\Program Files (x86)\Shoes\etc\fonts\fonts.conf
```
is mine. You mentioned that an older Shoes stopped working. Do you have both installed ? If so that might be the problem.

**Comment by Dassadar** [comment]
Hi Cecil,

Here is what I get with cshoes:
![image](https://cloud.githubusercontent.com/assets/11810481/7000998/667fb184-dc30-11e4-9eea-acd0d156ff36.png)
No idea about the manual, I don't know where to look (I usually use the online one).

My font config file is there:
![image](https://cloud.githubusercontent.com/assets/11810481/7001024/d2a91224-dc30-11e4-98a7-d760cdc6fced.png)

For the older Shoes, I had only one version installed. What happened was that the process was launched, but there was no wondow (happened from time to time).

Regards,
David

**Comment by ccoupe** [comment]
David, we can fix this. You have two values in FONTCONFIG_FILE, only the first is used and it points to an earlier Shoes file that is no longer in 3.2.22. You probably didn't un-install the older Shoes (because no one told you to) before installing 3.2.22.   We want to set it to just  the second value. The ';' separates them, so delete first one and the semicolon using instructions:

http://www.computerhope.com/issues/ch000549.htm is one of many descriptions of how to change env vars.  

Alternately, You can also un-install Shoes from the Start->All Programs->Shoes->Uninstall which will remove the second path and then use the instructions above to delete FONTCONFIG_FILE. Reboot and then reinstall Shoes 3.2.22 and it should then have the correct value ( the correct value it has the \etc\fonts\fonts.conf in it).

Let us know if that solves the problem.

Please note that the Shoes built in manual is available from Start->All Programs->Shoes->manual and it is much nicer and is much more accurate and up to date than the online manual.

**Comment by ccoupe** [comment]
David  expect a 1 or 2 minute hang  every once in a while - whenever Shoes/fontconfig thinks the font's need refreshing.  It is annoying.

**Comment by Dassadar** [comment]
Thank you, modifying the env variable works perfectly!
However I had tried before to uninstall and reinstall cleanly, and it didn't change anything.

By the way, the new version looks really good - but I still have an issue with accented letters: should I open another topic?

I am using a csv file with French accents like é è à etc.
Ruby keeps translating these as weird characters.

However the accents written directly in the code (app.para for example) are well displayed.

Regards,
David

**Comment by Dassadar** [comment]
As I am on it, I just saw a regression on the newest version (java-based, isn't it?).
Before if the text size was bigger than the list_box width, the dropdown was automatically resized to the maximum text length.
Now it is no longer the case, and it is a bit impractical and not user friendly to scroll horizontally inside the drop-down: do you think something can be done?

Regards,
David

**Comment by ccoupe** [comment]
David, once you get an extra unwanted path in the env var, by any means, it sticks aound until manually cleaned out. You could un-install Shoes, delete the FONTCONFIG_FILE env  var manually, and then reinstall but it's an extra reboot.  Thank you for helping to get it working. 

@BackOrder knows a whole lot more about the encoding issues than I so perhaps he will help with the csv.  Speculation follows: I'm guessing the csv file is from another application? If so, it may not be read correctly by Ruby unless the csv open is told to use utf16-le to read and write the file. Speculation. 

Shoes 4 is Java and swt. - Ruby version 1.9.3 (I think). Shoes 3.2 is MRI Ruby (cruby) and Ruby 2.1.5 so they can be different in details and we have two different github sites. When you say 'latest release, java?' I'm not sure which Shoes you have a question about.  If it's Shoes 3.2,  then there is an existing request to change the font size on list_box if the width is exceeded. That request may be difficult to do in 3.2 - even if Shoes 4 does it by default. 

My opinion (just one of many)  If you (the shoes script developer) know the text is going to be wider that the list_box, you can set the font and/or size styles when creating the list_box.  Shoes 3.2 depends on native widgets and hey don't always do what is asked.

**Comment by Dassadar** [comment]
Thanks Cecil
.
The csv is very simple: pure text separated by semi-colons.

For the font size there is the limitation it cannot be smaller than
"inscription", can it?

David

2015-04-06 11:52 GMT+02:00 Cecil Coupe <notifications@github.com>:

**Comment by ProvGANG** [comment]
@Dassadar , you can put any text like this

    para "Text", :size => 2 # i'm not sure what is the size of inscription but this could be smaller than its size

**Comment by passenger94** [comment]
see Manual Element > TextBlock
inscription, para, etc... are just convenient styled text blocks, inscription is styled 10px font size for example but like @ProvGANG says nothing stops you from styling that text block the way you desire

**Comment by Dassadar** [comment]
ok thx for the tip for para.
However, it doesn't seem to work for list_box...

2015-04-06 16:54 GMT+02:00 passenger94 <notifications@github.com>:

**Comment by ccoupe** [comment]
@Dassadar  - on the csv and unicode characters:  Is it the filename or the file contents with the accented characters inside?  how are you opening the file and parsing the contents? CSV is Comma Separated Text so semicolon ';' is not the normal separator.

**Comment by ccoupe** [comment]
@Dassadar - for the font size of list_box contents - you are correct, they can not be styled (native widget restrictions and vendor look and feel are one possible reason why). Even if you could,  practically you can't make the font small enough if the string is too large or make the list_box as wide as the longest string you haven't seen yet. Esthetically,  list_boxes should not be used that way. You have design a different GUI or a different way of presenting that info and that is very dependent on your application and the data to present and manipulate.

**Comment by Dassadar** [comment]
It is the file contents that has accents.
I require 'csv', then I read in this way:
csvInv = CSV.read("./data/inventaireUnites.csv", { :col_sep => ';' })

About the list_box, then I just regret the previous Shoes version where
list_box width was resized automatically upon click to the largest
contained string.

2015-04-07 6:37 GMT+02:00 Cecil Coupe <notifications@github.com>:

**Comment by ccoupe** [comment]
Feel free to open a new issue requesting the list_box compression - be sure to tell us what platform and shoes version does that.  @ProvGANG asked for it too but maybe that was in private email. It's not something I would expect OSX or Linux to do but someone did it.

CSV: We know Shoes has the font's (now) and can display the accented characters so we have to consider if this is a Ruby problem.  Shoes justs expects everything is UTF-8 encoded (as does gtk). 

This page http://ruby-doc.org/stdlib-2.1.0/libdoc/csv/rdoc/CSV.html discusses how CSV handles encodings. Ick but here we are. Can you make a small Shoes test program (and maybe a smaller file) that has the problem and share that?  You probably have a Gist button at the top of this page where you can paste them to or you can zip them up and send them in an email to ccoupe@cableone.net.  I'm not the smartest programmer here but this will turn out to be one of those "I never knew that" things.  Always fun to learn.

**Comment by ccoupe** [comment]
I've created https://github.com/Shoes3/shoes3/issues/109 for the list_box issue.

**Comment by ccoupe** [comment]
Just a follow up note. David sent me his test script and file. Thanks. The csv was not UTF-8 but ISO-8859-1 which can be converted to UTF-8, one cell at a time for each row - something that I brute forced for his test script. My solution lacks Ruby elegance. If someone wanted to write a wiki article on how to read and write iso--8859-1 csv files with Shoes (or Ruby for that matter) that would make a nice wiki article.

**Comment by Dassadar** [comment]
Hello,
Thanks for your help: it works perfectly!
Regards,
David

2015-04-08 10:37 GMT+02:00 Cecil Coupe <notifications@github.com>:

**Comment by Dassadar** [comment]
Hello,

I still have a problem with the csv and UTF-8.
It looks like once a read array is converted, it is well displayed through
a para, but not through an alert.
Example is in attachment.

Regards,
Dassadar


2015-04-08 11:32 GMT+02:00 David Pauchet <pauchet.david@gmail.com>:

**Comment by ccoupe** [comment]
@Dassadar - i don't see an attachment but I can guess.  You've come across bug #111 - which you can code around. More likely you are not be _converting_ the csv - you've made a temporary copy of it and only that copy is converted.  You need to create a a new object (array of array of 'converted' strings). That can be reused.

**Comment by Dassadar** [comment]
Hello,
Here is the example in full text.
*** test.csv
value1;value2
a;à
é;e
*** test.shoes
require 'csv'
Shoes.app do
	csvInv = CSV.read("./test.csv", { :col_sep => ';' })
	csvInv.map!{|row| row.map{|cell| cell.encode('UTF-8') if cell}}
	para csvInv[1][1]
	para "\n"
	para "#{csvInv}"
end

**Comment by ccoupe** [comment]
This is not  really a  Shoes problem. You've asked Ruby to convert "#{csvInv}" to string and then pass that to para. What you see depends on your locale setting/encoding. I'm US_ASCII so I see unicode strings \uxxyy. If you do "para  "#{csvInv[1][0]} #{csvInv[1][1]}" everything looks good.  You have to do the conversion of array[][] to string your self if Ruby's default doesn't do what you want.

**Comment by ProvGANG** [comment]
@Dassadar, I'm not sure but this might help you, on the start of my every ruby script I add this comment
```ruby
#encoding: utf-8
```
