### ISSUE TITLE
undocumented :minwidth, :minheight styles for Shoes.app

### ISSUE THREAD

**Issue by passenger94** [Shoes3/shoes3#107]
Sets a minimum width and height for the app (cannot shrink beyond), works with gtk2

but why ? `app_t->minwidth = (NUM2INT(ATTR(attr, minwidth)) - 1) / 2;`
https://github.com/Shoes3/shoes3/blob/master/shoes/app.c#L143
if you give :minwidth => 100, you'll end up, app constrained to a mimimum width of 49 !!!
(fixed a wrong parenthesis placement with minheight btw)

**Comment by ccoupe** [comment]
the history of app.c has this comment, https://github.com/Shoes3/shoes3/commit/9a8b0e44c5177916649000ffa916361617fd941a

**Comment by passenger94** [comment]
ok made a fix to get just  the straight minwidth/minheight ..., leaving previous code commented in case i understand the reasoning behind `ATTR(attr, minwidth)) - 1) / 2`
