### ISSUE TITLE
Cannot package my app with Google Drive

### ISSUE THREAD

**Issue by Dassadar** [Shoes3/shoes3#108]
Hello,

I am sharing my shoes code with a friend through Google Drive (as installed software).
The problem is, when I try to package my app, I cannot go inside GDrive link:
![image](https://cloud.githubusercontent.com/assets/11810481/7002494/f1994832-dc4b-11e4-929a-6012a938aeeb.png)

Is there something that can be done?

Regards,
David

**Comment by ProvGANG** [comment]
You can't open folder in Shoes with .lnk file. I have Dropbox installed on my machine but I think it should be the same thing.

You must open the folder where your Google drive is installed, not link to it. Mine for Dropbox for example is: C:\Users\User\Dropbox

Hope this helps.

**Comment by ccoupe** [comment]
The new theme engine dialog seems to skip certain drives. I have a network share on E: that isn't displayed so I know the problem. Thanks for reporting it. Gtk is pretty flexible if you know where to fix it.

**Comment by ccoupe** [comment]
I should update my comment. Sometimes, but not always, the network share is not displayed in the file dialogs.

**Comment by Dassadar** [comment]
Hello,

Waiting for a fix, what is the way to package an app behind GDrive/Dropbox
please?
I thought shoes -p would make it, but instead it opens the packaging GUI -
which has the problem mentioned before.
Is there a command to package without GUI?

Regards,
Dassadar

2015-04-07 6:19 GMT+02:00 Cecil Coupe <notifications@github.com>:

**Comment by ccoupe** [comment]
Have you tried @ProvGANG  suggestion? Open a window to the remote drive and then run shoes? Did that work? I don't have dropbox or google drive account nor do I intend to get one.  

You do know you can package to a directory on your hard disk and drag it to dropbox/google-drive?

**Comment by Dassadar** [comment]
Yes, the window on remote drive doesn't work (it will block with
Google drive.lnk even if the window is open within this directory).
I will try the copy on hard drive method as a workaround then, thx.

2015-04-09 8:02 UTC+02:00, Cecil Coupe <notifications@github.com>:

**Comment by ccoupe** [comment]
I've noticed something else. I have a network drive e: When shoes is first run as part of an install, e: doesn't show up. If I relaunch Shoes, e: is there.

**Comment by ccoupe** [comment]
> Is there a command to package without GUI?

A year late on the answer to that ;-) But yes,  you can write a script to do packaging without the Shoes gui. See https://github.com/Shoes3/shoes3/wiki/Command-line-packager
