### ISSUE TITLE
list box drop down text compression

### ISSUE THREAD

**Issue by ccoupe** [Shoes3/shoes3#109]
Due to popular demand, let us collect data on list_box rendering issues. Here is a small program:

```ruby
Shoes.app :width => 400, :height => 100 do
 stack do
   items = []
   items[0]= "No! Don't me"
   items[1]= "Let me tell you a story about how octal numbers fell out of \
favor and were replaced with hexidecimal numbers. As you might suspect the \
answer is not technical but financial and related to the 80 column punched card"
   list_box :items => items, :choose => items[1]
  end
end
```
Obviously the contents of item[1] are wide. Much wider that the list box or the windows. On my Linux, in my theme it looks like this, 
![listbox-inactive](https://cloud.githubusercontent.com/assets/222691/7019551/71e7b2bc-dcce-11e4-8e48-201368855fe5.png)

When I select the list_box, the drop down window is very wide - almost the whole width of my monitor. I can't capture it due to limitations in my capture tool and X11 oddities. It's just wide, wide and wider. 

Here's the drop down situation for Shoes 3.2.22 on Windows.
![win-active](https://cloud.githubusercontent.com/assets/222691/7019991/a7d675d0-dcd2-11e4-88e0-9cb3046f966d.png)

OSX behaves much like Linux -a very very wide drop down  but it has an  `...` in the middle so it's not quite as ugly as my Linux theme. 

Now I understand the complaint. A picture is worth a thousand words. I bet it's a themeable setting in gtk2 for windows.

**Comment by ccoupe** [comment]
Follow up. I need to change my theme to be more Windows like. 

@passenger94  the snippet behaves even worse on GTK3 - the whole app window is resized. #92

**Comment by passenger94** [comment]
yes whole app is resized in gtk3 ... i think it have something to do with widget size_request ... and co

**Comment by passenger94** [comment]
@ccoupe snippet working the same now on gtk2 and gtk3, width is working, turns out we need a `gtk_combo_box_text_new_with_entry()` in place of a `gtk_combo_box_text_new()`

**Comment by ccoupe** [comment]
Yes, that works much better. Thank you.

**Comment by ccoupe** [comment]
@passenger94  I like your newer gtk3 behavior but I don't put long strings in list boxes  so I would like it.  Would it be possible to extend the width (cell render?) to the width of the Shoes.app window which would be a reasonably compromise between the Gtk/Windows that only uses the list_box width and the older wild gtk2/osx widths. Thoughts?

**Comment by passenger94** [comment]
yes possible, just grab the app width and putting it in the "gtk_cell_renderer_set_fixed_size" method, first is the popup, second when choice is made
![lb02a](https://cloud.githubusercontent.com/assets/10730930/7115345/2de3758c-e1e8-11e4-8725-5abc0cbbdc33.jpg)
![lb02b](https://cloud.githubusercontent.com/assets/10730930/7115347/32ee0fce-e1e8-11e4-8335-ca44e4f89166.jpg)
we could have the same behavior by taking the with from the list_box attributes, (user defined)

another option with "ellipsize" property only (no width constraint at c level) gives this
![lb01 jpg](https://cloud.githubusercontent.com/assets/10730930/7115406/baea7df4-e1e8-11e4-9bf2-63a43f69797d.png)
here the popup is the very wide one, like in gtk2

**Comment by passenger94** [comment]
ooops was in a hurry, i think i didn't quite understood your request !! :-D
let me see ...

**Comment by ccoupe** [comment]
There is also the possibility that the behaviour/appearance is theme controlled. I haven't had a chance to did into how much the theme controls (on gtk2/windows vs gtk/linux vs gtk3/*)

**Comment by ccoupe** [comment]
I'd like to get this included in 3.3.0. :font => <string> is a valid style, just not for list_box (yet). It seems doable in gtk3 and I'm pretty sure OSX can do it to.  A small matter of pango_font_description_from_string .  see  shoes_app_style_for() in ruby.c  We'd need  a new list_box.font getter and a list_box.font= setter method possible/likely with native code implementations.

Assuming it can be done for list_box in 3.3.0,  it could be extended to other 'native' widgets in Shoes 3.3.1  That would be something spectacular.

**Comment by passenger94** [comment]
We want a GtkCellRendererText : https://developer.gnome.org/gtk3/stable/GtkCellRendererText.html
and use it like the *ellipsize* property : https://github.com/Shoes3/shoes3/blob/master/shoes/native/gtkcomboboxtextalt.c#L152 to Line 156

**Comment by ccoupe** [comment]
Gtk (windows, linux) only so far. Too easy.
![screenshot from 2016-01-03 20 54 09](https://cloud.githubusercontent.com/assets/222691/12083248/6a82eca8-b25c-11e5-94e3-79fd8dc18c15.png)

**Comment by ccoupe** [comment]
I'm going to close this issue when 3.3.0 is released. As I said in #170, it's probably not what they really want.
