### ISSUE TITLE
mask method is undocumented

### ISSUE THREAD

**Issue by passenger94** [Shoes3/shoes3#113]
nothing about it in manual despite "simple-mask.rb" in samples

**Comment by passenger94** [comment]
mask method creates a slot like flow or stack methods or Shoes::Widget (not documented in manual btw), images, shapes, textblocks, background and borders could be masks or a combination of these.

is Slot page an appropriate page for documentation in Manual ?

adapted "simple-bounce.rb"
```ruby
xspeed, yspeed = 8.4, 6.6
xdir, ydir = 1, 1

Shoes.app do
  background "#{DIR}/static/stripe.png"

  mask do
    @icon = image "#{DIR}/static/shoes-icon.png", :left => 100, :top => 100 do
      alert "You're soooo quick."
    end
    title "STATIC !", weight: "ultrabold", :left => 150, :top => 150
    @s = star 230,100,7, 50, 25
  end
  
  x, y = self.width / 2, self.height / 2
  size = @icon.size
  animate(30) do |f|
    x += xspeed * xdir
    y += yspeed * ydir
    
    xdir *= -1 if x > self.width - size[0] or x < 0
    ydir *= -1 if y > self.height - size[1] or y < 0

    @icon.move x.to_i, y.to_i
    @s.toggle if f % 10 == 0
  end
end
```

**Comment by ccoupe** [comment]
@passenger94  - Where in the manual? It looks more like art or transform effects to me. Where would like to put it? You are discovering a number of undocumented effects that don't really fit anywhere - maybe that's why the never got documented? 

The Shoes::Widget is deliberately undocumented - it's very limited or incomplete (you decide) and behaves oddly when put in the wrong situation. Attempts to understand it or extend it have been  less than successful.  There is also one big 'prior use' app - HacketyHack. which no one wants to modify if the Widget api changes or support it.  @BackOrder  added `samples/expert-custom-list-box.rb` which tries to make a custom widget by extending an existing native widget but there are large documentation challenges (method missing, observer pattern, etc). Who wants to document those concepts for newbie Shoes folks? 

Ian and I have talked about second or new Shoes manual in email  that would be target to more advanced Ruby knowledgeable folks and he did some private work on creating Shoes app's that act like epubs  but with a better markup language than is used in the Shoes Manual.  Like many brilliant ideas and good intentions we had some reality problems: gem installation primarily because ftsearch is pretty limiting, nokogiri (was then) not working on Windows and more -it's one of the reason I have issues created for rakefile clean up and a better gem mechanism.

**Comment by dredknight** [comment]
I will take this one.

**Comment by dredknight** [comment]
Heya everyone here is the first version of the mask documentation. Let me know if I did miss anything important.

> 
===========================================================
Mask(styles){...} >> Shoes::Widget::Mask
===========================================================
Mask is a slot which masks all elements in the area it is created. It offers the ability to peek through it using shapes and texts.
Abstraction is blurry so lets make a simpe example on how it works.

Imagine you have a canvas you are working on and you paint the whole canvas orange.
```Ruby
Shoes.app do
	background orange
end
```
While doing that you do remember that actually you wanted to draw just an orange star and not the whole canvas.
So what you do is use piece of paper with the star-shape cut in it glued on top of the orange canvas.
```Ruby
Shoes.app do
	background orange
	mask do
		star top: 200, left: 200, points: 6, outer:100, inner: 50
	end
end
```
You can cut more stuff through the above layer using shapes, text and images. The last one will be used solely as a shape and no image will be drawn.
```Ruby
Shoes.app do
  background "#{DIR}/static/stripe.png"
  mask do
    image "#{DIR}/static/shoes-icon.png", :left => 50, :top => 20
    title "STATIC !", weight: "ultrabold", :left => 150, :top => 400
    star 400,200, 7, 50, 20
  end
end
```
Finally you can even make a mix between multicolour background and animated cuts for some nice effects.

```Ruby
xspeed, yspeed = 8.4, 6.6
xdir, ydir = 1, 1

Shoes.app do
  background "#{DIR}/static/stripe.png"

  mask do
    @icon = image "#{DIR}/static/shoes-icon.png", :left => 100, :top => 100 do
      alert "You're soooo quick."
    end
    title "STATIC !", weight: "ultrabold", :left => 150, :top => 150
    @s = star 230,100, 7, 50, 20
  end

  x, y = self.width / 2, self.height / 2
  size = @icon.size
  animate(30) do |f|
    x += xspeed * xdir
    y += yspeed * ydir

    xdir *= -1 if x > self.width - size[0] or x < 0
    ydir *= -1 if y > self.height - size[1] or y < 0

    @icon.move x.to_i, y.to_i
    @s.toggle if f % 10 == 0
  end
end
```
Notes: Mask supports all slot related styles with the exception of fill.

**Comment by BackOrder** [comment]
This is good @dredknight. Clearly on the right path. Some feedback:

Mask is **not** a widget, it inherits from Shoes class. 
   [ruby.c](https://github.com/Shoes3/shoes3/blob/master/shoes/ruby.c#L4741): `cMask       = rb_define_class_under(cTypes, "Mask", cShoes);`

It might fit into slot > art category.
   
> Mask is a slot which hides all elements in the area it is created. It offers the ability to peek through it using elements. Abstraction is blurry so lets make a simpe example on how it works.

Mask is a slot allowing to clip elements outside its own area. 

The second and third sample code you wrote would be good for the manual. The last one would be good into the samples directory.

**Comment by BackOrder** [comment]
```ruby
ydir *= -1 if y > self.height - size[1] or y < 0
```

Testing with a constant **y** seems to look better.

**Comment by dredknight** [comment]
Thanks you @BackOrder! I specifically checked it but it seems I read it wrong, it should be Shoes::Types::Mask. 

That last piece of code is @passenger94 work and it is already available as a sample simple-mask2. Here is a new iteration.

> Mask(styles){...} >> Shoes::Types::Mask

Mask is a visual feature which hides all elements in the environment it is created (Canvas or slot). It offers the ability to peek through it using elements. For example:

Imagine you there is a canvas you painted in orange.
```Ruby
Shoes.app do
	background orange
end
```
While doing that you do remember that actually you wanted to draw just an orange star instead of the whole canvas. So what you do is use piece of paper with the star-shape cut in it glued on top of the orange canvas.

Shoes.app do
	background orange
	mask do
		star top: 200, left: 200, points: 6, outer:100, inner: 50
	end
end
More cuts can be done through the above layer using shapes, text and images. The last one will be used solely as a shape and no image will be drawn.

Shoes.app do
  background "#{DIR}/static/stripe.png"
  mask do
    image "#{DIR}/static/shoes-icon.png", :left => 50, :top => 20
    title "STATIC !", weight: "ultrabold", :left => 150, :top => 400
    star 400,200, 7, 50, 20
  end
end
A mix between multicolour background and animated cuts can be added so it is even better looking. Check simple-mask and simple-mask2 for inspiration.

Notes: Mask supports all slot related styles with the exception of fill.

**Comment by dredknight** [comment]
P.S. whoever edits the manual should also add the MASK method in the STYLE section under each style method it can be used with.

**Comment by BackOrder** [comment]
The definition is a bit unclear. The reason why I wrote _Mask is a slot allowing to clip elements outside its own area_ is because Mask is a shorthand for **clipping mask**.  Clipping masks are used in many software, including Photoshop and Illustrator, which will give Shoes programmers a good idea of what it does.

Searching on Google about clipping mask results in countless source of information. For example, https://helpx.adobe.com/ca/illustrator/using/clipping-masks.html

Maybe your sample should have a before and after like the article above. Maybe something with multiple clippings (different shapes) to show how powerful mask is. Especially in cases like when you use an image as a mask, such as **shoes-icon.png**, where it's unclear to the **new** Shoes programmer what it is and how it works.

Remember, everything in the manual are using **`left, top`** and your samples should also use the same order.

**Comment by dredknight** [comment]
Ah I see now. I am not a designer so this stuff really get away with me.
Alright basically the first code is before and the second one is after I just need to describe it in such way.

Here is a new approach.

> # Mask(styles){...} >> Shoes::Types::Mask
> 
> Mask is a slot allowing to clip elements outside its own area. The are is defined by using texts, shapes or images where the last one is used as a shape. 
> Here you have 2 slots with orange background.
> On the left it is drawn a green star while on the right the green star is clipped with mask.
> Notice how the colour of the star is not taken into account.
> 
> ```Ruby
> Shoes.app do
> 	flow left: 10, top: 10, width: 150, height: 150 do
> 		background orange
> 		star  left: 50, top: 50 , points: 6, outer: 40, inner: 20, fill: green
> 	end
> 	
> 	flow left: 200, top: 10, width: 150, height: 150 do
> 		background orange
> 		mask do
> 			star  left: 50, top: 50 , points: 6, outer: 40, inner: 20, fill: green
> 		end
> 	end
> end
> ```
> 
> Here we have the same setup but this time an image is used for clipping.
> 
> ```Ruby
> Shoes.app do
> 	flow left: 10, top: 170, width: 150, height: 150 do
> 		background orange
> 		image "#{DIR}/static/shoes-icon.png", width: 100
> 	end
> 	
> 	flow left: 200, top: 170, width: 150, height: 150 do
> 		background orange
> 		mask do
> 			 image "#{DIR}/static/shoes-icon.png", width: 100
> 		end
> 	end
> end
> ```
> You can do the same with text.
> ```Ruby
> Shoes.app do
> 	flow left: 10, top: 170, width: 150, height: 150 do
> 		background orange
> 		para "normal shoes"
> 	end
> 	
> 	flow left: 200, top: 170, width: 150, height: 150 do
> 		background orange
> 		mask do
> 			para "clipped shoes"
> 		end
> 	end
> end
> ```
> Check the sample directory for more examples

**Comment by BackOrder** [comment]
> Ah I see now. I am not a designer so this stuff really get away with me.

No worries. You are doing just fine.

This is a corrected text (just for misspelled words and such):
`Mask is a slot allowing to clip elements outside its own area. The area is defined by using texts, shapes or images where the last one is used as a shape. Here you have 2 slots with an orange background. The left slot is drawn with a green star while the right slot contains the green star used a clipping mask. Notice how the colour of the star is not taken into account.`

The samples are better representing the concept now. What would be good is to center things so they look better. You know?

![image](https://cloud.githubusercontent.com/assets/8844578/23343904/3f104c98-fc41-11e6-9628-a74b36c7bc65.png)

**Comment by dredknight** [comment]
Thanks, yes finishing touches will be done properly!

**Comment by dredknight** [comment]
Done! I believe we are done with this one :)

> # Mask(styles){...} >> Shoes::Types::Mask

Mask is a slot allowing to clip elements outside its own area. The area is defined by using texts, shapes or images where the last one is used as a shape. Here you have 2 slots with an orange background. The left slot is drawn with a green star while the right slot contains the green star used a clipping mask. Notice how the colour of the star is not taken into account.
```Ruby
Shoes.app do
	flow left: 10, top: 10, width: 150, height: 150 do
		background orange
		star  left: 75, top: 75, points: 6, outer: 40, inner: 20, fill: green
	end
	
	flow left: 200, top: 10, width: 150, height: 150 do
		background orange
		mask do
			star  left: 75, top: 75, points: 6, outer: 40, inner: 20, fill: green
		end
	end
end
```
The same setup but this time an image is used for clipping.

```Ruby
Shoes.app do
	flow left: 10, top: 10, width: 150, height: 150 do
		background orange
		image "#{DIR}/static/shoes-icon.png", left: 25, top: 25, width: 100, align: "center"
	end
	
	flow left: 200, top: 10, width: 150, height: 150 do
		background orange
		mask do
			 image "#{DIR}/static/shoes-icon.png", left: 25, top: 25, width: 100
		end
	end
end
```
Text can be used as well.
```Ruby
Shoes.app do
	flow left: 10, top: 10, width: 150, height: 150 do
		background orange
		para "normal shoes", top: 60, align: "center"
	end
	
	flow left: 200, top: 10, width: 150, height: 150 do
		background orange
		mask do
			para "clipped shoes", top: 60, align: "bottom"
		end
	end
end
```
Check the sample directory for more examples

**Comment by BackOrder** [comment]
The two first examples are good. The last one is alright but it wouldn't make a visual difference either use a mask or `stroke`, isn't it? It would be best to do something like **STATITC** that we see in this issue - using an image for background clipping and bigger size for the font.

Do you know how to commit to Shoes3 repo? Or how to make a pull request?

By the way, here is a shorthand manual code allowing you to test with your own manual text file. Change the path to your own copy of the `manual-en.txt` and run it with Shoes.

```ruby
require("shoes/search")
require("shoes/help")

module Shoes::Manual
  def self.path
    path = "C:/Users/Ian/Documents/GitHub/shoes3/static/manual-en.txt"
  end
end
  
Shoes.app(:width => 720, :height => 640, &Shoes.make_help_page)
```

**Comment by dredknight** [comment]
Sure I use git since recently and know how to branch and commit. Never did a pull but I believe it is something like getting the current state of the master branch, then work on it and then commit it back.

Thanks for the code I will try it out.

Here is the article with fixed text example

>#  Mask(styles){...} >> Shoes::Types::Mask
> 
> Mask is a slot allowing to clip elements outside its own area. The area is defined by using texts, shapes or images where the last one is used as a shape. Here you have 2 slots with an orange background. The left slot is drawn with a green star while the right slot contains the green star used a clipping mask. Notice how the colour of the star is not taken into account.
> ```Ruby
> Shoes.app do
> 	flow left: 10, top: 10, width: 150, height: 150 do
> 		background orange
> 		star  left: 75, top: 75, points: 6, outer: 40, inner: 20, fill: green
> 	end
> 	
> 	flow left: 200, top: 10, width: 150, height: 150 do
> 		background orange
> 		mask do
> 			star  left: 75, top: 75, points: 6, outer: 40, inner: 20, fill: green
> 		end
> 	end
> end
> ```
> The same setup but this time an image is used for clipping.
> ```Ruby
> Shoes.app do
> 	flow left: 10, top: 10, width: 150, height: 150 do
> 		background orange
> 		image "#{DIR}/static/shoes-icon.png", left: 25, top: 25, width: 100, align: "center"
> 	end
> 	
> 	flow left: 200, top: 10, width: 150, height: 150 do
> 		background orange
> 		mask do
> 			 image "#{DIR}/static/shoes-icon.png", left: 25, top: 25, width: 100
> 		end
> 	end
> end
> ```
> Text can be used as well.
> ```Ruby
> Shoes.app do
> 	flow left: 10, top: 10, width: 190, height: 150 do
> 		background orange
> 		 title "SHOES !", weight: "ultrabold"
> 	end
> 	
> 	flow left: 220, top: 10, width: 190, height: 150 do
> 		background orange
> 		mask do
> 			 title "SHOES !", weight: "ultrabold"
> 		end
> 	end
> end
> ```
> Check the sample directory for more examples.

**Comment by dredknight** [comment]
I pulled the shoes and used your code and it works! Only one thing... where and how to embed this code above as a page in the manual.

I got a peak at shoes3/static/manual-en.txt and I cant believe that the whole manual text is in there. How the heck does the code knows which pieces to take and present on each page? :dagger: 

Actually where I can see the manual code?
I found this file -> \shoes3\platform\mac\command-manual.rb but it is empty.

**Comment by BackOrder** [comment]
> I believe it is this one ->shoes3\lib\shoes\help.rb but any further explanation will be welcome :).

`help.rb` is rendering `manual-en.txt` into what you know as Shoes Manual. We even have a eBook project based on it, markdown and so on.

> I got a peak at shoes3/static/manual-en.txt and I cant believe that the whole manual text is in there. How the heck does the code knows which pieces to take and present on each page? 🗡

Shoes Manual has its own markup language. The first red square box below contains the code you see when you open Shoes Manual. The red square box below is a markup to attach an image. You can see the comparison between `manual-en.txt` and its rendering.

![image](https://cloud.githubusercontent.com/assets/8844578/23757473/ee54026e-04b4-11e7-8a42-9f0e6c162d06.png)

![image](https://cloud.githubusercontent.com/assets/8844578/23757546/22af46e0-04b5-11e7-9d4b-6cae411d314a.png)

**Comment by dredknight** [comment]
I am baffled by the idea that you have a framework (manual) within a framework (Shoes). I am not sure if I understand correctly but basically there is a parser which takes the txt file and based on the symbols like

!...! - creates image
==.....== - makes new page with header
^...^  - No idea what is this but I saw it at the bottom of the page code you show as example.

Whoever did this is genius, it allows the writer to add text without bothering of knowing any code besides the simple syntax out there. Though I believe the complexity comes when trying to introduce functions like search. 

Do you keep this syntax idea in the e-book? Anything else I might have missed?

**Comment by BackOrder** [comment]
> I am baffled by the idea that you have a framework (manual) within a framework (Shoes). I am not sure if I understand correctly but basically there is a parser which takes the txt file and based on the symbols like

Shoes is more powerful than one would think. 

> !...! - creates image
> ==.....== - makes new page with header
> ^...^ - No idea what is this but I saw it at the bottom of the page code you show as example.

Yes, this is basically how it works. The fun part is that you can look in `manual-en.txt` and compare with Shoes Manual. You will figure out how things work.

> Do you keep this syntax idea in the e-book? Anything else I might have missed?

Shoes eBook will eventually replace Shoes Manual code. It uses Markdown instead of strange markup in `manual-en.txt`. Unfortunately, Shoes eBook is still work in progress. https://github.com/Shoes3/ebook

> Whoever did this is genius, it allows the writer to add text without bothering of knowing any code besides the simple syntax out there.

Yes. :)

**Comment by dredknight** [comment]
It is ready! Where and how can I provide it here now as this thread gets big very fast every time I post the whole thing.

Also a noob question - is there a way to style text to be centered vertically just as _align: "center"_ does it horizontally?

**Comment by BackOrder** [comment]
> It is ready! Where and how can I upload/push it? This thread gets big very fast every time I post the whole thing so I better cut that practice.

You could explore [GitHub Desktop](https://desktop.github.com/). Normally I would first sync with Shoes3 repo, then commit change and finally sync again. Don't forget to test your changes before committing.

Alternatively, you could fork your own Shoes3 and make the modifications in your repo. Then you submit a pull request — fairly easy using GitHub web interface. To fork Shoes3...

![image](https://cloud.githubusercontent.com/assets/8844578/23769910/fc903cb0-04de-11e7-8aab-de01b094dccb.png)

> Also a noob question - is there a way to style text to be centered vertically just as align: "center" does it horizontally?

There is nothing to center vertically in Shoes. Just like when you wrote **Popup Text**.

**Comment by dredknight** [comment]
Done. Thanks a lot! Is it advisable to refer commits to appropriate ticket and how do you do it? I see that @ccoupe does it when committing.

**Comment by BackOrder** [comment]
You are clever, @dredknight ! In your commit title and/or commit message, you write the pound sign (`#`) followed by the issue number and it will be automatically list with the issue. For example, this is issue #113. Notice GitHub renders the number clickable.

**Comment by dredknight** [comment]
Cool :)

**Comment by BackOrder** [comment]
Everything works fine here. Samples look good. Thanks @dredknight !

**Comment by dredknight** [comment]
See you on another one :D.
