### ISSUE TITLE
radio button, unusual behaviour

### ISSUE THREAD

**Issue by ProvGANG** [Shoes3/shoes3#117]
I'm not sure if there is something wrong in the way I'm treating radio buttons or this is somewhat unusual behaviour...

```ruby
Shoes.app do
  @s = stack do
   @r1 = radio :items
   @r2 = radio :items
  end
 
button "Clear" do
  @s.clear do
    @r1 = radio :items
    @r2 = radio :items
  end
 end
end
```

What actually happens is that after the stack is cleared and filled with radio buttons again, they all become checked and therefore useless in further usage. From some reasons they do not get assigned to same group when appended to stack.

**Comment by ccoupe** [comment]
It's not good behavior -  there are gtk-critical error message on the console.  If you change the group name in the clear block to say :newitems - it will work - once. I suspect the slot.clear is not deleting the radio group when the last member of the group is removed.

Like you, I question the wisdom of treating radio buttons that way but It does work on OSX so it's probably a bug. BTW - Don't depend on the first radio being checked if you didn't say which one is checked in a group.

**Comment by ccoupe** [comment]
Too quote the manual (which I can't select and copy) - " you can group together radios from different slots, you just have to give them all  the same  group name."  Since the group name is a Ruby :symbol they live for the length of the program. Perhaps you can discover the Ruby incantation to remove a :symbol and put that in your clear block or just invent a new symbol.

**Comment by ProvGANG** [comment]
Alright I've found some kind of solution for this problem. Whenever I clear the block, new symbol is assigned to the group. 

```ruby
Shoes.app do
  @s = stack do
    @r1 = radio :items
    @r2 = radio :items
  end
 
 $count = 0
 button "Clear" do
  @symbol = $count.to_s.to_sym
  @s.clear do
    @r1 = radio @symbol
    @r2 = radio @symbol
  end
 end
end

```

**Comment by ccoupe** [comment]
Consider the more common layout - per the manual suggestion
```ruby
stack do
   flow { @r1 = radio :grupo1; para "Choice 1" }
   flow { @r2 = radio :grupo1: para "Choice 2" }
end
 ```
That demonstrates that :grupo1 is not part of a a stack or a flow. It has to be something that doesn't belong to a slot.

**Comment by ccoupe** [comment]
Forgot to mention - if you invent lots of new :symbols - they don't get garbage collected  in Ruby 2.1.x so you probably don't want to do that a lot.

**Comment by passenger94** [comment]
ok made a pull request 
looks it works now, `canvas->app->groups, group` wasn't cleared

**Comment by ccoupe** [comment]
checked= is one those things that may have to be called  in a start block (or timer).

**Comment by passenger94** [comment]
and of course, one need to set a radio to be checked !  for the others to be unchecked (`@r1.checked = !@r1checked?`  doesn't make sense !  )
```ruby
@r1.checked? ? @r2.checked = true : @r1.checked = true
```
forget it :-D

**Comment by ccoupe** [comment]
the fix doesn't hurt OSX (which behaved correctly)
