### ISSUE TITLE
scroll wheel speed

### ISSUE THREAD

**Issue by passenger94** [Shoes3/shoes3#121]
i always found it is a bit slow to scroll with the mouse
is it just me ? 
(easy to change in case there is a consensus on this, no deep change)

**Comment by BackOrder** [comment]
I previously suggested that we have a **Preference Pane** in Cobbler where we can customize any such behaviour.

**Comment by ProvGANG** [comment]
guys, is the issue with stacks having set :scroll => true solved? I still
find it annoying as I can scroll stacks only when hovering scroll

2015-04-23 11:56 GMT+02:00 Ian Trudel <notifications@github.com>:

> I previously suggested that we have a *Preference Pane* in Cobbler where
> we can customize any such behaviour.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Shoes3/shoes3/issues/121#issuecomment-95518996>.
>



-- 
*Cheers!*

**Comment by ccoupe** [comment]
The scroll wheel speed is a little slow.

**Comment by passenger94** [comment]
@ProvGANG did you mean #42 ?  if so it should be, some testing won't hurt :-)
 @ccoupe  https://github.com/Shoes3/shoes3/blob/master/shoes/canvas.c#L2024  does increasing  from 16 to 48 seems reasonable ? 
@BackOrder  The Cobbler's polishing studio

**Comment by ccoupe** [comment]
48 is OK, 32 seems a bit smoother. Other opinions?  On  the day that someone converts this C constants to a Ruby hash lookup {app.styles? } is the day that has not more bugs to fix.

**Comment by passenger94** [comment]
merged #122
