### ISSUE TITLE
Assertion failed: libxpc.dylib and UI freezes on Mac OS X

### ISSUE THREAD

**Issue by southwolf** [Shoes3/shoes3#125]
Shoes 3.2 (v3.2.2 r1933, built on 2015-03-25, TIGHT-SHOES), Mac OS X 10.10.2
Everytime I open an app with Shoes, it produces logs like

5/21/15 11:46:29.264 AM bird[48933]: Assertion failed: ![_xpcClients containsObject:client]
5/21/15 11:46:30.212 AM shoes-bin[85077]: assertion failed: 14C1514: libxpc.dylib + 97940 [876216DC-D5D3-381E-8AF9-49AE464E5107]: 0x87
And the whole Shoes app UI freezes for about 5-10 seconds.

Discussions:  shoes/shoes#274

**Comment by ccoupe** [comment]
Thanks @southwolf .  I too get the libxpc.dylib exception in the console. I don't think that is the proble. My delay is not the 5 to 10 seconds but shorter - still there but not that bad and I'm using a 2 year old mac mini with a slow disk. The Ruby i/o for starting is pretty heavy  and Shoes adds more to handle it's gems and libs.  What you describe is something I see starting Shoes on the raspberry pi2 with an NFS mounted disk.  Are you using cifs/samba/nfs for you testing of Shoes?

**Comment by southwolf** [comment]
@ccoupe No, just Macbook Air's SSD, without any slow FSs. But everything works fine on my PC, slower SSD, same file, opens immediately. Removing X11 does no help.

**Comment by ccoupe** [comment]
Your Mac should be faster than mine. Shoes on Windows does have pauses in startup which you don't have. The OSX start up process begins with some shell scripts that does some pango.modules manipulation and set the DYDLD path (you can peek inside the Shoes.app to see them). Then Shoes initializes Ruby and Gems and then loads font descriptor) all of that is a lot of IO.  It might be Font related. I'm not sure how to test that idea though without a special debug build of Shoes.  You try running Activity Monitor and see if you see something suspicious.

**Comment by ccoupe** [comment]
On my mac mini, the start up time for Shoes 3.2 is between 1 and 2 seconds.  You can try the 3.2.23 beta at http://walkabout.mvmanila.com/public/shoes/shoes-3.2.23-osx-10.9.tgz but it should be the same in this regard.

I remember researching  the libxpc.dylib and ended up with the feeling that it's "probably" harmless and no one knows what it is or means.

**Comment by ccoupe** [comment]
Close?
