### ISSUE TITLE
Branch 'console'

### ISSUE THREAD

**Issue by ccoupe** [Shoes3/shoes3#127]
Since adding a low level console (Gtk/Cocoa) is experimental and is going to take a week or two or more to find out if it works, I've created a new branch for all the changes - they are many. 

Basically it creates a shoes command 'show_console'. Not many user apps are expected to use that. That vectors off (evenutally) to shoes_native_console, a ruby singleton in gtk.c and cocoa.m.

**Comment by ccoupe** [comment]
After some gdb and head scratching I can see that running byebug with a Shoes 'console' is going to be damn near impossible. (gtk main loop thread is a ruby thread which byebug will stop and moving ruby to another gthread is not a brilliant idea and no help for Cocoa. No need for 'C' code. 
 
Issue #17, #110 could be solved by using the pure ruby 'console' implemented in branch 'console',  debugger.rb. There is a conflict in 'purpose' or duplication with log.rb and irb.rb that we need to think about. 

Still mulling the design specs.  Just mimic io.getc and io.putc for $stdin/$stdout/$stderr. For sure we want the 'copy' button so we need a button for that. And a scrollbar and it always scrolls. And a clear button. Mimic/handle history/rb-readline/io-console things?  And --console cmd line flag to show it at startup.

**Comment by ccoupe** [comment]
I think I want to pursue the Gtk & Cocoa 'C' solution for Linux and OSX (maybe Windows but that already works),  Here's a screen shot of the very early Gtk console when you start shoes with --console.  - it runs a test loop 
![gtkconsole](https://cloud.githubusercontent.com/assets/222691/8199001/dc5b3d1a-146b-11e5-9e91-04104bbd7e2b.png)

Button panel layout is incorrect, It's not pretty. It Scrolls incorrectly. Doesn't do readline editing ... But it's wired up  to stdin/out and doesn't have to de construct Shoes formatted textblocks and the cmdline editing can be added with io-console and and or rbreadline. I think.

**Comment by ccoupe** [comment]
It's looking and acting  'not that bad' on Linux: 
![linux console](https://cloud.githubusercontent.com/assets/222691/8270124/b9afe3a0-178c-11e5-80db-616b998510f9.png)

Information at https://github.com/Shoes3/shoes3/wiki/Design:-New-Shoes-Console.

**Comment by ccoupe** [comment]
Started on the OSX --console. This is has almost nothing to do with Ruby or Shoes.  The Linux pty/backend compiles and should work pretty much as it does on Linux.
![osx-console](https://cloud.githubusercontent.com/assets/222691/8423049/b4c3320a-1ea0-11e5-9f9f-59aac2c48ac1.png)

Still have to hook up an NSScrollView to something Text Handling (NSTextView?)  and handle the keyboard.

**Comment by ccoupe** [comment]
Status report. The OSX code does the important things correctly for this 'feature'. The less important things are - setting the correct font on the NSTextView and some odd behaviour if you manually drag the scroll thumb up. Yes, those bugs do need to be fixed before closing the issue. 

It's also usable on all three platforms if your expectations are lowered to what was proposed (not much).  I'd really like to merge the console branch into master. The feature is mostly isolated to new files (.h., .c ,.m) - no need to change anything more in base Shoes - other than update the manual and changelog saying there is now  Shoes::show_console command and fixing the OSX and Linux packagers to support --console and maybe allowing it to be an option when packaging from the GUI. All of those are better done after merging to  master.

**Comment by ccoupe** [comment]
Getting near the 'good enough for me' point.  blog post http://walkabout.mvmanila.com/2015/07/24/need-a-console/

**Comment by passenger94** [comment]
:+1: excellent job :-)

**Comment by ccoupe** [comment]
I'll leave this open for a while, but I'm done with this **feature**. It does have to be converted to gtk3 with some #ifdefs and the gtk version should draw the icon like OSX does but it really doesn't matter.
![osx-console](https://cloud.githubusercontent.com/assets/222691/8892670/754ec696-3324-11e5-8786-40e26a02e5d2.png)

**Comment by ccoupe** [comment]
closing issue. 3.2.24 has a 'console' on all platforms. use Shoes::show_console.  No where near perfect - lowest common denominator and there are many denominators.
