### ISSUE TITLE
Problem with length of flows

### ISSUE THREAD

**Issue by Dassadar** [Shoes3/shoes3#132]
Hello,

With this simple code:
Shoes.app do
	flow {
		flow { para "a" }
		flow { para "b" }
	}
end

a is displayed in the first line, and b is displayed in the second line.
However, if I remove the inside flows, a and b are displayed on the same line.

What I need is to:
- have flows to be able to associate a click event
- have a and b on the same line

Can you please help?

Regards,
David

**Comment by ccoupe** [comment]
Shoes.app do
flow {
  stack(:width => 0.4)  { background green; para "a" }
  stack(:width => 0.4) { background red; para "b" }
}
end

**Comment by Dassadar** [comment]
Hello,

Thanks but it doesn't answer to my requirement as my a and b strings have
lengths that I do not know in advance. I would like to be able to tell to
the flow to adjust to the string length it contains.

Taking one step back to the use case, I want to be able to display a list
of items separated by commas. And when I click on one of the items, I
launch an alert providing more information on the item.
But since inscription is not clickable, my issue is there...

Regards,
David

2015-06-13 20:53 GMT+02:00 Cecil Coupe <notifications@github.com>:

**Comment by ccoupe** [comment]
You'll need 'cells' of some width (in pixels or %) other wise flow defaults to the width of the outer container.  Remove the :width => 0.4 above and watch how flow works with the background stretching to the width of the stack. Since the two stacks are larger than the window, flow wraps them. Html like Table lay outs can very difficult in Shoes.  You'll just have to experiment and figure it out.

Ruby sprintf can  format strings to the proper size.

link (Shoes::Link) does have a click proc but styling can be tricky if you don't like the default.

**Comment by ccoupe** [comment]
Closing issue.

**Comment by Dassadar** [comment]
Well, not sure it should be closed. There is no solution brought to the
issue. Could there be a development to have a click event over a stack?

**Comment by ccoupe** [comment]
A click on a stack? What would you do then? Iterate over the everything selected in the stack or flow to see what changed? You can do that already with clever programming and a 'modify this' checkbox in the front of flow/stack.  You can adjust flow width and stack height as you go if it's important to you.  Your request, as written would require a seriously long and long  rewrite of Shoes to accommodate. The solution is don't use Shoes if you need that pixel level of control.  Shoes just won't do it.  You can use wxRuby or RubyTk if Shoes 3.2 (a maintence release for crying out loud) or sweet talk the Shoes4  into rewriting their code

Closed does not mean forgotten. The bug report is still there for  for any one looking to rewrite shoes so it looks like wxRuby.

**Comment by Dassadar** [comment]
Well, my requirement didn't seem so complex at first... Within a flow,
I am adding dynamically text elements followed by a cross to remove
that element.
For example:
Item A (x) Item B (x) Item C (x)
It is possible to add new items to the list, then Shoes adds Item D
(x) and automatically adds a line if needed: that's great!
Now what I wanted to do was just to be able to click on any item to
get the description associated to this item as a popup: this is where
I get stuck. Problems:
- a para is not clickable
- if para is included in a stack, then the click could work but I
don't know the needed stack length (no automatic adjustment as for a
para)
Is my problem any clearer?

2015-07-30 8:45 UTC+02:00, Cecil Coupe <notifications@github.com>:

**Comment by ccoupe** [comment]
have you looked at Shoes::link ?

**Comment by Dassadar** [comment]
I cannot find any example showing how link works: can you please help?

2015-07-30 21:18 GMT+02:00 Cecil Coupe <notifications@github.com>:

**Comment by ccoupe** [comment]
It's easy to overlook Link in the Shoes manual. Just use the search function for link. It's a text element with a proc that is style like a hyperlink you the user knows they can click it.

**Comment by Dassadar** [comment]
Yes I had found it in the manual, but in practice I cannot find how to make
it work - I think I missed something. Could you please help with a two-line
example?

2015-07-30 23:30 GMT+02:00 Cecil Coupe <notifications@github.com>:

**Comment by ccoupe** [comment]
There are several examples in your Shoes samples directory. simple-slide.rb for example does this:
```
para link("slide out") { slide_out @lipsum }, " | ",
      link("slide in") { slide_in @lipsum }
```
Link is definitely one of the strange things in Shoes.
