### ISSUE TITLE
Gemming from github

### ISSUE THREAD

**Issue by aarmora** [Shoes3/shoes3#140]
I'm looking to use a custom repo for a gem.

Using `gem 'pdf-reader', :git => "https://github.com:aarmora/pdf-reader.git"` returns:

    Error in <unknown> line 0 | 2015-07-24 16:33:25 +0000
    Illformed requirement ["{:git=>\"https://github.com:aarmora/pdf-reader.git\"}"]
    C:/Program Files (x86)/Shoes/lib/ruby/site_ruby/2.1.0/rubygems/requirement.rb:100:in `parse'
    C:/Program Files (x86)/Shoes/lib/ruby/site_ruby/2.1.0/rubygems/requirement.rb:130:in `block in initialize'
    C:/Program Files (x86)/Shoes/lib/ruby/site_ruby/2.1.0/rubygems/requirement.rb:130:in `map!'
    C:/Program Files (x86)/Shoes/lib/ruby/site_ruby/2.1.0/rubygems/requirement.rb:130:in `initialize'
    C:/Program Files (x86)/Shoes/lib/ruby/site_ruby/2.1.0/rubygems/requirement.rb:63:in `new'
    C:/Program Files (x86)/Shoes/lib/ruby/site_ruby/2.1.0/rubygems/requirement.rb:63:in `create'
    C:/Program Files (x86)/Shoes/lib/ruby/site_ruby/2.1.0/rubygems/dependency.rb:58:in `initialize'
    C:/Program Files (x86)/Shoes/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:907:in `new'
    C:/Program Files (x86)/Shoes/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:907:in      `find_all_by_name'
    C:/Program Files (x86)/Shoes/lib/shoes/setup.rb:106:in `gem'
    get_insurance.rb:9:in `block in <main>'
    C:/Program Files (x86)/Shoes/lib/shoes/setup.rb:93:in `instance_eval'
    C:/Program Files (x86)/Shoes/lib/shoes/setup.rb:93:in `initialize'
    C:/Program Files (x86)/Shoes/lib/shoes.rb:134:in `new'
    C:/Program Files (x86)/Shoes/lib/shoes.rb:134:in `setup'
    get_insurance.rb:4:in `<main>'
    C:/Program Files (x86)/Shoes/lib/shoes.rb:497:in `eval'
    C:/Program Files (x86)/Shoes/lib/shoes.rb:497:in `visit'
    C:/Program Files (x86)/Shoes/lib/shoes.rb:143:in `show_selector'
    C:/Program Files (x86)/Shoes/lib/shoes.rb:186:in `block (4 levels) in splash'
    -e:1:in `call'

**Comment by ccoupe** [comment]
Try the shoes command, 'cshoes -g install ......` it should obey all the gem commands like 'cshoes.exe -g env'  or `-g list -l` . That will not install into C\Program File however. How are you trying to install the repo?

**Comment by ccoupe** [comment]
Solved in email.
