### ISSUE TITLE
Dinamic app title replacement

### ISSUE THREAD

**Issue by ProvGANG** [Shoes3/shoes3#145]
My idea is to change my app's title dinamically like this:

```ruby
@sh = Shoes.app :title => "First title" do
    @b = button do #some action to change :title
         @sh.title => "Something else" # this should set :title to a new value(as my pseudocode, not as a documented, right way)
    end
end
 ```

My idea of an app was a calendar which would have its title replaced as each month is changed by clicking button. Is there a way to perform it? Thanks in advance.

Btw., I've been away during summer and haven't kept with all the work you guys made. Thanks for keeping shoes alive and I'm happy that shoes is downloaded by hundreds of people a week as Cecil wrote in a blog, the number of people using shoes is probably much bigger.

**Comment by ccoupe** [comment]
You're in luck!  We  add that ability in Shoes 3.2 some time ago. Search the built-in manual for set_windows_title as this example shows
```ruby
 Shoes.app :title => "I'm Shoes" do
    button "change title" do
      Shoes.APPS.each {|a| a.set_window_title("No Shoes Here") }
      confirm "did the title change to No Shoes Here"
    end
 end
```
Will that work for you?

**Comment by ccoupe** [comment]
I'll also mention the number of downloads in the blog post was inflated by a large number of Chinese sites that download incessantly, one or twice every day even if nothing has changed.  The real number is probably closer to 5 to 20 per day but that is a decent number. I'm happy with that. Makes feel good.

**Comment by ProvGANG** [comment]
Wow, awesome, thank you, I'm not sure had I seen it in manual or couldn't figure the way how to do it but it is great that it exists.
