### ISSUE TITLE
edit_box improvements for 3.2.25

### ISSUE THREAD

**Issue by ccoupe** [Shoes3/shoes3#146]
edit_box has append(string) and scroll_to_end() methods.  #144 has lots of issues and may be delayed. These two were (almost) easy to add and they may be useful.  The call to scroll_to_end can be made by the Shoes script writer, as they see fit.

```
Shoes.app height: 400, width: 640 do
  stack do
    @tb = edit_box "foo", width: 0.8
    @tb.text = "Not your everyday edit_box\n"
    cnt = 0
    button "append" do
      cnt = cnt + 1
      @tb.append("append line #{cnt}\n")
      @tb.scroll_to_end
    end
    button "check" do
      confirm @tb.text
    end
  end
end
```

**Comment by passenger94** [comment]
nice :)
you mean "edit_box" in the title and comments :-D
