### ISSUE TITLE
Can't compile Shoes with/for Ruby 2.2.3

### ISSUE THREAD

**Issue by ccoupe** [Shoes3/shoes3#148]
The C macro ID2SYM is used in Shoes and was 'improved' in Ruby 2.2.x by using a new macro.  We fail when linking (rb_id2sym).  Also can't find rb_str_new_static().  It was only a matter of time until MRI moved the C goal posts.  Not sure yet how difficult or wide ranging this is going to be. Has to be done, sometime.

**Comment by ccoupe** [comment]
I would like some feedback @BackOrder, @passenger94 .  I think I should finish up the nothing much to see 3.2.5 and release it. Then create a git branch 'federales' which will hold it at that (source) state - only emergency bug fixes would be made to the federales branch. The git 'master' branch would then be the 3.3 in work in progress.

3.3 would be GTK3 only for Linux and Windows (delete those #ifdefs GTK2) . Ruby 2.2+  plus brilliant ideas that push the definition of what shoes is. Less "maintenance release" mentality.  The existing bugs and requests carry forward of course.

**Comment by passenger94** [comment]
hi @ccoupe :-)
sounds good, shoes 3.2 looks stable now, i made an attempt at building with ruby 2.2... looks awful !!!
let's hope it's just a simple bolt to unlock somewhere ...

i made some attempts to bring animated gif to shoes, everything is in place to work provided we upgrade to the latest gif library (libgif 5.1.1), which simplifies greatly even the actual code.
(i can access all the frames and respective pixels for rendering and loop through them)
Now to make it work some changes are needed to the whole image structure : essentially where in the chain of method calling do we slide the call to animated gif which needs a new thread (**g_timeout_add** i think), also do we loop indefinitely, provide a way to pause/restart animation ?

**Comment by ccoupe** [comment]
@passenger94 Shoes 3.2.25 on Windows is not stable.  Sigh. A small matter of debugging.

One of the shoes4 folk did some recent work on animated gif and I think it was successful (just my memory so you'll have to check their issues). We should be try to stay compatible if possible. 

In my dreams I wonder If getting the audio/video widget working again could be possible. Very difficult to do cross platform. It was a hack from the beginning which is why it's not in 3.2 or 4.

**Comment by passenger94** [comment]
like i said vlc video/audio is working on my video branch :-) Far far far from being cross platform though :-D

**Comment by BackOrder** [comment]
I haven't sync with Shoes repo for roughly 4-5 months. A little concerned that Windows dependencies and other things cause problems. It doesn't seem a smooth transition according to what @ccoupe wrote a while ago.

**Comment by ccoupe** [comment]
@BackOrder - the gtk3 merge into master broke some Windows stuff. I'm not worried. Just a matter of tracking them all down.

**Comment by ccoupe** [comment]
in re: video 
Could we  include in each 3.3 Shoes download  an FFI based library/gem/ext that exposes a Shoes friendly set of methods for play/pause/rewind/stop/loop/volume-mute/up/down/whatever? That ffi interface doesn't have to be VLC for everyone. It could be Quicktime (or whatever OSX uses now) or what ever is in Windows.  Only Linux would have to find a VLC install. Bonus points for a Linux dbus interface.

**Comment by BackOrder** [comment]
@ccoupe keep me updated about Windows version. Whenever you get it working, I shall resume some work on it. I haven't forgot about your request for eBook code. Also, the addition of readline might allow to use the real IRB.

**Comment by ccoupe** [comment]
Shoes 3.2.25 was just released. Windows works fine.  Readline requires a tty/pty or windows command line shell so it can't be hooked up to the IRB you wrote.  IReadline does work with the new mostly independent of Shoes console introduced in 3.2.24 but it's not really Shoes in it.

**Comment by BackOrder** [comment]
What I am talking about is to overwrite input and output of the original IRB provided with Ruby and integrate it into Shoes. I have attempted many ways to do that but readline would be the easiest. Unfortunately, according to your comment, it needs a console window attached.

**Comment by ccoupe** [comment]
It's a classic tradeoff. The new console isn't pretty (windows) but the functionality is there for easily dealing with programs like IRB or pry and should give a pretty complete command line experience. (including copy to clipboard )And it can be popped up from Shoes (unless it's already on screen). 

https://github.com/Shoes3/shoes3/wiki/Design:-New-Shoes-Console

**Comment by ccoupe** [comment]
I'll create a new branch for this issue because it's not going to be pretty. In Ruby 2.2 they added two classes of :symbols - those that can be garbage collect and those that can't. Previously no :symbols were GC eligible so that is what Shoes did and should probably continue to do for most uses of ID2SYM.  

My first idea is simply do a textual replace of ID2SYM with SID2SYM and then Shoes will #define SID2SYM based on ruby < 2.2 or >= 2.2.0. config.h? Will that work? I don't know. It's easy to get C macros very wrong.  Anybody with a better idea?

**Comment by passenger94** [comment]
The problem is there, in Ruby 2.2, in  ID2SYM ?
Where can we find the doc for difference(s) between pre 2.2 and after ?

**Comment by ccoupe** [comment]
That doc barely exists. Find clues in the Changelog (pre release of 2.2 of course) 
```
ccoupe@bronco:~/.rvm/src/ruby-2.2.3$ more ChangeLog 
```
And then you have to google for something like 'ID2SYM'  and  get to one of the mail list archives.
ID2SYM is not the only problem, but it needs to be fixed first before tracking down the others. I don't your error message. 'cd Projects/shoes3; rvm use 2.2.3; rake clean; rake`

**Comment by passenger94** [comment]
my ruby-2.2.3/lib/pkgconfig/ruby-2.2.pc is missing the `-L'$${ORIGIN}/../lib'`part in LIBRUBYARG_SHARED
With it added in RUBY_LIB it compiles fine !???! just me ?

**Comment by ccoupe** [comment]
It links? and runs for you.? Getting odd.  Clearly our rake files are different. This could be good news for me.

There are parts of /make/linux/task.rb and maybe env.rb that don't parse a 2.2.x correct. There may be a version problem in the shoes startup script (Tight Shoes)

**Comment by passenger94** [comment]
No works fine ! except ftsearch

**Comment by passenger94** [comment]
The issue with my setup is in **ruby-2.2.pc**

**Comment by ccoupe** [comment]
the line from my ruby-2.2.pc
```
LIBRUBYARG_SHARED=-Wl,-rpath,'$${ORIGIN}/../lib' -Wl,-R'$${ORIGIN}/../lib' -l${R
UBY_SO_NAME}
```

**Comment by passenger94** [comment]
Same line here !
there should be a -L'$${ORIGIN}/../lib' 
look into ruby-2.1.pc

**Comment by ccoupe** [comment]
So my premise with ID2SYM was premature. Good. We can fix the env.rb 

ftsearch problems may involve iostring encoding changes/defaults. That was the main problem with 1.9.3+

**Comment by passenger94** [comment]
lots of warning during ftsearch compilation but that was always the case ....
chipmunk is failing too ...
something in building extensions ... (lots of warning, but also like usual)

gems are ok, was just me, bad install !

**Comment by ccoupe** [comment]
Check tasks.rb to see if it's copying the ext correctly in re: version numbers

**Comment by ccoupe** [comment]
We're on the same page. Blank splash screen , Shoes console says can't load ftsearch. I've seen this before!

**Comment by passenger94** [comment]
Yes, works :-)

Something like this should give the correct RUBY_VERSION in cache.rb
(copied from env.rb)
`pkg-config --variable=ruby_version #{EXT_RUBY}/lib/pkgconfig/ruby-#{rv}.pc`

**Comment by ccoupe** [comment]
Shudder.  We can't trust pkg-config at build time to be correct, why would we trust if to be correct at run time? Linux is not the only platform where pkg-config screws up with bad pc files or old versions.  Pkg-config can not be trusted.

**Comment by passenger94** [comment]
ok, didn't knew that  !

**Comment by ccoupe** [comment]
@passenger94 - think of all the knowledge and fun you would gain by building a Tight Shoes in a schroot. Or even the MinGW build for Windows. The dream (half unrealized) was to use any  version of Ruby to build Shoes using a different Ruby. It's a very nasty problem because of subtle  ties to RbConfig. and pkg-config. 

Back to the 2.2.x  issue. I've uploaded a Shoes 3.3.1 beta for Linux x86_64 at http:///walkabout.mvmanila.com/public/shoes/shoes-3.3.1-gtk3-x86_64.install that has Ruby 2.2.4, gems 2.5.1 and newer versions of nokogiri and byebug. Safe to install or uninstall.

**Comment by passenger94** [comment]
I'm Drooooling ! :-D
i didn't realized it was to the point one can't rely on tools made for that ! But i guess the Wild is named that way for a reason :-) 
oh, btw, i don't understand what **cshoes** can buy me on linux, i have symlink to shoes already ??

**Comment by ccoupe** [comment]
That is an interesting finding about the Shoes url binding.  Worth noting in the manual. I don't know if it's worth creating an issue for because if you structure your app that way there is no mixing styles. Good thing packager and Cobbler don't use that style. 

FWIW , I've noticed a 4MB decrease in download size for 3.3.1 with ruby 2.2.4 for x86_64 - probably because it doesn't include useless ri/rdoc.

**Comment by passenger94** [comment]
ouch !
this one ? `static int w32_cmdvector(const WCHAR *, char ***, UINT);`

did you find the alternative ?

**Comment by ccoupe** [comment]
Shoes needs this to process --ruby (see bin/main.skel). The change is not in the ruby changelog either. Bad Ruby!

One option is to create a patch to ruby to set the visibility to extern and remember to apply the patch for every Ruby update used in Shoes. Ick!

Another solution is to copy Ruby win32/win32.c w32_cmdvector() code and name it shoes_win32_cmdvector. That is what probably what I'll do. We won't get future  Ruby fixes for that code unless we know to look for them. Lesser of two evils.

**Comment by passenger94** [comment]
regarding url, with this change in shoes.rb, it fixes the problem in manual
```ruby
  def self.mount(path, meth, &blk)
    unless @mounts.empty?
      # checking if app changed
      @mounts.clear if meth[0] != @mounts[0][1][0]
    end
    @mounts << [path, meth || blk]
  end
```
meth is an array whose first member is the self of the Class who subclasses Shoes, so checking if it has changed should work ...

**Comment by ccoupe** [comment]
That's appears to be a bug fix! I think  we need an new  issue so we don't loose tracks of what's been fixed.

**Comment by ccoupe** [comment]
Finally got Shoes-3.3.1 to build for OSX with Ruby 2.2.4 with updated gems. the Ruby Lords changed the arch name from x86_64-darwin-13.0 to x86_64-darwin-13 which was source of much debugging. 
Beta at http://walkabout.mvmanila.com/public/shoes if any one cares.

**Comment by ccoupe** [comment]
I do believe I can close this issue. Shoes 3.3.1 downloads include  Ruby 2.2.4 and compiling your own Shoes may need 2.2.3 or 2.2.4, depending on platform.

**Comment by passenger94** [comment]
:+1:
