### ISSUE TITLE
Shoes 3.2.25 is released, yet milestones incomplete

### ISSUE THREAD

**Issue by BackOrder** [Shoes3/shoes3#150]
How come Shoes 3.2.25 has been released with 7 opened issues?

**Comment by ccoupe** [comment]
Because some people don't like it if I close issues without telling them? ;-)

**Comment by BackOrder** [comment]
Closing issues have to be relevant. Though it begs the question why the given milestone is released incomplete. Isn't it all rushed?

Issue #19, #44, #143 seem to be completed. You recently added "Clean up for Walkabout" on milestone 3.2.25 — why is that? Are GTK 3 support #92 and edit_box improvements #146 completed? I know for a fact that #141 is not completed.

You can leave a message in closing an issue, that would qualify as telling them. It's still possible to reopen anyway. My view on this is that all issues should be closed on a release or, if it's really not possible, those incomplete should be reassigned to another milestone. It makes everything easier to track.

**Comment by ccoupe** [comment]
Lighten up, my friend. All releases are rushed. I don't know how to tell you this - Shoes is not very important to that many people. If it was important, people would be talking on the new mailing list. They would get Shoes 4 out the door. They would would respond to people posting issues on the old Shoes 3.1 github (3 issues today) . They would assign themselves issues, when asked:  #141. They would close issues they opened after testing the solution. 

That would be a perfect world and it's not happening! We muddle along.
