### ISSUE TITLE
Must hide slot before removing

### ISSUE THREAD

**Issue by kylekyle** [Shoes3/shoes3#151]
This bug was first observed [6 years ago](http://stackoverflow.com/questions/630681/removing-a-slot-on-a-child-button-click), but still seems to be lurking. In certain situations, you must first hide a slot before removing it. Here's an example:

This **does not work**:

```ruby 
Shoes.app do
  slot = flow do 
    para 'Click me!'
    click { slot.remove }
  end
end
```

This **does work**:

```ruby 
Shoes.app do
  slot = flow do 
    para 'Click me!'
    click { slot.hide; slot.remove }
  end
end
```

You can verify that the slot is truly removed from the parent in the second case. Not sure why hiding is necessary, but this is a pretty easy fix: The `remove` method should simply hide the slot before removing it.

**Comment by passenger94** [comment]
hi @kylekyle 
in fact the slot **is** removed but the app is not refreshed, try to resize your first example and you'll see the slot disappearing (tested on linux)
This needs to be adressed nonetheless

**Comment by BackOrder** [comment]
There is a huge concern about the behaviour change, as far as maintenance goes. The manual is however explicit:

> Removes the slot. It will **no longer be displayed** and will not be listed in its parent's contents. It's gone.

Hiding is not necessary but invalidate the window to force a refresh might be when the element is within the displayed area. (No need to refresh elements not on screen)

**Comment by passenger94** [comment]
adding **shoes_canvas_repaint_all(self);** in canvas.c => *shoes_canvas_remove* method like following code works for me
the clue was indeed in *shoes_canvas_hide*
needs some polishing to check if element is displayed or not !

```c
VALUE
shoes_canvas_remove(VALUE self)
{
  shoes_canvas *self_t;
  Data_Get_Struct(self, shoes_canvas, self_t);
  shoes_canvas_empty(self_t, TRUE);
  if (!NIL_P(self_t->parent))
  {
    shoes_canvas *pc;
    shoes_canvas_remove_item(self_t->parent, self, 0, 0);
    Data_Get_Struct(self_t->parent, shoes_canvas, pc);
    if (pc != self_t && DC(self_t->slot) != DC(pc->slot))
      shoes_slot_destroy(self_t, pc);
    shoes_canvas_repaint_all(self); // new
  }
  shoes_canvas_send_finish(self);
  return self;
}
```

**Comment by passenger94** [comment]
because i stumbled upon variations on that same problem, needing to refresh (no, i was wondering if a refresh method

**Comment by passenger94** [comment]
oops mistake sorry!

because i stumbled upon variations of that same problem, needing to refresh (rarely though) i was wondering if a refresh method would be something valuable to add to the shoes tool set ?

**Comment by ccoupe** [comment]
@kylekyle - thanks for reporting.  @passenger94 - that fix does work on OSX as well as Linux. Excellent! Please push your change up or do pull request.

There are likely to be other places in the code that need to call shoes_canvas_repaint_all() or as suggested we could add a canvas.refresh() which brings up @BackOrder's point that this could break existing Shoes scripts.  It could do that but most likely any one who is managing slots that way has a workaround (for instance cobbler uses clear/append). I'm not going to worry about backwards compatibility for this one - and we don't have to fix the manual for this one!

I'm going to create a new issue for the refresh method.

**Comment by passenger94** [comment]
doing a PR on federales branch

**Comment by ccoupe** [comment]
I'd rather have you take credit in the commit logs for the fix you created.  I can refix my env.rb (if needed) - I think that line was added with the 2.2.x experiment.  Send in the pull request or push if you can.
