### ISSUE TITLE
pango-querymodules

### ISSUE THREAD

**Issue by ccoupe** [Shoes3/shoes3#156]
This is a fun one. It seems recent OSX builds don't run on 10.9 systems.  I believe it was a brew update that brought in a less than perfect glib. There is no official way to delete a brew update. One can only move forward. So i installed a newer glib and that problem was replaced with a pango-querymodules problem.  After much research, pango was updated to 1.38 in the above glib update.

Turns out there is no pango-querymodules (or pango/modules/*.so). They designed them away. There's a fair bit of Shoes infrastructure that isn't needed now. Even the need for the shell script that starts Shoes on osx is questionable. For the moment OSX doesn't work at all but it's fixable (soon I think). When we get around to building new dependence for Windows - this feature will strike there too. 

some updates are bad. some updates are good. sigh.

**Comment by BackOrder** [comment]
This might be interesting but how will it play on legacy systems?

**Comment by ccoupe** [comment]
According to brew folk where I complained, pango built those modules.so  static (inside the pango.so) so in theory it's a change the could work for 10.6 but brew doesn't support 10.6 very well so you can't know until you fail and then you can't back out. Bad brew! There are other issues with Shoes 10.6. 

Shoes is back to working on 10.1. Still failing in 10.9 but at a different place in pango.dylib

**Comment by ccoupe** [comment]
From the pango 1.3.8  NEWS file:
```
Overview of changes between 1.36.8 and 1.37.0
=============================================
- Pango modules, engines, and config have been removed (#733882)
- Added pango_fc_font_map_config_changed() (#748767)
- Added pango_fc_font_map_[sg]et_config() (#547671)
- Added pango_matrix_get_font_scale_factors
- Lot of API has been deprecated
- Fix CoreText font fallback
- General build fixes
- Win32 build fixes
```
Shoes/Windows uses 1.36.8 so it's not infected. Yet.

On 10.9, Shoes is crashing early in world.c shoes_world_alloc() in  the call to pango_font_description_new() which (in pango/fonts.c) is a very simple function. It calls g_slice_new which just happens to be where things were crashing on 10.9 for the original bug report.  So, updated  versions of glib appear to not be compatible with 10.9.  Bad bad brew and the people who claim it's been a long time since you upgraded". This is a mess for 10.9.

**Comment by ccoupe** [comment]
Further discussion with some brew folks have convinced me that brew is not the way to manage dependencies for OSX.  Which means building Ruby from source instead of rvm but that can be a plus (there is a bug report about rvm droppings in Shoes). Of course this is going to take some time and debugging but I can leverage the shoesdeps stuff I built earlier.

**Comment by ccoupe** [comment]
Blog post http://walkabout.mvmanila.com/2015/10/21/too-dumb-for-my-shoes-3-2-26-is-osx-only/ 

Upshot is I'm back to building 3.2 and 3.3 for OSX (and windows and linux). OSX works fine without pango-querymodules .  That change hasn't been made to Windows yet so I can't close this issue  but I can drop the severity level to 'less panic'.

**Comment by ccoupe** [comment]
Pango-querymodules isn't used in Windows or OSX and I've fixed OSX. I'm calling this one done.
