### ISSUE TITLE
Changing font size in list_box

### ISSUE THREAD

**Issue by Dassadar** [Shoes3/shoes3#170]
Hello,

Elements in my list_box take a longer width than the list_box width.
How can I change the font size of elements within the list_box please?

Regards,
David

**Comment by ccoupe** [comment]
Is this issue https://github.com/Shoes3/shoes3/issues/109 the same? If so, there will be some improvement in Shoes 3.3.0 (Windows and Linux) but it may not satisfy everyone.

**Comment by Dassadar** [comment]
yes
