### ISSUE TITLE
Svg: gtk complains about not a widget when closing

### ISSUE THREAD

**Issue by ccoupe** [Shoes3/shoes3#176]
I'm going to make this a new issue so it doesn't get lost in long discussions about other svg details.
The error message looks like this
```
(shoes:8377): Gtk-CRITICAL **: gtk_widget_queue_draw: assertion 'GTK_IS_WIDGET (widget)' failed
```
And only happens when closing from the window adornment app/window close button which us gets to 
shoes_app_gtk_quit- > shoes_app_remove in app.c:99 -> shoes_app_clear app.c:86 ->
     shoes_canvas_clear (canvas.c) -> shoes_canvas_empty
However the last two get called a lot (even at startup) . 

shoes_ele_remove_all  (ruby.c:665) is called a lot and invokes the s_remove method which we do have for svg and is called before the complaints. I suspect shoes_svg_remove does not do the correct thing. It also uses slot->contents

**Comment by passenger94** [comment]
```ruby
Shoes.app do
    flow height: 200 do; end
end
```

here, it's ok without :height attribute but complains with `(shoes:10475): Gtk-CRITICAL **: gtk_widget_queue_draw: assertion 'GTK_IS_WIDGET (widget)' failed`  with  it !!

on svg and master branch, a Gtk3 issue ?

**Comment by ccoupe** [comment]
That is an excellent discovery. I suspect the key  line is canvas.c:1695 in shoes_canvas_repait_all which is designed to stop if their is nothing to be done.

**Comment by passenger94** [comment]
ahhh ! you are right!!!
canvas.c, line 342 :` canvas->stage = stage;`
needed when clearing the canvas but get in the way when removing everything !
so adding line 1214 `self_t->stage = CANVAS_EMPTY;` might resolve the problem
But what is the link to the height attribute ???

**Comment by passenger94** [comment]
also in good_flip.rb if we  do `@animation.remove`, later when closing from the window adornment, it's crashing because Shoes routines to remove all elements ( namely app->extras for animation ) don't find the anim it thinks it will find and crashes !
We need to guard against this, because there is surely good reasons one would want to explicitly remove an element

**Comment by ccoupe** [comment]
shoes_svg_remove needs to behave more like shoes_basic_remove which is used by Image, and many more things.

**Comment by passenger94** [comment]
yes, i believe it boils down to 
```ruby
rb_ary_delete(canvas->contents, self);
shoes_canvas_repaint_all(self_t->parent);
```

**Comment by passenger94** [comment]
**shoes_canvas_remove_item** (called by all timer's remove function with **t** param set to 1 for app->extras) is doing something strange :
https://github.com/Shoes3/shoes3/blob/svg/shoes/canvas.c#L1160
because then later when looping to remove all elements in the array it do finds one, albeit a nil, and tries to process it ! it should remove it, not insert a nil.

Maybe the safer is to insert a null pointer check in remove elements routines ?

**Comment by ccoupe** [comment]
If I read that code correctly if their a list of item then it the 'item' is in the middle of the list, it needs
to be replaced with 'something' . If so then one option, if possible is to compact the list. I don't see a convenient rb_xxxx method to do that. 

The other choice is as you have suggest insert some NIL_P checks to return or skip calling something that won't work or even put the ` if NIL_P- return ()` at the top of the called function. I would be be comfortable with either.  I see nothing wrong with sanity checks at the top of a function.

This bug has probably been around a long time.  Linux people don't seem to mind warning messages on the console and of course if it's run from the menus theire is no console window to show them. I've seen some very odd messages running some apps from a terminal.

**Comment by ccoupe** [comment]
Whoa!  Is this possible? shoes_native_remove_item() gtk.c:329 is a stub. It does nothing.

**Comment by passenger94** [comment]
i think it's not needed 
only time it might be used is in shoes_control_remove (where param **c* is 1)  https://github.com/Shoes3/shoes3/blob/master/shoes/ruby.c#L3101
and just a few lines later removing the native control is taken care of https://github.com/Shoes3/shoes3/blob/master/shoes/ruby.c#L3107

**Comment by ccoupe** [comment]
I believe this issue is fixed. Good job!
