### ISSUE TITLE
Svg:  export and save methods

### ISSUE THREAD

**Issue by ccoupe** [Shoes3/shoes3#177]
issue #54 is a little long.  The two Svg methods we haven't done much thinking about are export and save. 

I propose, humbly of course is that export is going to be a lot like snapshot but it firsts renders svg[handle] into a gdkpix (a raster) and then executes the block arg, if given.  so the api would be 
`svg.export {filename: , group:, svghandle:}, [&block]` where group: and handle: are optional and mutually exclusive defaulting to nil (all). if given, block would allow some raster based Shoes things  just like snapshot does.

save will only work with vector formats (ps, pdf, svg). Inside its going to have to create the proper cairo_surface, set up the cairo_matrix, and  transforms much like it is done in shoes_svg_draw_surface(). Then rsvg_render_cairo_sub() to  the  vector surface (file). The api would be:
`svg.save {filename: , group:, svghandle:, dpi: }`

Note there is no optional &block for save() since there is no Shoes canvas for the drawing surface on which to execute Shoes code.   Group: and svghandle: are mutually exclusive, default is all (nil). Here, the user can set the dpi. I suspect they might **have** to set the dpi to get anything meaningful for ps or  pdf.  

[Some minutes later]  export() should not have a block either  (no Canvas).  Since we can tell from the filename: <str> suffix whether it is a raster (png, jpeg) or vector output that is needed export() and pick the cairo_surface and rsvg render method.  So the proposed api is
```
svg.export {:filename => <path>, :group=> <string>, :handle = <svghandle>, :dpi => <integer>}

**Comment by passenger94** [comment]
Seems nice to me, just the dpi, i think, for saving to ps or svg doesn't matter, as they are vectors, user have control later on it (leaving default, or what is the actual value)
-  for pdf, is it embedded as a vector or a raster ?  -

**Comment by passenger94** [comment]
for now in the PR export is `svg.export(dpi, filename)`
could be changed to a hash parameter at will, no problem.

handle is not needed (we always have access to it via svghandle() method on svg object) and is not of interest in the export (as an option/parameter i mean)

I tried the gdkPixbuf route, it works but the rendered colors were totally wrong !!!?? didn't found why.
 
As stated in the PR, the whole canvas is rendered, otherwise the only possible change is on the dpi
Still an option, if needed, but would be easier to do via the gdkPixbuf, once the rendering problem is fixed ...

**Comment by ccoupe** [comment]
I'd rather have the export method raise an error if the path arg is missing instead of opening a dialog
(which should be done by  rb_ruby eval("ask_file_save") which is a pain. It's still early though. I added a save button to good-svgviewer for testing purposes
```ruby
      button "Save" do
        savep = ask_save_file
        if savep
          @current_svg.export savep
        end
      end
```

**Comment by passenger94** [comment]
ok
why rb_ruby eval("ask_file_save"), instead of calling directly filechooser ?

**Comment by ccoupe** [comment]
```
    path = shoes_dialog_chooser(self, "Save file...", GTK_FILE_CHOOSER_ACTION_SAVE, _("_Save"), attr);
``` 
is not OSX friendly.

**Comment by ccoupe** [comment]
This is a good starting point for raster output (.png) but I'm really curious if we can create and render to svg surface from a svg widget. 
* http://cairographics.org/manual/cairo-SVG-Surfaces.html

**Comment by passenger94** [comment]
shoes_dialog_chooser, just a matter of #ifdef no ? (advantage here is we can customize the dialog), anyway, let's the user have total control over the file !

> render to svg surface from a svg widget

i think that it should be straightforward, we just have to follow the snapshot processing, almost using it !
only difference is in the drawing part : in snapshot there is a block that is used to draw on the provided surface, here we have an svghandle, roaming around.
Yes, I can confirm it works !


i got GdkPixbuf working but no way to set dpi ??? i tried all the set_dpi methods of svghandle before querying the pixbuf and also the options in gdk_pixbuf_save() method, which should officially accept a "x-dpi" and "y-dpi" option, but don't recognize them ??
If we have to manage dpi ourselves (using internal rsvg and Shoes rendering, like in the present incarnation of export), there is no benefit of using GdkPixbuf !  Thoughts ?

**Comment by ccoupe** [comment]
I think we need to wake up @BackOrder - dpi matters to him for reasons I still don't understand. We could dig through the libsvrg source and find out where it's being used and for what.  If i remember the last time I looked at it, I thought it was creating a slightly different cairo_surface_t format (24 vs 32?) which might account for odd coloring. Assuming I remember correctly. 

Until some one actually has a reason to export/save an svg, we really don't know whether our work is done or not. png, ps, pdf,svg outputs work (w/o the dpi). Think we're done on this #177 issue until told otherwise.

**Comment by passenger94** [comment]
dpi is working for png !!!

**Comment by ccoupe** [comment]
Please issue the PR against master.  I really, really want to get 3.3.0 released very soon, whether edge cases work or not.

**Comment by passenger94** [comment]
??? Already done, like you said !
Shoes3:master is up to date with all commits from passenger94:svg.


See #185 to look for details about export and save methods

**Comment by passenger94** [comment]
With the :canvas => true option, i had in mind to be able to draw everything that is on the canvas not just only the svg, so we can than save or export  a whole new creation :-D made of our svg + Shapes, background, whatever is on the canvas (i believe) some glitches though with Text in svg

It's Done ! :-)

**Comment by ccoupe** [comment]
Is this issue completed?
