### ISSUE TITLE
how to uninstall shoes in Linux ?

### ISSUE THREAD

**Issue by omgbox** [Shoes3/shoes3#182]
how to uninstall everything ?

**Comment by ccoupe** [comment]
On Linux you navigate  to ~/.shoes and remove federales
```
`cd ~/.shoes
rm -rf federales
```

**Comment by ccoupe** [comment]
That's an incomplete answer. Getting rid of the menu is not as easy. It depends on your Linux & desktop. If that fails see you'll need to read the man page for xdg-desktop-menu and find the Shoes.desktop file. Cd to there an do the xdg-desktop-menu for uninstalling.

**Comment by ccoupe** [comment]
FWI, Shoes 3.3.0 (beta) at http://walkabout.mvmanila.com/2016/01/07/getting-closer-shoes-3-3-0/
has an uninstall menu for Linux  so you can install 3.3.0 and then uninstall it and your menus should be clean.  - You still need to remove federales files in ~/.shoes. 

Is there a reason you are will to share why you don't like Shoes?

**Comment by ccoupe** [comment]
Closing unless @omgbox reopens it.
