### ISSUE TITLE
sticky shoes urls

### ISSUE THREAD

**Issue by ccoupe** [Shoes3/shoes3#187]
If one uses the url/visit method of creating a shoes App,  if you run then run a  second one which also uses url/visit in the same Shoes process (like the manual will do) it always uses the first app for url '/' even if you closed it. Congratulations to @passenger94  for even noticing this very odd behaviour in #148 and even better for providing options to fix it.

>regarding url, with this change in shoes.rb, it fixes the problem in manual
```ruby
  def self.mount(path, meth, &blk)
    unless @mounts.empty?
      # checking if app changed
      @mounts.clear if meth[0] != @mounts[0][1][0]
    end
    @mounts << [path, meth || blk]
  end
```
meth is an array whose first member is the self of the Class who subclasses Shoes, so checking if it has changed should work ...
Otherwise `@mounts` is appending paths, no matter what and Shoes take the first one it finds...
Another approach could be to always take the last one (the more up to date)... or prepend to the array
```ruby
def self.mount(path, meth, &blk)
  @mounts.unshift([path, meth || blk])
end
```

**Comment by ccoupe** [comment]
I have no strong opinion of what is the best solution.  Maybe remove the `@mount` when the app was closed? What if someone really want two Apps on screen so there should be two  "/" urls.. I do learn towards allowing that to happen so maybe visit needs some help?

**Comment by passenger94** [comment]
Hehe interesting !!!
If we open several "Class" app **at the same time**, via a regular Shoes.app (Case of the Manual app) there is a clash with the '/' route (that route is the mandatory entry point for all app created via  subclassing Shoes) so there can be only one '/' route per Shoes session. (of course you have to take care that  other routes are specific to each app - not the same -)
Now this is a super edge case as except for Manual where we want to show demos of possible Shoes apps, one probably never want to do that.
Manual showing **one app after the other** (ie once first is closed) is possible with the fix.

Also there is two visit methods one Ruby, one C :
- the ruby method is called by C shoes_load() at start-up or by ruby when asking to open a new script file
- the C method - ultimately shoes_app_visit() via shoes_app_goto() - is called by ruby in shoes script : That's the one used in the script ! Then calling ruby's Shoes.run()

So, unless you are Yma Sumac (please double check), messing in this amazing fancy dress is going to happen over my dead body :-D !

**Comment by ccoupe** [comment]
I am not Yma Sumac (R.I.P) and I don't want to mess with your your dress with a variable '/'
