### ISSUE TITLE
Shy tmpdir removal removes content but not directory

### ISSUE THREAD

**Issue by BackOrder** [Shoes3/shoes3#19]
Fix 33c041cc650a01fc7b4e3af9dab42e4d194c16d1 removes the content of the tmpdir created by a Shy app but not the directory itself.

**TEST SCENARIO on _Windows_**
* Open a file browser on _%TEMP%_
* Open a Shy file with Shoes
* Check _%TEMP%_ for the presence of a directory named _shoes-&lt;Shyname&gt;.&lt;random number&gt;_
* Close the Shy app
* Check _%TEMP%_ again

_EXPECTED RESULT_ **_shoes-&lt;Shyname&gt;.&lt;random number&gt;_ should be entirely removed**

**Comment by ccoupe** [comment]
This seems to be a Ruby windows bug. I've added a another File.exist? on the dir and any attempt to
delete it segfaults.  Very odd. Maybe this is why people don't clean up %TEMP%

**Comment by ccoupe** [comment]
Shoes was cd to the expanded shy dir so Windows refused to delete the dir. We can cd to home and then delete the the exanded shy.  lib/shoes.rb aro line 536:
``ruby
  def self.clean
    if @shy
      Dir.chdir() # do it from HOME 
      FileUtils.rm_rf(@tmpdir, secure: true)
    end
  end
```
Since this is done at quit time, the process is going to die and getwd/pwd will be where ever is normal for the platform.

**Comment by Shy** [comment]
Got a notification about this today. Was a little confused :wink:

**Comment by ccoupe** [comment]
@shy - I think we've  found a github error. Our ruby code has a variable '@shy' and it may have been typed in a issue without proper escaping. Sorry.  I'll try to remove you from the issue.
