### ISSUE TITLE
Add Ruby version to Shoes splashscreen

### ISSUE THREAD

**Issue by diasks2** [Shoes3/shoes3#193]
This is a low priority issue, but it would be helpful to show which version of Ruby the Shoes build is using. I think this could go under the Shoes build info. For example

Welcome to
SHOES
walkabout
build 3.3.0 r3229
Ruby version X.X

**Comment by ccoupe** [comment]
You can get the Ruby version and more from Cobbler  aka  Maintain Shoes. "Shoes Info" button. Historically, the splash screen was kept as uncluttered as possible - for old laptops with tiny screens?  Or,  don't confuse newbies  with too much info ...?  While still maintaining some of  _why's whimsy/arty spirit. 

While their aren't a lot of Ruby newbies on the Mailing List or posting issues here and _why went Walkabout, I still kind of believe in that. I'm often wrong and too stubborn.

**Comment by diasks2** [comment]
Ok, makes sense. I didn't know that about Cobbler. I'll close this issue then.
