### ISSUE TITLE
background default size

### ISSUE THREAD

**Issue by ccoupe** [Shoes3/shoes3#2]
Was issue #042 at https://github.com/shoes/shoes/issues/42

Problem still exists in 3.2

**Comment by passenger94** [comment]
testings by my side makes me think that this fix is working
not entirely confident though, needs more testing

replacing this line
https://github.com/Shoes3/shoes3/blob/master/shoes/ruby.c#L511
by  `dh = (max(canvas->height, canvas->fully - CPB(canvas)) - CPY(canvas));`
removing check for `ORIGIN(place)` happening in CPH(canvas)

**Comment by ccoupe** [comment]
@passenger94, the bug snippet to use is bugs/bug042.rb (some of the snippets are named with their 3.1 issue numbers. Sorry for the confusion.

**Comment by passenger94** [comment]
@ccoupe i was basically using that one :-) 
i've tested the fix above on my system, it's *seems* OK but changing things at that peculiar place might have implications elsewhere and beyond.
step by step, i've located the problem there, apparently it occurs only for `REL_TILE` which are Backgrounds, Borders and Patterns
basically which the check of `ORIGIN(place)` (not sure but might be : first placement ?) the background wasn't aware of the real height of the host canvas

btw i've made a gist with `shoes_place_decide` documented, WIP, feel free to comment, add, correct,  etc...
https://gist.github.com/passenger94/405902e0aa4261935f67

**Comment by ccoupe** [comment]
#355 is a nicer duplicate of this bug. Fixed in branch 'background'.  Closing this issue.
