### ISSUE TITLE
NSIS 3.0b3 incompatible 

### ISSUE THREAD

**Issue by ccoupe** [Shoes3/shoes3#204]
The shoes nsis script fails 

```
Processing script file: "Shoes-3.3.1-gtk3-w32.nsi" (ACP)
Error: can't find bitmap
Error in macro MUI_INTERFACE on macroline 87
Error in macro MUI_PAGE_INIT on macroline 6
Error in macro MUI_PAGE_WELCOME on macroline 5
Error in script "Shoes-3.3.1-gtk3-w32.nsi" on line 33 -- aborting creation process
rake aborted!
```

To replicate you have to install the NSIS 3.0. and change make/win7/tasks.rb:216

```
   #sh "\"c:\\Program Files (x86)\\NSIS\\Unicode\\makensis.exe\" #{WINFNAME}.nsi" 
   sh "\"c:\\Program Files (x86)\\NSIS\\makensis.exe\" #{WINFNAME}.nsi" 
```

**Comment by BackOrder** [comment]
NSIS Unicode is different from NSIS.

**Comment by ccoupe** [comment]
>NSIS Unicode is different from NSIS.

NSIS Unicode appears to be dead. NSIS 3.0b3 appears to be where folks are working on the code. Did they unify? It's not a place or project I track so I'd be the last to know.

**Comment by BackOrder** [comment]
NSIS Unicode is not dead but it's kind of project to follow behind the original. It is mostly a series of patches, additional scripts, etc. Using a non-Unicode friendly installer is calling for disaster. Maybe the original NSIS 3.0 does better at this than before but it will require changes in our installer script.

We may also consider moving towards Windows Installer technology, producing msi files.

**Comment by ccoupe** [comment]
Finding an open source license, free , cross platform msi appears to be a road block.

**Comment by BackOrder** [comment]
> Finding an open source license, free , cross platform msi appears to be a road block.

What do you mean? NSIS is Windows-centric. Windows Installer is not open source but it's made by Microsoft and well integrated. Not sure what you are having in mind exists...

**Comment by ccoupe** [comment]
I'd like something that doesn't require microsoft C compilers and all that goes with it. Shoes is tied to mingw compiler (as is RubyInstaller, most gems ...)

**Comment by BackOrder** [comment]
Windows Installer can be used at command line. Nowadays it has an XML file for the installation script. After searching on the web, it seems NSIS 3.0 supports Unicode based on NSIS Unicode code. So we may be able to stick wit h NSIS 3.0+ from now on but it still might need some fixing the installation script.

**Comment by ccoupe** [comment]
We'd have to write a new install script for msi builder of choice. So it's probably better to see what's wrong with the current script. And figures how to build it and run it on Linux. My first attempt on Linux  suggests it's beta although there are hint's it works, just no instructions so I'd have to understand it more that I do know.

**Comment by BackOrder** [comment]
This is not an issue anymore.

* Windows users shall use NSIS Unicode.
* Linux users can use NSIS Unicode for Linux to deliver Windows installers.
