### ISSUE TITLE
Shoes 3.3.1 should drop support of Gtk2

### ISSUE THREAD

**Issue by ccoupe** [Shoes3/shoes3#206]
This is developer clean up the code base issue. We won't be going back to gkt2 (might even be impossible) so we might as well get rid all that #ifdef code in gtk.c and related crud in the rakefiles  and the old remote  branches . Yeah, it's just housekeeping but we'd all feel better by doing it and fixes some compiler warnings in svg and video code.

**Comment by ccoupe** [comment]
Created a branch at github 'with_why'  so one could get the older gtk2/gtk3 mixed code,  because  I going to  update the master branch with deletions of the gtk2 code,  This would also be a opportune time  to get rid of the win32 native widget code which hasn't worked for years and to get rid of any curl crud in the source code. I don't expect anyone to work on the with_why branch. It's a placeholder. Yes, git tags were considered.

**Comment by BackOrder** [comment]
It seems too early to remove gtk2 code. It should be set for the next milestones. The rationale behind this is that there were major features added such as VLC support. Cleaning up may risk breaking the new features and also unnecessarily delay the release of Shoes where we can get feedback on new features before the next gig.

**Comment by ccoupe** [comment]
@BackOrder  - you have a branch for the old gtk2 code,' with_why'. It pains me emotionally to delete code so I saved it in that branch. Gtk2 is completely unless going forward and has been for months - video won't work with it. Svg won't work with it.  The rake files will be less cluttered and more approachable to future developers - A valid complaint of yours, if I remember.  Since we only have 2 developers contributing code, me and mostly @passenger94  it's a very good time to get rid old code that will never be used in the future.

**Comment by BackOrder** [comment]
@ccoupe I am all for its removal. Maybe my point wasn't clear : it is about a smooth transition and ensuring avoiding breaking code. Everything is so entangled that it wouldn't surprise me that removing unused code break things up. That's why I suggested to make it 3.3.2's priority.

**Comment by ccoupe** [comment]
Caution is certainly needed. Fortunately hunting down #ifdef that aren't needed is pretty simple. and it obvious when you make a mistake - compile files of a link fails.  Now, the env.rb files are where things get a little ugly but it's still just house keeping. Go slow, remove/change one thing at a time.

**Comment by ccoupe** [comment]
I'm going to close this one. It's release time.
