### ISSUE TITLE
 Windows 10 "application cannot run on my pc"

### ISSUE THREAD

**Issue by dredknight** [Shoes3/shoes3#229]
Hello once again!

 I am building [this](https://www.dropbox.com/s/851y6zjbxl60u6l/Open%20Skillwheel.exe?dl=0) app and it is currently tested on Windows 7,8,10 and 2003.

Unfortunately it was reported that on some configurations ( windows 8 and 10 ) the app cannot be run and the following error message appears - "application cannot run on my pc"
I cant replicate the issue but so far three different people reported it.

I dont understand why only some of the Win8 and 10s report that but not all of them.
Any idea what is causing this?

**Comment by ccoupe** [comment]
Please see issue #196 - You have to turn off certain security settings to get Shoes installed via a packaged app except no one knows which settings they are. I got it too work once but forgot what I did and really, Users shouldn't be asked to do that. That exe-shoes project will work for building  Win 10 apps.

**Comment by dredknight** [comment]
Thanks! Closing this one then. :)
