### ISSUE TITLE
remote_debugger.rb and require 'byebug/core'

### ISSUE THREAD

**Issue by passenger94** [Shoes3/shoes3#231]
in order to make the remote byebug debugger work i had to
`require 'byebug/core'` instead of just `require 'byebug'`
(linux, latest Shoes, byebug 8.2.1 & 8.2.2)

don't know if it's the best way to resolve the problem (no server, no connection)
found some clue over the internet, don't remember where ...

**Comment by ccoupe** [comment]
Which version of byebug?  Shoes is shipping with bybug-8.2.1 which  is a lot of numbers more than we first had.  I also note that I've not installed in my tight shoes which means I haven't used it.  This might be a feature that would benefit from a few automated tests for shoes integration. I think byebug itself does have a test suite.

**Comment by passenger94** [comment]
> linux, latest Shoes, byebug 8.2.1 & 8.2.2

:sunglasses:

**Comment by ccoupe** [comment]
Is `require 'byebug/core'` needed in lib/shoes/remote_debugger.rb or in the script being debugged . Or both?
