### ISSUE TITLE
Cannot present web links?

### ISSUE THREAD

**Issue by dredknight** [Shoes3/shoes3#234]
Hello everyone :),

Kind of trivial question but I couldnt find anything on the matter.
How I can do something like this:

[url="www.google.com"]Google link[/url]

... and when I click it to open a web page.

All I could find is a VISIT command but the guide explicitly says it is not for direct links...

**Comment by passenger94** [comment]
**visit** could work, theoretically, but only if there is a Shoes.app at the address ! (never tried, a bit scary knowing that code is going to be eval-ed ! must be sure you know at 100% that code is safe)
In your case, 
The cross platform way :
https://github.com/Shoes3/shoes3/blob/master/lib/shoes/help.rb#L302

**Comment by passenger94** [comment]
just checked visit a web address against shoes sample files here at github: it does work !
alone in a file
```ruby
Shoes.visit "https://raw.githubusercontent.com/Shoes3/shoes3/master/samples/simple-bounce.rb"
```

or launches a second app
```ruby
Shoes.app do
    button "visit" do
        Shoes.visit "https://raw.githubusercontent.com/Shoes3/shoes3/master/samples/simple-bounce.rb"
    end
end
```

**Comment by dredknight** [comment]
Thanks a lot :). This one is solved :).
