### ISSUE TITLE
color transparency

### ISSUE THREAD

**Issue by passenger94** [Shoes3/shoes3#241]
**shoes_dialog_color** returns only an opaque color (gtk and cocoa)
Is there a reason for such a limitation ?
(Easy to fix, if ok)

**Comment by ccoupe** [comment]
I'm not aware of any reason to hide the alpha channel but I don't see any way in the dialogs to set it (gtk/linux and osx). If so, there's nothing to fix.

**Comment by passenger94** [comment]
? well ... what about cocoa ? the missing part of the apple, maybe?
![alpha](https://cloud.githubusercontent.com/assets/10730930/14486422/01893d38-015d-11e6-9655-87b0e40ee8df.jpg)

**Comment by ccoupe** [comment]
I was expecting to see the numeric value for the channel displayed.  Easy fixes as easy to undo so give it a try.
