### ISSUE TITLE
equality operator on color is missing

### ISSUE THREAD

**Issue by passenger94** [Shoes3/shoes3#243]
While working on tests for Shoes::Color i  noticed 
`rgb(255,0,0) == rgb(0,0,255)` 
This assertion is true, at the moment, because == is implemented via the spaceship operator which compares two colors by adding each component of a color and compares the result for equality, which leads to the absurd assertion above

I have a fix which implements **==** and **eql?** besides the spaceship operator (with passing Tests).

But before submitting a PR, i would like to know, what you think about the spaceship operator behavior ? Is this desirable ? : `assert_equal(0, rgb(255,0,0) <=> rgb(0,0,255))`

EDIT :  related
**invert** method on color has no respect for the alpha channel (fix awaiting in PR)
given :  color = rgb(157,255,25,57)
`assert_equal rgb(98,0,230,57), color.invert` was failing  - color invert was rgb(98,0,230,255) -

**Comment by ccoupe** [comment]
255,0,0 is not equal to 0,0,255 IMO. Which one is larger and which is smaller is ... anyone's guess. Be aware somethings may be rgba and some may be argb.

**Comment by passenger94** [comment]
yes, i do agree, what is the meaning of a color being smaller or greater than another one ? Well maybe in some calculation context ... 
will left those untouched and fix the == and eql? part
