### ISSUE TITLE
finding ressources in the same directory as the packaged app, no matter where it is 

### ISSUE THREAD

**Issue by passenger94** [Shoes3/shoes3#247]
http://stackoverflow.com/questions/36816994/how-to-get-a-exe-packaged-ruby-shoes-app-to-reference-resources-outside-the-pac/36817440#36817440

Do you know how to handle this in a clean way ?

**Comment by ccoupe** [comment]
I answered `background "#{DIR}/bg.jpg" - although Dir.getwd is another way to find out where you are.

**Comment by passenger94** [comment]
I'm afraid, this is not what the OP is asking ...
He wants to have access to the directory where the actual exe file is , so he can use the resources in the same directory

**Comment by ccoupe** [comment]
I update the answer.  You may not have seen that. Dir.getwd is what I use to my ytm test app which is packaged 6 ways to Sunday.

**Comment by passenger94** [comment]
just tested (on linux) it gives me the tmp folder not where the "exe" is .... ?

**Comment by ccoupe** [comment]
I thought you said he wanted the dir where the exe is ;-).  A shy is always in /tmp. It's not permanent. (secondary packager fixes that at great cost to me and the user) %APPDATA%\somewhere for Windows. DIR and LIB_DIR are your friends.

**Comment by passenger94** [comment]
nope, DIR points to working directory (the tmp where package expand) and LIB_DIR to where shoes user "data" folder is
If exe (the packaged app) is in say ** /home/peculiar_folder** it will expand in tmp/some temporary_folder and that's where dir pwd getwd, __FILE__ are pointing, the OP wants to know where **peculiar_folder** is

**Comment by ccoupe** [comment]
In normal packaging . You only have **one** file. Either a rb or .shy. If you want multiple files in a 'package' ie, resources, you must create a Shy and use Dir.getwd. True for window, osx and linux.

**Comment by passenger94** [comment]
his particular use case is that he don't have the resources beforehand (when packaging) so he wants later to puts his packaged app where the resources are when he get a chance to have them (downloaded it seems)

**Comment by ccoupe** [comment]
There's always more to a simple bug report, eh? I'd create a folder in #{LIB_DIR}/myapp/  which is probably ENV['APPDATA']/LOCAL/myapp' and download and move the resources to there.  You do not want to download files into or move them into c:\Program Files (x86)\myapp - Win 10 will actively prevent it.

**Comment by passenger94** [comment]
> There's always more to a simple bug report, eh?

This one is a tricky one !!   

oh yes, better ! (didn't knew about that win10 thing...)
but ...it means distribute the packaged app with instructions about what to do, by hand, to find resources .... no ? so, no easy way to know where packaged is?

**Comment by ccoupe** [comment]
It is  virus behavior to download to protected directories without user permission.  Shoes can't download to /usr/bin on Linux either and Shoes has no way request permission or and way to ask the OS for permission, nor do I intend to may it easy to do that.  The exe-shoes, linux-shoe, osx-shoes projects can build installers that do get permission to install be even they will run into problems downloading into directories they shouldn't.  Look at what samples/good-cardflip.rb does to find 'paris.svg' in a  downloaded and installed Shoes. 

The script writer must decide where they want their resources  to be. There's a multitude of ways to do that, most on them not easy if they can't work with what Shoes provides.

**Comment by ccoupe** [comment]
>.... no ? so, no easy way to know where packaged is?

The secondary installer (Advanced Packaging checkbox) will ask the _end user_ where to install the shy permanently in user writable space  and  it sets up a deskop .lnk for it and then it can download into user writable space with paths determined by the end user) Or the OP can write their own secondary installer script if they don't like the default script (all Shoes has a copy of the default secondary script, should they care to look).  It's entirely possible to do what the OP wants **IF** they are willing to not inflict there choices on the end user and willing to work within OS security restrictions.  It doesn't need a manual or step by step instructions - unless that is an easier path that they choose.

**Comment by ccoupe** [comment]
Closing issue
