### ISSUE TITLE
colouring part of the text?

### ISSUE THREAD

**Issue by dredknight** [Shoes3/shoes3#250]
Heya everyone,

I wonder if there is a way to mark some of the text in different colour without typing multiple commands.
For example:
```Ruby
para "this is"
para  "THE BEST", colour: red
para "moment of my life"
```

Can I do the above example in one line like this?
```Ruby
 para "this is <red>THE BEST</red> moment of my life"
```

**Comment by passenger94** [comment]
Shoes.app do
    para "this is", span("THE BEST", stroke: red), "moment of my life\n"
    para span("this is", underline: 'double', undercolor: green), span("THE BEST", stroke: red), span("moment of my life", size: 10)
end

**Comment by dredknight** [comment]
Thanks!! That will do :), it will be nice if it could be seen in the guide!
