### ISSUE TITLE
mysql2 with mariadb in Windows

### ISSUE THREAD

**Issue by yebyen** [Shoes3/shoes3#252]
Hey, thanks for continuing the work on Shoes!

I have a need to build an app that talks to a database using the mysql2 gem.  My databases are actually a mix of MariaDB 10.0 and 10.1, so on my Linux machine I make sure I have the mariadb client libraries and dev headers from the MariaDB apt repositories, and when I just add 'mysql2' to my Gemfile, Shoes takes care of the rest.  Great!  Amazing, in fact.

Now I'm trying to deliver this app to a Windows user, and I expected to have headaches because mysql2 builds a native extension, but sure enough, I add 'mysql2' to the Gemfile and let Shoes figure it out, the gem builds and installs no problem.  But it seems to be using libmysqlclient to build against, and I never installed any of that.  How do I get Shoes to build mysql2 against the mariadb client libraries?

**Comment by yebyen** [comment]
I see that Cobbler is a relatively new thing, and read enough docs to find out about Jail-breaking gems... I was hoping to package this app up and deliver it as a portable exe, though, so jail break is out.  I haven't been able to figure out how to do this with Cobbler yet.  I grabbed the mariadb-c-connecter-2.2.3 installer for Windows which I'll probably need, but the best advice I've found on this vein is to point bundler at the right mysql-client-config tool.  Clearly cobbler is not bundler, and mariadb-c-connecter comes with header files, but no mysql-client-config or any other executable programs that I was able to find.

Installing the gem a second time after uninstalling seems to be hanging up somewhere, so I've uninstalled shoes, dumped ~/AppData/Local/Shoes, reinstalled, trying again now.

**Comment by yebyen** [comment]
Same result...

The specific error message:

```
Error in <unknown> line 0 | 2016-06-03 16:38:04 +0000
Malformed packet
C:/Users/Administrator.MM/AppData/Local/Shoes/+gem/gems/mysql2-0.4.4-x86-mingw32/lib/mysql2/client.rb:87:in `connect'
C:/Users/Administrator.MM/AppData/Local/Shoes/+gem/gems/mysql2-0.4.4-x86-mingw32/lib/mysql2/client.rb:87:in `initialize'
testapp.rb:10:in `new'
testapp.rb:10:in `<main>'
C:/Program Files (x86)/Shoes/lib/shoes.rb:500:in `eval'
C:/Program Files (x86)/Shoes/lib/shoes.rb:500:in `visit'
C:/Program Files (x86)/Shoes/lib/shoes/setup.rb:81:in `block (2 levels) in setup_app'
-e:1:in `call'
```

I am almost 100% sure this is a result of building mysql2 against the mysql2 libraries, but since I have no idea how Shoes does this (or where the dll even lives to try replacing it with a better one) I'm just stuck.

**Comment by ccoupe** [comment]
You need to build the dll's to match what the gem wants on Windows.   You'll need a Windows machine or VM with the correct RubyInstaller and Devkit that matches Shoes (ruby 2.2.x) The wiki might help. Use that to install the gem. If the gem needs other libraries or headers (mysql/...) it will fail of course. Once you have a gem installed correctly and know what all the dll's are. Then we can figure out how to distribute them with Shoes.

I advise ignoring bundler when working with Shoes. It only confuses things and probably won't do what you want.

**Comment by ccoupe** [comment]
The gem - **not Shoes**, decides what db to link against.

**Comment by yebyen** [comment]
Aha, (before I saw you posted back) I got to:

```
shoes -g install mysql2 -- --with-mysql-lib="C:\Program Files\MariaDB\MariaDB Connector C 64-bit\lib" --with-mysql-include="C:\Program Files\MariaDB\MariaDB Connector C 64-bit\include"
Exiting RubyGems with exit_code 0
```

and guessed that I'd have to be recompiling the gem to make it work.  Shoes seemed to take long enough to install the gem that I just assumed it was actually compiling stuff in the background, but this time it returned almost immediately, I guess installing the gem from the gem cache.

I also tried dropping in some replacements for libmysql.dll from various sources, none of those worked of course.  I'll try putting together a proper dev environment and getting a gem that links to the right connector libraries.

I think I got side-tracked because I found the "Old Instructions" before I got to this link:
https://github.com/Shoes3/shoes3/wiki/Building-Shoes-on-Windows

So, ruby 2.2 then... got it.  I'll come back and post an update when I made some more progress.

**Comment by ccoupe** [comment]
If your working from the windows command line, use cshoes.exe -- you'll get the full stdout/stderr progress messages. `$ cshoes.exe -g install mysql2 -- ....`

**Comment by yebyen** [comment]
`cshoes -g` doesn't seem to give me any extra output, but then exit_code 0 is usually a success state, and the gem seems to be installed after that...

From what I'm reading I need 32-bit libraries also, not 64-bit ones

**Comment by yebyen** [comment]
There seems to be a dead link, http://shoes.mvmanila.com/public/shoesdeps/mingw/Shoesdeps.zip -- in the guide linked above.  I am assuming you need all of these things from the parent folder, which does exist, and have a readme that also refers to the gone file...

**Comment by yebyen** [comment]
Well, it turns out the mariadb-c-connector package is completely the wrong thing to download, and that's my next problem.

I got a full copy of mariadb 10.1.14 from the distro site (this version matches my db server), the 32-bit version for Windows, installed the dev kit properly according to the instructions of RubyInstaller and sought out instructions for `mysql2` gem to ensure that I didn't get a binary copy (`--platform=ruby`), put the mariadb into c:\mariadb, built using this command, and I was able to build a working gem:

```
$ gem install mysql2 --platform=ruby -- --with-mysql-lib="/c/mariadb/lib" --with-mysql-include="/c/mariadb/include"
```

That gem works great in my ruby2.2.4 from RubyInstaller, I use it without Shoes and it can contact my database no problem, but it looks like the `mysql2-0.4.4.gem` it generated does not vendor the DLL and I can't simply pick it out of the cache and `shoes -g install` it.  Trying to install it like that results in, Shoes tries to build it again, and that fails predictably because Shoes is not set up to build gems...

**Comment by yebyen** [comment]
Looks like now I need the mysql2 source tree and `gem-compiler` to make a x86-mingw32 gem...

**Comment by yebyen** [comment]
Winner!  Well, almost... The magical incantation turned out to be

```
$ git clone https://github.com/brianmario/mysql2.git
$ git checkout 0.4.4
$ gem build mysql2.gemspec
$ gem compile mysql2-0.4.4.gem -- --with-mysql-lib="/c/mariadb/lib" --with-mysql-include="/c/mariadb/include"
```

The result is a `mysql2-0.4.4-x86-mingw32.gem` that you can `shoes -g install`.

The only problem is, it didn't actually vendor libmysql.dll -- it 

Opening up `AppData\Local\Shoes\+gem\gems` to find the installed gem, adding a `vendor` directory, and copying the dll from its build-time home into that vendor dir, resulted in me with happy feet, and a Shoes app running in Windows that talks to my database.  So, any idea how to tell gem-compiler to vendor that DLL so I can mark this closed?

Sorry, this is way off-topic for Shoes dev issue tracker, but I couldn't use Shoes for my purpose without it, so maybe this is worth a Wiki post?  I'd be glad to write it up...

**Comment by ccoupe** [comment]
Only if you want to host gems for downloads or update a remote gem.  Yes, you do need the 32 bit devkit because Shoes is 32 bit (I cross compile on Linux but that's more difficult to set up). You don't need the full deps (yet, maybe never?) unless you want to build Shoes from source.

Internally,  Shoes just copies the needed files when working with gems. So you can copy the correct files from wherever RubyInstaller puts them into \Appdata\Local\Shoes\+gems without build a gem There are scripts to do that https://github.com/Shoes3/shoes3/tree/master/gemutils and there's another script not at github that might be useful.  It now depends on how much control you want over the install experience  (wiki describes this in it's confusing way)

**Comment by yebyen** [comment]
I tried to do that, but I wound up watching Shoes try to install the gem anyway when Shoes.setup was invoked...

What I wound up doing was to make a new commit to my local mysql2 tree, with a vendor dir and spec update to include it in the gem, recompiling that gem, and installing it.

I'm not sure what this will look like when it's packaged up, but for now that gives me a gem file that I can at least include with my app so the user can `shoes -g install` it, after he's gone out and downloaded shoes.  He won't need to download any dev kit, and he's meant to be the one writing this app anyway, so, target audience is satisfied, at least until we try to package this up for distribution.  The main point here was to prove that it would still work on Windows, not to finally package it up and ship it off.

I'm happy!  Closed if you agree?

**Comment by ccoupe** [comment]
Crossed messages!  if you only wanted your app on that Windows machine, then great! If you want to package your app for other Windows machines then the job is half done.  If you decide to write a wiki article, let me know

**Comment by yebyen** [comment]
OK, I will revisit this and most likely put together a wiki article, I'm not sure if there's any need for an official mysql2-mariadb gem source with Windows support, but I would definitely call this solved if it was possible to require 'mysql2-mariadb' on Windows and get a working app without going through all of this.

I agree, anything less than that would be pretty much half done.

**Comment by ccoupe** [comment]
I've found gem authors to be appreciative of a comment, bug report or a patch/workaround so why not contact the mysql2 gem author with a 'here is what to do to build for mariadb on windows'. Windows gems can include precompiled dlls so it might be useful if msysql2 did that using the mingw compiler.. Then Shoes.setup would have worked (assuming all its required gems also had binary packages.) There are  version- ing issues with those precompiled gems so I can understand why not all authors build them.

**Comment by ccoupe** [comment]
For your first case, i should have sent you to https://github.com/Shoes3/shoes3/wiki/Gempacks which will allow you to extract Gems from rubyinstaller or shoes and then email the 'gem pack' to your Shoes compatriot and they can load that into Shoes with Cobbler->load gempack

**Comment by yebyen** [comment]
@Brianmario does actually provide (or someone does) the binary gem for
msys32 but, mariadb is supposed to be binary compatible, although not
usable or completely interchangeable for MySQL lib.  So it's a sticky
issue.  Only MariaDB users need to compile mysql2 against MariaDB libs.
This is probably a very uncommon edge case that 300 or more people have
either spent a whole day figuring out, or given up on.

I guess the first step would be putting a better error message in place
than malformed packet! When I tried to drop the different version of the
library in, I got an error message that told me it was a mismatched version
versus the version that the gem was compiled against.  I dont know if it
could be possible to get a garden path like that when you simply try to
connect to MariaDB and you don't have MariaDB libs; I only knew what was
going on here to begin with because I've had this issue before!

**Comment by ccoupe** [comment]
Shoes is an edge case magnet. BTW, thanks for reporting the bug.

**Comment by ccoupe** [comment]
Closing. Re-open if needed

**Comment by kingdonb** [comment]
Thanks... I should write the wiki article, may have a recruit

**Comment by ccoupe** [comment]
Recruits are welcome.

**Comment by ccoupe** [comment]
@kingdonb  Would you like an invitation to join the Shoes3 team?

**Comment by yebyen** [comment]
Sure! Sign me up, is that just GitHub org? Or are there meetings, or slack
or what else

**Comment by ccoupe** [comment]
It's just github traffic, new issues, comments, commits from Shoes3 and related side projects.

**Comment by yebyen** [comment]
Thanks! I'm glad to subscribe to all those things.
