### ISSUE TITLE
OSX: ask_color_dialog

### ISSUE THREAD

**Issue by ccoupe** [Shoes3/shoes3#255]
Need to write a new osx dialog that can return RGB+A like Gtk3 does. This is a tracking issues so I don't forget to do it.

**Comment by ccoupe** [comment]
The recent commit works OK from a Shoes perspective - returns a reasonable answer, doesn't crash anything.  Fun fact: I found the solution in a Python/Tk/Tcl post on the interwebs.  I did speak Tcl internal API some decades ago. Still need to clean the code and test each clean up so I can't close the issue yet.

**Comment by ccoupe** [comment]
Interesting: when ask_color() returns (samples/simple-dialog.rb) and the alpha is 100% (0xFF) Shoes only shoes the RGB values. If alpha is less than 100% then the display is RGBA where the A is a %. That is not Gtk or Cocoa. - probably Shoes::Color.to_str().  I don't see a big problem but it might confuse someone expecting 4 values.

**Comment by passenger94** [comment]
:+1:
