### ISSUE TITLE
Click do |button| does not work as documented

### ISSUE THREAD

**Issue by dredknight** [Shoes3/shoes3#258]
Hello guys,

 This week is kind of glitchy week. I bumped into something that seems really weird.
Basically i have a For cycle that builds a 4x3 table. First 4 slots are pictures which can be hovered/clicked. Image functions are defined in **set_primary_image**.

The problem is that the CLICK  function cannot get the button that is used to click.
The click function itself is working. I have it implemented on other part of the code as well and I am able to capture the button. The only difference between the other part and this one is that here the Click is defined in a method.

Why is there such difference?
**p.s. the debug ("button is #{button}") returns Shoes::Types::Images**

```
def set_primary_image img, file, i
	img.hover do
		text=File.read("text/pskills/#{file}.txt")
		open_popup 200, 70, "", text
	end
	img.leave do
		close_popup
	end
########## THIS IS NOT WORKING##########	
	img.click do |button|    
		close_popup
		debug ("button is #{button}")
		if button == 0 then	
			@ch_primary[i]+=1
		else
			@ch_primary[i]-=1
		end
		set_primary
		debug ("primary is #{@ch_primary}")
	end
end
#####################################
for i in 0..11																									
	flow height: 45, width: 45 do
		border("rgb(105, 105, 105)", strokewidth: 1)
		case i 
			when 0..3 then	image "pics/pskills/#{table_image[i]}.png", left: 1, top: 1
			set_primary_image contents[1], table_image[i], i
			else @table_stats[i-4] = para "0" , align: "center", margin_top: 0.32
		end			
	end
end
```

**Comment by ccoupe** [comment]
Quick guess: `button`  is essentially  image.click.self so the debug() is correct. Name it foo instead and will still an image.

**Comment by dredknight** [comment]
You got that right. img.click - img is variable that contains image (image "asdaasd.png").

Here is another piece of code that uses the same function but here it works.
The difference is that contents[7] is a flow slot. Not an image like the previous example.

```
contents[7].click do |button|             ##########Hero leveling up and gaining of primary stats based on chance
				close_popup
				if button == 1 && @ch_level<50 then
					@ch_level+=1	
					i=rand(0..100)+1
					case i
						when 1..@ch_primary[4] then @ch_primary[0]+=1
						when @ch_primary[4]+1..@ch_primary[4]+@ch_primary[5] then @ch_primary[1]+=1
						when @ch_primary[4]+@ch_primary[5]+1..@ch_primary[4]+@ch_primary[5]+@ch_primary[6] then @ch_primary[2]+=1
						when @ch_primary[4]+@ch_primary[5]+@ch_primary[6]+1..100 then @ch_primary[3]+=1
					end
				else
					@ch_level=1
					@ch_primary=read_skills "text/classes/#{@ch_class}/primary.txt", 1
				end
				set_primary
			end
```

**Comment by passenger94** [comment]
hi,
That's expected, an image like other clickable **Elements** (button, check,..) gives self to the block of a click event, **Slots** on the other hand, like you experienced, gives : buttton, left, top.

That's maybe arguable ... for consistency with other elements, it's good, but an image might have "active" zones and react differently, so left and top would play a role there, also like what seems your use case, react differently depending on which button was clicked ...

You can probably use the app's **mouse** method to get button, left and top
not tested :
```ruby
Shoes.app do
  button, left, top = self.mouse
end
```

**Comment by dredknight** [comment]
Alright :). Now it is more clear! That self thing always brings surprises.

**Comment by ccoupe** [comment]
Knowing self is why nobody knows shoes.
