### ISSUE TITLE
adding more than 1 stuff to same  event?

### ISSUE THREAD

**Issue by dredknight** [Shoes3/shoes3#259]
Hello everyone,

I was wondering if it is possible to make more than one version of event for object that works simultaneously. For example I want to add a popup window and a back shade on the box when hovered but I dont want them in one method because not every hovered element has background or popup text while sometimes it has both.

```Ruby
Shoes.app do

def set_popup box
     box.hover { open_popup }
     box.leave { close_popup } 
end

def set_shade box
     box.hover {  box.contents[0].show }
     box.leave { box.contents[0].hide  }
end

box = flow height: 30; width: 30; do 
      image "shoes.png" do end.hide
end
set_popup box 
set_shade box 

```

**Comment by passenger94** [comment]
yes sure, you do whatever suits your use case inside the event's block, for example ,check if the box has a background, in which case you change it, after or before raise a popup, if needed or if valid text is avalaible, etc.. 
hover event sends self to the block `object.hover {|self| ....... ]` which is the box in your case, you can check, test, that object, i.e. `if self.contents[0].class == Shoes::Background`

or did i misunderstood your question ?

**Comment by dredknight** [comment]
I got you this will work!
Actually my question was more philosophical - Can you define one event at two places at such way that things add-up. 

On the upper example hover is defined twice for the same object and in my world when the mouse go over the object both things should happen. Unfortunately shoes does not think so :D.

**Comment by passenger94** [comment]
Philosophically i don't see why you couldn't define events at several places at the same time, leisurely questioning the absoluteness of the necessity to do so, naturally, 
but Shoes or even Ruby are exploring new ways of thinking and in their current state of investigations are apparently positive on the fact that once you defined "something", if later you redefine it it means you gave another meaning to that "something". It looks like you guys both are on disagreement about the concrete implications of the adds-up concept !

But i'm only a disciple ...

**Comment by dredknight** [comment]
Thank you for the explanation once again!
You are absolutely correct. I totally didnt make the connection that events just like variables are object that can also be redefined.

Now it is all clear master :)!
