### ISSUE TITLE
require 'observer' opens two windows

### ISSUE THREAD

**Issue by bartheg** [Shoes3/shoes3#262]
For example:
```
lol = require 'observer'

Shoes.app {
  para lol
}
```
opens two shoes apps. The first has 'false' text and the second has 'true'.

**Comment by ccoupe** [comment]
Is this on OSX? If so, you might have two app windows open stacked on top of each other.  I believe it's fixed on Shoes 3.3.2 which isn't released yet. The fix may be in [this beta](http://walkabout.mvmanila.com/public/shoes/shoes-3.3.2-osx-10.9.tgz)

**Comment by bartheg** [comment]
No, sorry, I should give more details. It is Ubuntu 15.10. Shoes version 3.3.1 r2509 x86_64-linux 2.2.4. On the older version 3.3.0 I had the same issue.

**Comment by ccoupe** [comment]
Odd. I ran your example on ubuntu 14.04 (very new shoes) and 15.10  - shoes r2470 and every thing looked fine.. How are you launching Shoes?

**Comment by bartheg** [comment]
I have tried those methods:

1. `~/.shoes/walkabout/shoes` and then "Open an App"
2. `~/.shoes/walkabout/shoes observer.rb`
3. "Shoes Walkabout" launcher in Dash (or whatever they call that) and then "Open an App"

**Comment by bartheg** [comment]
Oh, wait, something funny. When I changed the filename it looks fixed.

**Comment by ccoupe** [comment]
That's same methods I tested too. I'm more than a little stumped. There is a Shoes.3,3.2 beta for x86_64 linux at http://walkabout.mvmanila.com/public/shoes. If you install that it will overwrite your current install. (except for any gems you've installed) - All I can think of is you got a faulty version of Shoes built when I was working on the OSX problem.  You could try launching
 `~/.shoes/walkabout/shoes -f observer.rb`  -f should be ignored by Shoes but if it works for you then then would suggest you need a newer Shoes setup.

**Comment by ccoupe** [comment]
Ohh of course. The scripts location is added to the ruby load path so the require is loading itself, then the gem. Sort of like that.

**Comment by ccoupe** [comment]
After some thought, I believe this how Ruby behaves and Shoes is not the problem. I'm going to close the issue.
