### ISSUE TITLE
URLs behave strange?

### ISSUE THREAD

**Issue by dredknight** [Shoes3/shoes3#268]
Heya all of you :).

I try to modularize my app by using the URL function. Unfortunately there are some underwater stones that I hit. How do I make the URL links aware of my methods? Where should I place the methods?
I tried several things nothing worked...

I tried putting them out of the class, didnt happen.
In the example below I place the method inside the URL but doesnt work either.
What should be done?

```Ruby
class PopUp < Shoes::Widget
	
		def initialize ()
			motion { |x, y| @move_left = x; @move_top = y }
			start { @menu = stack height: 0 do end.hide }
		end
		
		def resize ( length, length2=0, h_length=0 )
			wide, high = length*8, 1
			while (wide*high/length < 9*17 or wide/high > 6) do
				(wide/high).between?(0,7) ? nil : ( wide-=wide/2 )
				high+=18
				wide < 260 ? wide = 260 : nil
			end
			(h_length+3)*10>wide ? wide = ( (h_length+3)*10 ) : nil
			h_length > 0 ? high+=60 : nil
			high+=8*20*length2/wide
			return wide, high
		end
		
		def present ( options={} )
		text, text2, header, offset, wide, high = options[:text], options[:text2], options[:header], options[:offset], options[:wide], options[:high]
			flow margin_left: offset, width: wide, height: high do
				header == "" ? nil : ( para ("#{header}"), size: 17, stroke: white, font: "Bell MT", align: "center", justify: false )
				para ("#{text}"), size: 9, stroke: white, font: "Courier New", align: "center", justify: true
				text2 == "" ? nil : ( para ("#{text2}"), size: 9, stroke: rgb(50,50,50), font: "Courier New", align: "center", justify: true )
			end
		end
		
		def open ( options={} )
			offset, high, wide, text, text2, header, back1, back2 = 10, options[:height], options[:width], options[:text] || "ERROR: Missing mandatory options \"width:\", \"height:\" or \"text:\"\nAvailable options:\ntext: the text presented in the popup window\nwidth: the width of the popup\nheight: the height of the popup\nfont: the font of the text\nstroke: the stroke of the text\nsize: the size of the text\nborder: the colour of the border of the tooltip\nbackground: the colour of the tooltip box\nExample:   slot.hover { @popup.open text: \"Popup comming through\", width: 200, height: 100, border: rgb(0,20,5,0.5), background: rgb(0,244,99,0.5) , font: \"Vivaldi\" , size: 10, stroke: white }", options[:text2] || "", options[:header] || "", options[:border] || rgb(120,42,5,0.5), options[:background] || rgb(180,150,110,0.7) 
			( wide.nil? || high.nil? ) ? (wide, high = resize text.length, text2.length, header.length ) : nil
			@menu.style width: offset + wide, height: offset + high
			menu_left, menu_top = @move_left, @move_top;
			@move_left + @menu.width >= app.width + offset ? menu_left = @move_left - @menu.width : nil
			@move_top + @menu.height >= app.height + offset ? menu_top = @move_top - 2*@menu.height/3 : nil
			@menu.move(menu_left, menu_top)
			@menu.clear do
				background back1, curve: 15
				background back2, curve: 15, width: @menu.width-4, height: @menu.height - 4, left: 2, top: 2
				present text: text, text2: text2, header: header, offset: offset/2, wide: wide, high: high
			end
			start { @menu.show }
		end
		
		def close
			@menu.hide
		end
	end

class MyApp < Shoes
	url "/", :setupscreen
	url "/entry11", :entryscreen
	url "/help", :helpscreen
  
  def setupscreen
  
	def set	(img, options={} )
		img.hover { @hovers.open  text: options[:text], header: options[:header] , text2: options[:text2], width: options[:width], height: options[:height] }	
		img.leave { @hovers.close }
	end
	
	@hovers = pop_up()
    stack do 
      image "pic.png", left: 50, top: 50
	  set contents[0], text: "Welcome to My Demo app"
    end
  end
  
  def entryscreen
    stack do 
    end
  end
  
  def helpscreen
     stack do 
     end
  end
end
Shoes.app :width => 400, :height => 300, :margin => 5
```

**Comment by ccoupe** [comment]
Things do act differently with the url/visit style and it wouldn't surprise me that there are bugs. 
This line `set contents[0], text: "Welcome to My Demo app"` refers to contents[0] and the code above doesn't seem to have any 'contents` defined.

**Comment by passenger94** [comment]
Hi all, 
yep !
if contents is refering to the stack in which this method (contents of stack, i presume) is called then it can't work as the stack don't know yet what is exactly his contents.
you have to call set (...) once stack is finished ... here comes again our start friend ...
But beware like cecil said url/visit class style App works a bit differently
other than that your code looks correct to me ....

**Comment by dredknight** [comment]
@passenger94, this is wierd because the stack + contents code work when executed in a normal Shoes.app manner. Actually what I currently do is just transfer bits of my app from the Shoes.app to the first URL page.

@ccoupe I found out there is some issue with declaring Constants.
Use the above code and place a constant in the first page like
```Ruby
FACTIONS = [5,6, 7, 8 ]
```
It brings dynamic constant assignment error.

Also just to let you know that I will be happy to explore this part of Shoes and see where we can come up to and what is there for debug and may be.... write a guide if things happen.

**Comment by passenger94** [comment]
ok got a chance to look closer... several things,
first, class style apps are a bit different because they are not instance evaled but the class block is called (like a procedure) !!! ( the whole thing begins here : https://github.com/Shoes3/shoes3/blob/master/shoes/app.c#L396) this has an impact on what self is referring to, mainly it's not any more the app instance like in regular app
another consequence is that you can't access instance variables everywhere anymore, you must use class variables (@@hovers, not @hovers)

you're right contents[0] works here, but don't rely on that, in a more complicated setting it'll probably fail, - well, if you are sure that image is always going to be first element, it's ok of course -   
this works (with the start event it works also)
```ruby
stack width: 300, height: 300 do 
      im = image "pic.png", left: 50, top: 50
      set im, text: "Welcome to My Demo app"
end
```
lastly the real issue is here :` start { @menu.show }`
just go with @menu.show and it works
(still unclear though as to why exactly)

[working app ](https://gist.github.com/passenger94/925732454b03d9b386b52566fdd77247)

**Comment by dredknight** [comment]
Dang that **self** thing... works totally the way you said it.
That *me* thing is super nice! Didnt know you can change self that way. Thanks!

Question about this code.
```Ruby
stack start: proc {  |me| set me.contents[0], text: "Welcome to My Demo app"  }
```
 I didnt know you can do the  { } on flows and stacks. Here are 2 ways to use it but the second one does not work. Why? I try some brackets, comas and semi columns here and there but with no success.

```Ruby
Shoes.app do
        flow  {  image "#{DIR}/static/app-icon.png", left: 49, top: 49}
end
```
```Ruby
Shoes.app do  
        flow left: 65, top: 75 , width: 50, height: 50 {  image "#{DIR}/static/app-icon.png", left: 49, top: 49}
end
```
Regarding the Start thing I will investigate later.

**Comment by passenger94** [comment]
it's just some ruby stuff
"me" is a block variable, you are free to name it the way you want, most of the times it's named self because the oject that variable refers to, is the object on which the block is called (i choose "me" to stay close to "self", another one could be "slot" in this case, because we are dealing with a stack (a slot in Shoes parlance)

Sorry, don't be confused :   
`start: proc {  |me| set me.contents[0], text: "Welcome to My Demo app"  }`   
is a style hash, like width: 400, etc...
not alone it is for example
```ruby
Shoes.app do
    flow left: 15, start: proc {  |me| set me.contents[0], text: "Welcome to My Demo app"  },width: 364 do
    #.....
    end
end
```
it works for all events, because under the hood, in C code, Shoes saves the block in an attribute exposed to Ruby code (attribute **start:** proc {...} for a start method for example), so **it looks like** there is a start style, maybe just accidental coincidence ??
You'll find easily, examples with the click event, that one is documented.

**Comment by dredknight** [comment]
Thanks! I will further optimize the code later :).

Some good news to announce! I managed to transfer the App into a URL page.
Just made a built, check it out [here]. :)(https://www.dropbox.com/s/jl4xoykkv416m6i/Open%20Skillwheel_v0.75.exe?dl=0)
There is no need to create a dropbox account, just click on the "No, thanks. Continue to view →" button below.

Still not sure why the start { @menu.show } is not working. I found a workaround though.
start was replaced with timer(0.01) { @menu.show } .  This way it works.

The full code can be found [here].(https://gist.github.com/dredknight/1346614cb8eae395b36d35bbe9c284b5).
Rough distribution of the code is like this:
```Ruby
class Tooltip   ########this is thetool tip class
...........
end

class MyApp   ########this is the APP
    #rows 92-95 define pages
    # rows 96-295 define methods
    #below 296 define each page insides. Currently only home page is done.
end

Shoes.app()

**Comment by ccoupe** [comment]
I was reviewing some notes (not bug reports, yet) and I see that you can't run profiling on a  app that uses the url/visit style - because that is the style that profile uses itself and navigating through the app/window maze is difficult to understand and difficult to generalize.

**Comment by dredknight** [comment]
@ccoupe thanks for the warning . I guess I will keep a separate script for each URL just to test on profiler.

**Comment by dredknight** [comment]
I did a few takes and this is as far as I could go. I can present the home pages but **visits** do not work.
```Ruby
Shoes.app :width => 400, :height => 300, :margin => 5 do
background yellow

class Myapp < Shoes::Widget
	url "/", :setupscreen
	url "/entry", :entryscreen
	url "/help", :helpscreen
  
  def setupscreen
    stack do 
      para "Welcome to My Demo app"
      flow do
        button "entry" do visit '/entry' end
        button "help" do visit '/help' end
      end
    end
  end
  
  def entryscreen
    stack do 
      para "Entry Screen - whats your secret?"
      @the_secret = edit_line text: "Secret"
      flow do
        button "home" do visit '/' end
        button "help" do visit '/help' end
      end
    end
  end
  
  def helpscreen
     stack do 
      para "This page describes MyApp, a very demo for structuring a Shoes application "
      flow do
        button "entry" do visit '/entry' end
        button "home" do visit '/' end
      end
    end end
end


	take = myapp()
	stack width: 400, height: 200 do
		background green
		take.setupscreen
	end
end
```

**Comment by dredknight** [comment]
Just to report a few things.
I found URL to be quite worthless for anything but tiny/experimental code. Some of the functions have to be completely rewritten to fit the URL behavior and this is the good case...

The good news is that there is a workaround. Here is what one can do if you want page-like behavior.

1. Draw a slot and assign it to a variable.
2. Define your page in a method
3. Define your second page in another method.

Example code:
```Ruby
Shoes.app do

     def main_page slot
             slot.clear do
                     background "example.png"
                     button do 
                           second_page @primary_slot
                     end
             end
     end

    def second_page slot
             slot.clear do
                     background "another_pic.png"
                      button do 
                           main_page @primary_slot
                     end
             end
     end

##### main starts here ##########
     @primary_slot = flow;
      main_page @primary_slot
end
```
Not sure how URL is working exactly but the worst thing here is that pages are drawn from scratch every time you call them.

Another workaround to reduce the load if you have some overlapping elements (lets say the background is common for all pages) is to draw 2 equally big slots .

```Ruby
Shoes.app do
    flow width: 500, height 500 do
        background "image.png"
        ####define here all elements that are constant throughout the pages ####
        @primary_slot = flow width: 500, height 500;
    end
    main_page @primary_slot
end
```
