### ISSUE TITLE
Animate from time to time?

### ISSUE THREAD

**Issue by dredknight** [Shoes3/shoes3#272]
Hey everyone,

Recently I started going through what shoes offers as animation.
I would like to start with something simple but alas it is not in defaults.
I wonder how every 10 seconds, 24 frames to be executed and then stop until the next 10 second period come. 
Here is an example code that does not work.
```Ruby
every(10) do
		animate(24) do
			@box.displace(0, (Math.sin(i) * 6).to_i)
		end
end
```

**Comment by ccoupe** [comment]
Last time I looked, you can't animate in an every or vice versa. Two different timers that don't know about the other.  Asking for 24 frames and seeing 24 won't happen every where. Not dependable and probably not fixable.

**Comment by passenger94** [comment]
one way is to check the frame in an animate :
```ruby
Shoes.app do
    @started = false
    
    animate(24) do |frame|
        if frame % (24*10) == 0 # every 10s
            @started = !@started
        end
        puts "frame : #{frame}" if @started
    end
end
```

**Comment by dredknight** [comment]
Thank you once again @ccoupe and @passenger94.
You gear me up with a lot of inspiration :).
