### ISSUE TITLE
Styles will not allow to position a window

### ISSUE THREAD

**Issue by BackOrder** [Shoes3/shoes3#28]
Shoes App, Window and Dialog **cannot be positioned** using styles such as **:left** and **:top** as demonstrated in the following code snippet.

``` ruby
Shoes.app(:title => "Window Positioning", :left => 0, :top => 0) {}
```

**Comment by ccoupe** [comment]
It hope it doesn't work in Linux too.  I don't consider this a bug.  Developers have a habit of too large windows (as you've seen)  and it they use abs position its way too easy the get a window that can't be closed or resized or dragged.  It would be nice if Shoes would offset it's own windows by a title bar height but I suspect that's not as easy it sounds.

**Comment by BackOrder** [comment]
You have words of wisdom. There are many things developers should not do but shall we decide for them? In any case, there are many styles not supported in Shoes App but yet not clearly expressed in the Shoes Manual. Could be low priority?

Here is a scenario where positioning does make sense:

A user uses an application written in Shoes and personalize it to his or her tastes, including resizing and moving the window and then save it as preferences. The applications can remember the preferences next time it is started and reposition/resize accordingly.

**Comment by ccoupe** [comment]
I don't know about my wisdom but Linux windows managers (and there are many of them) control windows positioning, not the app. Fullscreen is only a hint or polite request to the windows manager. Shoes has no knowledge of multiple monitors for example or which one it's displaying on. You'd want to save that info in your use case.  If Gtk2 (not 3) Linux and Windows can provide that level of information and you can get it from OSX  and can be abstracted cross platform then you could build something in Shoes that does this.

**Comment by BackOrder** [comment]
Another scenario:

An application requires a toolbar in similar fashion as in Photoshop or Gimp. Gimp used to have multiple floating windows. Positioning is absolutely necessary in such applications.

![image](https://cloud.githubusercontent.com/assets/8844578/5772067/0f0bdcee-9d19-11e4-9f69-faf59ebf0cda.png)
