### ISSUE TITLE
Allow  title: for ask open/save 

### ISSUE THREAD

**Issue by ccoupe** [Shoes3/shoes3#282]
ref #280

**Comment by ccoupe** [comment]
The parsing on :title needs to be moved into the callesr(s) of shoes_dialot_chooser.

**Comment by passenger94** [comment]
ah why, a cocoa thing ?

**Comment by ccoupe** [comment]
Yes. There are four Shoes methods, each with their own "title" string (API).  gtk sends all four to dialog_choser and osx doesn't because every 4 of the OSX critters is unique. Way back in the Shoes 3.1 day they were similar but it used  deprecated osx  api's from 5 or more years back. Carbon api's back then so 10 years old - well past the _use by_ date from Apple. It used to be the "open file" string was an app.c compiled in string. 

Four widgets (or dialogs) No sharing. I did consider subclassing in Obj-c like to be like  the gtk dialog chooser - much more code for no real benefit.

**Comment by passenger94** [comment]
ok, thanks for clarification ! :-)

**Comment by ccoupe** [comment]
It's more interesting than I said above. cocoa.m  used to vector all  4 calls to shoes_dialog_chooser, just like gtk but Apple deprecations broke that. Also, on OSX, ask_save_folder() is an unpleasant user experience (gtk is not much better).  But wait, all four shoes_dialog_open/save do a half ass parse of `|h` and then send args.a[0] on to the chooser (gtk) . It offends **my** sense of separation to see that. It looked like a hack back then and still does.  I understand  it's one of those 'who cares?' edge cases so purity is not a big issue but... all the dialogs just seem so unclean.

**Comment by ccoupe** [comment]
Actually, there is  support in Shoes Gtk 
```ruby
ask_open_file title: "Select and foobar file"
```
We're just missing the osx support - and it's doable and since I'm working on #303, now is the time.

**Comment by BackOrder** [comment]
Seems this is completed. Reopen if needed.
