### ISSUE TITLE
Error on start shoes. line 22

### ISSUE THREAD

**Issue by fffuture** [Shoes3/shoes3#286]
Hello. I was tried to install shoes with bash script from this [source](https://shoes.mvmanila.com/public/shoes/shoes-3.3.1-gtk3-i686.install). After installation, I logout and login again. Try to run Shoes Walkabout, but nothing happens. When I try to run from terminal I have this error: 

```
b77c7000-b77c9000 rw-p 00000000 00:00 0 
b77c9000-b77cb000 r--p 00000000 00:00 0          [vvar]
b77cb000-b77cd000 r-xp 00000000 00:00 0          [vdso]
b77cd000-b77ed000 r-xp 00000000 08:01 4195448    /lib/i386-linux-gnu/ld-2.19.so
b77ed000-b77ee000 r--p 0001f000 08:01 4195448    /lib/i386-linux-gnu/ld-2.19.so
b77ee000-b77ef000 rw-p 00020000 08:01 4195448    /lib/i386-linux-gnu/ld-2.19.so
bf09c000-bf89b000 rw-p 00000000 00:00 0          [stack]


[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html

shoes: line 22:  4491 Aborted                 (core dumped) LD_LIBRARY_PATH=$APPPATH $APPPATH/shoes-bin "$@"
```

What is problem?

**Comment by fffuture** [comment]
I will try to reinstall Ruby

**Comment by fffuture** [comment]
`sudo apt-get purge ruby` was help for me.. It not remove ruby but Shoes work properly after this actions.

**Comment by ccoupe** [comment]
Shoes includes it own Ruby in ~/.shoes  and completely ignores the installed Ruby. You should have menu items to install/de-install shoes. the command line launch is `~/.shoes/federales/shoes`

**Comment by ccoupe** [comment]
Closing this for lack of feedback.
