### ISSUE TITLE
Have anyone seen Cecil?

### ISSUE THREAD

**Issue by dredknight** [Shoes3/shoes3#291]
Kind of feel empty here lately. Does anyone know if she is alright?

**Comment by ccoupe** [comment]
He doing fine. We had an election in the USA and I took a few days of to watch it.

**Comment by ccoupe** [comment]
Also been super busy writing code which you would see unless your join the team. An invitation has been sent.

**Comment by dredknight** [comment]
Good. I have been following the election things there and they are really messy :D.

Thanks for the invitation!  I will look around.
Closing this one :)
