### ISSUE TITLE
Can shoes be used to create a web page?

### ISSUE THREAD

**Issue by dredknight** [Shoes3/shoes3#295]
Hello everyone, 
I wonder if Shoes can be used as a web page framework alongside apache?
Any idea where to begin?

**Comment by BackOrder** [comment]
Do you mean like a Java applet, flash player, etc?

**Comment by dredknight** [comment]
Well I am not quite a lot into web development so I will put it this way -  what I want is make a simple program, upload it on a linux server and access it via browser.

**Comment by BackOrder** [comment]
You maybe be able to run a headless Shoes using [CGI](https://httpd.apache.org/docs/2.4/en/howto/cgi.html) through Apache. This would mean you could run Shoes without UI. Most people would just use Ruby through CGI. Ruby on Rails could be an option.

Now, if you want Shoes UI on web, this is not possible. There are ways you may be able to do that but not without challenges. For example, you could install a PC/Linux emulator for Web and startup on your Shoes app.

**Comment by BackOrder** [comment]
By the way, headless Shoes is cshoes.

**Comment by ccoupe** [comment]
Web development is a deep dive and Shoes isn't going to be help except as a 'learn to program' experience.  Very different technology restrictions and options.  Whoever owns the server will set the rules for what you can do and it and languages you can use.

**Comment by dredknight** [comment]
Thanks for all the ideas. I wanted to build something simple for internal use. No need to be beautiful or classy. The server will have access to some infrastructure and the web gui will make some statistics out of it. I will be the owner of the server so I can set it up the way I need.

**Comment by passenger94** [comment]
well, just put your shoes app code at a web address and connect ... (via Shoes of course (visit method), everything is ready there to do it)
But be very cautious !! make sure it's only for internal use, you're going to allow runnable code on your system !
try this, should be safe as it is Shoes repo
```ruby
Shoes.app do
    button "visit" do
        Shoes.visit "https://raw.githubusercontent.com/Shoes3/shoes3/master/samples/simple-bounce.rb"
    end
end
```

**Comment by dredknight** [comment]
Thats awesome but those this mean the code you just gave me needs to be executed locally?
There is no need to be browser based and no shoes to be installed on the local system (all shoes things to happen on the server).

The code you shared got some SSL error.

```Ruby
Error in <unknown> line 0 | 2016-12-18 22:00:42 +0200
SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/net/http.rb:923:in `connect'
C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/net/http.rb:923:in `block in connect'
C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/timeout.rb:73:in `timeout'
C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/net/http.rb:923:in `connect'
C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/net/http.rb:852:in `start'
C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/open-uri.rb:318:in `open_http'
C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/open-uri.rb:736:in `buffer_open'
C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/open-uri.rb:211:in `block in open_loop'
C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/open-uri.rb:209:in `catch'
C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/open-uri.rb:209:in `open_loop'
C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/open-uri.rb:150:in `open_uri'
C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/open-uri.rb:716:in `open'
C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/open-uri.rb:724:in `read'
C:/Program Files (x86)/Shoes/lib/shoes.rb:299:in `visit'
qqqq.rb:3:in `block (2 levels) in <main>'
-e:1:in `call'
```

**Comment by ccoupe** [comment]
The SSL error is a real bug with some packaged versions of Shoes. It's likely the Ruby/Shoes certificate is outdated. I've put it on my bug list. 

Although that is a clever bit of code from @passenger94, it does execute locally in your copy of Shoes which is not what you were looking for.

**Comment by passenger94** [comment]
yes locally only, in your local copy of Shoes, 
without questioning the usefulness of it ... instead of rendering an html page, after some number crunching one might render a shoes app on the server side and fetch the result via Shoes, locally, that's what a browser is basically doing ...

**Comment by dredknight** [comment]
I will have to  think it over. It seems the current idea is out of the scope.
Thanks for suggestions! :)
