### ISSUE TITLE
Alert not working on its own anymore

### ISSUE THREAD

**Issue by BackOrder** [Shoes3/shoes3#303]
A simple `alert "hello, world!"` causes the following error on Shoes 3.3.2:

```
NoMethodError: undefined method `app' for main:Object
```

Alert was previously supported without `Shoes.app`. Using `Shoes.app { alert "hello, world!" }` will create an app window **and** an alert. Additionally, this is the first sample code in HacketyHack and obviously not working for the very said reason.

**Comment by ccoupe** [comment]
This going to be such a low priority that you shouldn't expect it be fixed any time soon (perhaps never)

**Comment by BackOrder** [comment]
The question here is what happened in the first place? It was working perhaps a couple version ago...

**Comment by ccoupe** [comment]
It was working long ago for some platforms (Windows?) and not for others.  Now they are all equal ;-) Imagine someone (new) writing a chain of ask/confirm/alerts without ever calling Shoes.app.  I've seen it happen and it's all too common in some bash scripts (once is 'too common' for me). Let's not encourage that.  Call your GUI shoes methods inside the Shoes.app block{} or methods run from inside that block.

**Comment by BackOrder** [comment]
The following are working in Shoes Manual: `alert`, `confirm`, `ask`. (`dialog` may also work)

Only `window` is working in Shoes and Shoes IRB without Shoes.app.

Also, be noted that both Shoes Manual and Hackety Hack code samples include all of them runnable without Shoes.app, which suggests it is standard practice and thus should be supported.

Is Shoes 4 support them without Shoes.app?

**Comment by ccoupe** [comment]
> The following are working in Shoes Manual: alert, confirm, ask. (dialog may also work)

I would expect that. The Manual has a completely initialized and working framework gtk or cocoa and event loops/queues. Dialogs like alert have different rules (especially osx which was greatly modified to be up to date with the later Apple api. There were also changes to the base app (window) in gtt. I don't remember the reason, perhaps @passenger94 does? There was a reason for that change and presumable a trade-off will be needed.

**Comment by passenger94** [comment]
i remember changing some bits to make alert etc work on "run this" in manual context because there was no app avalaible in the running code context ! I think i made a binding of the manual app to the code context

**Comment by ccoupe** [comment]
We tried several settings and settled on this
```
shoes_dialog_alert(int argc, VALUE *argv, VALUE self)
{
    //GLOBAL_APP(app);
    //ACTUAL_APP(app);
    GTK_APP_VAR(app);
```

**Comment by passenger94** [comment]
yes,i remember, but those were for a slightly different story : to be able to launch the alert on the window which requested it and not only on the main window.

**Comment by BackOrder** [comment]
Shoes 4 report: `alert`, `ask` and `confirm` are working but `window` and `dialog` are not working without **Shoes.app**.

**Comment by BackOrder** [comment]
Interestingly, `window` shorthand method is actually defined in Shoes 3, see [shoes.rb](https://github.com/Shoes3/shoes3/blob/master/lib/shoes.rb#L476). It appeared right here in [3.0.0](https://github.com/shoes/shoes/commit/3b0658c281cea24b2ee4aa3f8390a75d113ebaf7) branch (r1313).

**Comment by ccoupe** [comment]
This turns out to be a bit tricky and broken for quite some time.  What is happening is that we don't have 'app' setup when the kernel method `alert` is called.  I'm sure you want to know what other Shoes kernel methods might be usable without a Shoes.App:
*  alert, 
* ask
*  confirm
* ask_color
* font
* ask_open_file, ask_save_file, ask_open_folder, ask_save_folder

All of them probably need to safeguards for this situation, Gtk and Cocoa.

**Comment by BackOrder** [comment]
This seems to be completed. Reopen otherwise.
