### ISSUE TITLE
Funnies ain't so funny.

### ISSUE THREAD

**Issue by BackOrder** [Shoes3/shoes3#304]
The sample code [Funnies](https://github.com/Shoes3/shoes3/blob/master/samples/expert-funnies.rb) in both Shoes3 and HacketyHack is not working. The download stalling on (possibly) redirections. It loads query on google but certainly not [XKCD](http://xkcd.com/rss.xml). Directly invoking HTTPS URL of XKCD will not help. Even famously standard [w3c](https://www.w3.org/) will not work.

[Redirect checker](http://www.redirect-checker.org/index.php) reports:
```
http://xkcd.com/rss.xml
301 Moved Permanently
https://xkcd.com/rss.xml
200 OK
```

**Comment by ccoupe** [comment]
According to XKCD.com About page you're supposed to use json. I subscribe to the atom feed and it's OK but perhaps he dropped rss.xml  . Same question about w3c  does it have and rss.xml?  No visual indication that it does. 

I would not be surprised it there are https problems in Shoes. I suspect packaging has one.

**Comment by ccoupe** [comment]
`wget https://xkcd.com/rss.xml` does produce something reasonable. I get an hpricot error so thats a bug to fix in expert-funnies.rb

**Comment by BackOrder** [comment]
Hpricot? Both are using Nogokiri. I also tested download on its own, hence the mention about other non-rss URLs.

**Comment by ccoupe** [comment]
I didn't have hpricot or nokogiri installed the that ruby (Loose Shoes). Download is actually done in Ruby, a change I made long long ago. lib/shoes/download.rb if you want see what is doing. I also remember a recent commit to Shoes 4 and I made a note to see if Shoes 3.x needs it.

**Comment by ccoupe** [comment]
An Shoes app that knew how to get the daily comics for various sites (lots of web server issues there) would be good project for someone.

**Comment by dredknight** [comment]
I can try this one.

**Comment by BackOrder** [comment]
Good luck @dredknight !

**Comment by ccoupe** [comment]
@dredknight  - did you volunteer to fix the bug or write a more general comics reader?

**Comment by ccoupe** [comment]
The Shoes4 code appears to handle the problem and might be worth backporting into Shoes 3.3.3

**Comment by dredknight** [comment]
@ccoupe  currently writing the shoes-exe GUI. I will take this one after that. Currently I am not sure of approach because adding and using external libs is not my strongest shoes skill but I believe it will be good thing to learn.
I will update you when I have some progress. Thanks for the proposals!

**Comment by BackOrder** [comment]
For reference only:

Shoes 4 approach does work in Shoes 3 with some changes. It would need [download.rb](https://github.com/shoes/shoes4/blob/master/shoes-core/lib/shoes/download.rb) with some minor modifications and [http_request.rb](https://github.com/shoes/shoes4/blob/master/shoes-core/lib/shoes/http_request.rb) with an additional `require "net/https"` and change `@started_proc&.call(response)` to `@started_proc.call(response) unless @started_proc.nil?`.

Your approach @ccoupe is much lighter. Some changes inspired by Shoes 4 might be in order but it's yet unclear whether **open_uri with redirection** or **http_request** is better.

@dredknight don't be shy to share with us, we sure can give you feedback. Your contribution is more than welcomed! :)

**Comment by ccoupe** [comment]
I suspect the Shoe4 code is better but the easy way works, so far.

**Comment by BackOrder** [comment]
> I suspect the Shoe4 code is better but the easy way works, so far.

Shoes 4 is clean and considerably easier to understand. Sometimes a little over-engineered and the final rendering isn't as good as Shoes 3. For example, the Shoes 4 manual is not rendered properly and looks rather retro.

We sure can stick with **open_uri with redirection** for now. My previous comment is meant to be a reference in case something comes up, then it will be possible to dig into issue tracker for alternative solution.

**Comment by BackOrder** [comment]
The code committed on the repository is not working here. It takes a while and then **two** windows open up.

![image](https://cloud.githubusercontent.com/assets/8844578/22438556/6ed10154-e6fa-11e6-9359-7e5b8a33d6c8.png)

**Comment by ccoupe** [comment]
Did you run that with the old Hacketyhack shoes installed?

**Comment by BackOrder** [comment]
> Did you run that with the old Hacketyhack shoes installed?

Sorry? I made a portable installation of HacketyHack. Shoes 3.3.2 is by default.

```
> cshoes -v
Shoes walkabout 3.3.2 r2741 i386-mingw32 2.2.4
``

**Comment by ccoupe** [comment]
I just package up a beta exe walkabout.mvmanila.com/public/shoes/ for 3.3.3 and it does not have the strangeness you show.  However it doesn't fix expert-funnies.rb.

**Comment by ccoupe** [comment]
There's more going on here than I first thought. It's easy to change the xkcd feed to use the proper https: url , and without the open-uri-patch it still hangs on Windows. Digging deeper it seems that uses a https works. Also in image.rb we don't have the patch but it's hanging getting the rss.xml, not the image.

**Comment by ccoupe** [comment]
Now we have something to dig into. From the shoes.log on windows (cross compiled)
```txt
Error in <unknown> line 0 | 2017-02-01 00:13:12 -0700
Image download failed for https://s3.amazonaws.com/static.garfield.com/comics/garfield/2017/2017-01-30.gif because: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
C:/Program Files (x86)/Shoes/lib/shoes/image.rb:39:in `rescue in image_download_sync'
C:/Program Files (x86)/Shoes/lib/shoes/image.rb:26:in `image_download_sync'
foo.rb:4:in `image'
foo.rb:4:in `block in <main>'
eval:1:in `instance_eval'
eval:1:in `block in <main>'
-e:1:in `call'
```

Certs!

**Comment by BackOrder** [comment]
It's possible to disable certificate verification.

```Ruby
output = open(request_uri, {ssl_verify_mode: OpenSSL::SSL::VERIFY_NONE})
```

**Comment by ccoupe** [comment]
That does appear to help with some things.  Be aware that image caching can fool us!

**Comment by ccoupe** [comment]
Ok. I think I have something that works for Linux and Windows.  Two test scripts, samples/expert-funnies.rb (xkcd with https redirect) and this test 
```ruby
Shoes.app {
  stack do
    image "https://shoes.mvmanila.com/public/images/2017-01-30.gif"
    download "https://xkcd.com/rss.xml" do |dl|
     puts "got xkcd rss.xml"
    end
    download "https://shoes.mvmanila.com/public/images/dino.jpg", save: "dino.jpg" do |f|
      puts "got dino image"
    end
  end
  #image "https://s3.amazonaws.com/static.garfield.com/comics/garfield/2017/2017-01-30.gif"
}
```
I think [this beta will work](http://walkabout.mvmanila.com/public/shoes/shoes-3.3.3-gtk3-32.exe
) for windows. It's 22MB because it has debugging symbols - might be helpful in a crash. It has some puts status messages from inside download.rb. Don't forget to clear the image cache with cobbler when testing the image  method. 

It does not verify the ssl certificates but thats OK for now.  I suspect a deeper bug between ruby, openssl, and the two Windows dlls included with Shoes.

**Comment by dredknight** [comment]
Heya. I am back now. Anything I can help with here?

**Comment by BackOrder** [comment]
Welcome back @dredknight !

You have plenty of choices. Let's see...

* Adding code samples to Shoes Manual #317 
* Documenting Chipmunk basic usage #321 
* Documenting `mask` method #113 
* Documenting `dash` style #244 
* Documenting `attach => Shoes::Mouse` #114 
* Adding more relevant samples to samples directory
* Backporting Shoes 4 RSpec #79

**Comment by dredknight** [comment]
Good :)

**Comment by ccoupe** [comment]
Closing. Does not fix that download can be very slow. - different issue.
