### ISSUE TITLE
Packaged app is not logging to files, nor saving/loading files.

### ISSUE THREAD

**Issue by mwiegant** [Shoes3/shoes3#305]
I'm using Ruby's Logger gem and also doing some basic fileIO in my ruby script. My project itself is a set of ruby classes with two additional files that generate Shoe apps. One of those files is the main driver that the entire project starts off from. When I use the Shoes UI to open my project ("app"), it logs to a log file as expected and also saves/loads an external .txt file as expected. Once I package the app with shoes, it stops logging to files or saving/loading my custom .txt files. All the ruby code is read as normal and no errors appear in the built-in Shoes console (alt-/), so I'm not sure if this is a bug in my code or in the Shoes code that packages applications.

As an additional note, the code that use's ruby's Logger class performs logging as soon as the initial Shoes.app is created. So once the UI shows up (which it always does, even when packaged), there should immediately be a log file written to.  I attached a screenshot of my code, in case that may help.

Do you have any suggestions for how I should proceed, and does this sound like an issue on my end or yours?

Thanks,
  Max

![capture](https://cloud.githubusercontent.com/assets/6188869/22436334/72400b18-e6d8-11e6-815a-7aa3de058970.PNG)

**Comment by BackOrder** [comment]
Take a look at the working code below and see if it helps or is related to your problem.

```ruby
require("logger")

Shoes.app {
   logger = Logger.new("logfile.log")
   logger.level = Logger::WARN
   
   logger.info "#1 this is an info"
   logger.warn "#2 this is a warn"
   logger.debug "#3 this is a debug"
   logger.error "#4 this is an error"
}
```
```
# Logfile created on 2017-01-30 14:11:50 -0500 by logger.rb/47272
W, [2017-01-30T14:11:50.586414 #15700]  WARN -- : #2 this is a warn
E, [2017-01-30T14:11:50.586414 #15700] ERROR -- : #4 this is an error
```

**Comment by BackOrder** [comment]
OH! Packaging may be expanding in a temporary directory. You should try to check the directory it's running in at runtime.

**Comment by ccoupe** [comment]
as @BackOrder  said, it's almost certain that the 'current_directory' is not where you think it is.  You'll need to find a permanent place to keep the files after the App quits.

**Comment by mwiegant** [comment]
My source code has /log and /traffic directories for the log files and for the files to be read/written through basic fileIO. I am packaging my project into an entirely different directory and then trying to run it. In my new directory, there is neither of those 2 folders and no errors are thrown by my program, nor does it end up creating the folders (which I don't expect it should, to be honest).

When I was debugging this earlier last week, I was seeing that the packaged code was complaining about not finding those directories, and now it is no longer complaining, although I'm not sure why. I'm confident this is because of some small code change I made. I'll debug this more though and post here with anything I find. I'll also try @BackOrder 's small code snippet he presented and see if I can get that to log correctly when packaged.

**Comment by ccoupe** [comment]
I'm assuming your packaging for  Windows. On the users system, they'll have in C:Program Files (x86)\shoes\shoes.exe + stuff. Your app while running will be in a tmp dir which goes away at exit, deleting anything created in that tmp dir. Your end user may not have permission to create files in Program files and it's kind of an unclean thing to do.  So you need to find a permanent  place to create them, using a full path like c:\Users\Cecil\AppData\Local\MyAppName\  You can build the path by using ENV['Home']

**Comment by mwiegant** [comment]
Can you clarify exactly where I should expect to see the app write to while it is running? I've got 2 folders inside of my AppData\Local\Shoes directory and I've looked through both while the app is running to find a logfile being created by my program. I did not find my logfile. 

----------

I took the small program @BackOrder wrote and added an absolute path for the logger to write to. Running the program through Shoes, unpackaged, saw the file being created and written to. Running the program through Shoes, packaged up, did not see the file get created (or written to).

```
require("logger")

Shoes.app {
   logger = Logger.new("C:/Users/Max/Desktop/loggertest/logfile.log")
   logger.level = Logger::WARN
   
   logger.info "#1 this is an info"
   logger.warn "#2 this is a warn"
   logger.debug "#3 this is a debug"
   logger.error "#4 this is an error"
}
```

**Comment by ccoupe** [comment]
If I remember correctly, the tmp dir used  _while_ a packaged app is running is in Appdata\local\temp but it's Windows that controls that, I think. If you log files have known names, then you  can search for 'them' while Shoes still running (but doing nothing).

That little test script should have worked if the second machine you tested with had the same directories. You do need a second machine to test packaging (or a VM) otherwise you're not testing a real end user situation.   How are you doing the packaging. Which options?

**Comment by BackOrder** [comment]
Could you make sure you know where it is running? Try output somewhere `Dir.pwd` in your app. You could also check to make sure it's not a **Logger** problem by creating and writing to a file in your packaged app: `File.open("C:/Users/Max/Desktop/loggertest/test.txt", "w") { |f| f.write("Ain't no longer, but ain't bad either.") }`

As @ccoupe mentioned, ENV['HOME'], ENV['APPDATA'] are also good candidates to explore.

**Comment by mwiegant** [comment]
I managed to get it working. I'm not quite sure what I was doing wrong but I believe I was looking in the wrong directory for where the .shy file was being generated. I also had to use an absolute path before the logfile would be printed and before I could successfully do fileIO.

---------

Thanks for the help guys :)
