### ISSUE TITLE
Image on gif causes segmentation fault

### ISSUE THREAD

**Issue by BackOrder** [Shoes3/shoes3#306]
The following code works on png files but not on gif files. 

```ruby
Shoes.app {
   image "https://s3.amazonaws.com/static.garfield.com/comics/garfield/2017/2017-01-30.gif"
}
```

```
C:/Program Files (x86)/Shoes/lib/shoes/image.rb:35: [BUG] Segmentation fault
ruby 2.2.4p230 (2015-12-16 revision 53155) [i386-mingw32]

-- Control frame information -----------------------------------------------
c:0009 p:---- s:0031 e:000030 CFUNC  :alert
c:0008 p:0020 s:0027 e:000026 RESCUE C:/Program Files (x86)/Shoes/lib/shoes/image.rb:35
c:0007 p:0054 s:0024 E:00129c METHOD C:/Program Files (x86)/Shoes/lib/shoes/image.rb:24 [FINISH]
c:0006 p:---- s:0017 e:000016 CFUNC  :image
c:0005 p:0009 s:0013 e:000012 BLOCK  170130001T.rb:6 [FINISH]
c:0004 p:---- s:0011 e:000010 CFUNC  :instance_eval
c:0003 p:0010 s:0008 e:000007 LAMBDA eval:1 [FINISH]
c:0002 p:---- s:0004 e:000003 CFUNC  :call
c:0001 p:0000 s:0002 E:002274 TOP    [FINISH]

-- Ruby level backtrace information ----------------------------------------
-e:0:in `call'
eval:1:in `block in <main>'
eval:1:in `instance_eval'
170130001T.rb:6:in `block in <main>'
170130001T.rb:6:in `image'
C:/Program Files (x86)/Shoes/lib/shoes/image.rb:24:in `image_download_sync'
C:/Program Files (x86)/Shoes/lib/shoes/image.rb:35:in `rescue in image_download_sync'
C:/Program Files (x86)/Shoes/lib/shoes/image.rb:35:in `alert'

-- C level backtrace information -------------------------------------------
C:\WINDOWS\SYSTEM32\ntdll.dll(ZwWaitForSingleObject+0xc) [0x77AFE5FC]
C:\WINDOWS\System32\KERNELBASE.dll(WaitForSingleObject+0x12) [0x7518AD52]
C:\Program Files (x86)\Shoes\msvcrt-ruby220.dll(rb_print_backtrace+0x4b) [0x640AF005]
C:\Program Files (x86)\Shoes\msvcrt-ruby220.dll(rb_vm_bugreport+0x78) [0x640AF082]
C:\Program Files (x86)\Shoes\msvcrt-ruby220.dll(rb_bug_context+0x72) [0x63F7AAD6]
C:\Program Files (x86)\Shoes\msvcrt-ruby220.dll(rb_get_next_signal+0xdb) [0x640356B9]
C:\Program Files (x86)\Shoes\cshoes.exe(WinMain+0x496) [0x004019F6]
C:\WINDOWS\System32\KERNELBASE.dll(UnhandledExceptionFilter+0x172) [0x7521D412]
C:\WINDOWS\SYSTEM32\ntdll.dll(LdrSetAppCompatDllRedirectionCallback+0x1ae9d) [0x77B2E0BD]

[Edited]

**Comment by ccoupe** [comment]
Confirmed problem for windows, Linux is fine - suggesting the gif  dll  on Windows is out-of-date?

**Comment by ccoupe** [comment]
after a wget, file says:
`2017-01-30.gif: GIF image data, version 89a, 1200 x 400`

FWIW, OSX handles the image just fine.

**Comment by ccoupe** [comment]
Odd, very odd. Linux libgif was version 4.1.6. Shoes/windows was using version 4.2.3 (so it's newer). Since recent libgifs are easy to build I tried 5.1.4 on Windows -- same failure.  Then I converted the shoes splash.png to .git -- failed to display.  The cartoon and splash  don't crash Shoes with the newer libgif so that's an improvement -- after a few seconds the Shoes.log  has
```txt
Error in <unknown> line 0 | 2017-01-31 16:04:34 -0700
Couldn't load splash.gif. Is the file a valid .gif?

Error in <unknown> line 0 | 2017-01-31 16:04:35 -0700
Couldn't load splash.gif. Is the file a valid .gif?
```

Why two ?

**Comment by ccoupe** [comment]
Good New! The update to libgif 5.1.4 does work properly with the cartoon and my generated gif. You just have to remember to tweak the rake files when changing gif versions. 

New 3.3.1 beta with the fix  at http:/ /walkabout.mvmanila.com/public/shoes/shoes-3.3.3-gtk3-32.exe

**Comment by BackOrder** [comment]
I'm getting a `This application has requested the Runtime to terminate it in an unusual way.` on the GIF image.

```
-- Control frame information -----------------------------------------------
c:0017 p:---- s:0056 e:000055 CFUNC  :alert
c:0016 p:0020 s:0052 e:000051 RESCUE C:/Program Files (x86)/Shoes/lib/shoes/image.rb:35
c:0015 p:0054 s:0049 E:001134 METHOD C:/Program Files (x86)/Shoes/lib/shoes/image.rb:24 [FINISH]
c:0014 p:---- s:0042 e:000041 CFUNC  :image
c:0013 p:0041 s:0037 E:001440 BLOCK  expert-funnies-typhoeus.rb:42 [FINISH]
c:0012 p:---- s:0034 e:000033 CFUNC  :call
c:0011 p:---- s:0032 e:000031 CFUNC  :stack
c:0010 p:0031 s:0028 E:000c74 BLOCK  expert-funnies-typhoeus.rb:36 [FINISH]
c:0009 p:---- s:0024 e:000023 CFUNC  :each
c:0008 p:0039 s:0021 E:001e2c BLOCK  expert-funnies-typhoeus.rb:34 [FINISH]
c:0007 p:---- s:0019 e:000018 CFUNC  :call
c:0006 p:---- s:0017 e:000016 CFUNC  :stack
c:0005 p:0035 s:0013 E:0019cc BLOCK  expert-funnies-typhoeus.rb:30 [FINISH]
c:0004 p:---- s:0011 e:000010 CFUNC  :instance_eval
c:0003 p:0010 s:0008 e:000007 LAMBDA eval:1 [FINISH]
c:0002 p:---- s:0004 e:000003 CFUNC  :call
c:0001 p:0000 s:0002 E:00067c TOP    [FINISH]

-- Ruby level backtrace information ----------------------------------------
-e:0:in `call'
eval:1:in `block in <main>'
eval:1:in `instance_eval'
expert-funnies-typhoeus.rb:30:in `block in <main>'
expert-funnies-typhoeus.rb:30:in `stack'
expert-funnies-typhoeus.rb:30:in `call'
expert-funnies-typhoeus.rb:34:in `block (2 levels) in <main>'
expert-funnies-typhoeus.rb:34:in `each'
expert-funnies-typhoeus.rb:36:in `block (3 levels) in <main>'
expert-funnies-typhoeus.rb:36:in `stack'
expert-funnies-typhoeus.rb:36:in `call'
expert-funnies-typhoeus.rb:42:in `block (4 levels) in <main>'
expert-funnies-typhoeus.rb:42:in `image'
C:/Program Files (x86)/Shoes/lib/shoes/image.rb:24:in `image_download_sync'
C:/Program Files (x86)/Shoes/lib/shoes/image.rb:35:in `rescue in image_download_sync'
C:/Program Files (x86)/Shoes/lib/shoes/image.rb:35:in `alert'
```

**Comment by ccoupe** [comment]
Yes - as mentioned on #304, image.rb  doesn't have the open-url patch and even so https in general seems to be broken in Shoes Windows. Possible consequence of cross compiled ruby 2.2.4 ?

**Comment by BackOrder** [comment]
Good question. Seems like we fell into a bugs nest. o_O

**Comment by ccoupe** [comment]
I suspect the two ssl dlls and their data files have been 'configured' different. File sizes suggest so.

**Comment by ccoupe** [comment]
Did the dilbert gif work?

**Comment by ccoupe** [comment]
I built a shoes.exe on Win7. Same https: problems as the cross compiled Shoes.  Narrows the problem down I guess. Maybe.

**Comment by ccoupe** [comment]
There's some poorly written code in download.rb and image.rb which was not helping to find the real problem. Mea culpa.

**Comment by BackOrder** [comment]
I attempted to use Typhoeus as a replacement in **image.rb** but gif files still crashes Shoes. It crashes upon returning from `image_download_sync`. 

Dilbert and PennyArcade have feeds without images. Alternative [Dilbert](http://comicfeeds.chrisbenard.net/view/dilbert/rss) and [Penny Arcade](http://comicfeeds.chrisbenard.net/view/pennyarcade/default) feeds with images but they need some work anyway. Dilbert original feed is [here](http://dilbert.com/feed) and PennyArcade original feed is [here](https://www.penny-arcade.com/feed).

No matter what, those feed would need some work in expert-funnies. It would need to go on the link of the first entry/item, load the page, find the proper image to download.

**Comment by ccoupe** [comment]
What happens with png file? The return values in the results variable have to match what rbload wants (whiich is more or less) what the OLD curl code wanted, rbload..c is not flexible.

**Comment by BackOrder** [comment]
The PNG from XKCD is working in **expert-funny-typhoeus.rb** and typhoeus based **image.rb**. Just the GIFs aren't working. 

> rbload..c is not flexible.

This would be an understatement.

**Comment by ccoupe** [comment]
Do you have libgif-7.dll  in "Program Files (x86)\shoes" ? Thats the one that worked for me.

**Comment by BackOrder** [comment]
Seems to be in order. I am using your lastest Shoes 3.3.3.

![image](https://cloud.githubusercontent.com/assets/8844578/22534837/f824cac8-e8c4-11e6-94f5-821704d4444f.png)

**Comment by ccoupe** [comment]
Hmm. I also see libgif-4 in mine and yours. remove -4 and see what happens. I don't see in the rake file where that can happen but it is there. It shouldn't be linked into shoes so removing wouldn't fix anything. If shoes fails to run, then it's still linked in.

**Comment by BackOrder** [comment]
Results without `libgif-4.dll`: PNG works, GIF doesn't. Both Typhoeus based and current **image.rb**.

The current **image.rb** crashes on `alert`. Commenting out the alert results in the following error in Shoes Console. Trying some puts revels it's not entering `open url` block. Using `open-uri-patch` is not helping.

https://s3.amazonaws.com/static.garfield.com/comics/garfield/2017/2017-02-01.gif

```
Error in <unknown> line 0 | 2017-02-01 21:40:45 -0500
no implicit conversion from nil to integer
expert-funnies-typhoeus.rb:43:in `image'
expert-funnies-typhoeus.rb:43:in `block (4 levels) in <main>'
expert-funnies-typhoeus.rb:37:in `call'
expert-funnies-typhoeus.rb:37:in `stack'
expert-funnies-typhoeus.rb:37:in `block (3 levels) in <main>'
expert-funnies-typhoeus.rb:35:in `each'
expert-funnies-typhoeus.rb:35:in `block (2 levels) in <main>'
expert-funnies-typhoeus.rb:31:in `call'
expert-funnies-typhoeus.rb:31:in `stack'
expert-funnies-typhoeus.rb:31:in `block in <main>'
eval:1:in `instance_eval'
eval:1:in `block in <main>'
-e:1:in `call'
```

**Comment by ccoupe** [comment]
That's the ssl bug, not the gif bug. I replaced the alert with a raise and a real error message to discover its a certificate problem

**Comment by BackOrder** [comment]
I downloaded the said GIF and use image on it locally, it does load the GIF.

Unfortunately, it might be more than that certificate problem. It's not working on non-HTTPS gif either. It's actually very hard to find non-HTTPS server nowadays.

http://galleryproject.org/gallery2/main.php?g2_view=core.DownloadItem&g2_itemId=7529&g2_serialNumber=2

**Comment by ccoupe** [comment]
I have a server that should support both https and http. so I uploaded the problem baby to http://ccoupe/shoes.mvmanila.com/public/images/2017-01-30.gif

**Comment by BackOrder** [comment]
Good idea!

**Comment by ccoupe** [comment]
Gif bug is closed. Long discussion about better downloaders should be a new issue.
