### ISSUE TITLE
cshoes: Ctrl+C doesn't kill the Shoes window

### ISSUE THREAD

**Issue by 7stud** [Shoes3/shoes3#308]
Mac OSX 10.10.5
Shoes walkabout (3.3.2 r2741)

After starting a Shoes app with cshoes, in order for me to terminate the app I have to hit Ctrl+C, and then I have to click somewhere on the Shoes window to make it close.  Ctrl+C alone won't make the window close.

Also, if I use cshoes to launch a Shoes app, then close the app window by clicking on the 'x', I don't get control back of my Terminal window, and hitting Ctrl+C does nothing to alleviate that state of affairs.  To bet control back of my Terminal window, I have to click on the Shoes icon in the Dock (which makes the Shoes icon in the Dock disappear).

**Comment by ccoupe** [comment]
Like most multi-document OSX app's you quit  Shoes with that Apple-Q  keys or the menu in menu bar.

Apple does not maintain much of a connection between launch terminal and a Gui app so really can't ctl-c the terminal (somes times two ctl-c's will do it - sometimes not). cshoes is just a little bash script that you can look at to see how osx launchs apps.
