### ISSUE TITLE
Shoes appearance does not match native windows on OSX

### ISSUE THREAD

**Issue by 7stud** [Shoes3/shoes3#310]
OSX 10.10.5
Shoes 3.3.2 r2741

In Shoes:

1. A window's title is blurry.

2. A window's min, max, and 'x' out buttons don't match a native app's buttons.  The `-`, `x`, and max symbols inside those buttons in Shoes are bolder and blurry.

For comparison, in a python tkinter gui app, 1) and 2) are perfect.

3.  The elements `title` and `subtitle` have their text cut off at the baseline of the text. 

![shoes1 copy](https://cloud.githubusercontent.com/assets/891276/22569440/c84a017a-e954-11e6-91f1-73adf77f2a7c.jpg)

For comparison, here is what a macvim app's window looks like:

![shoes2 copy](https://cloud.githubusercontent.com/assets/891276/22569456/d1a95b62-e954-11e6-93e4-99f6733f7207.jpg)

...and a python tkinter program's window:

![shoes3 copy](https://cloud.githubusercontent.com/assets/891276/22570190/9db2f09a-e957-11e6-8952-5c7d932b793f.jpg)

Code for Shoes program:

```ruby
Shoes.app do
  stack do
    title "Title"
    subtitle "subTitle"
    tagline "Tagline"
    caption "Caption"
    para "Para"
    inscription "Inscription"
  end
end
```

**Comment by BackOrder** [comment]
Would you mind posting screenshots for reference?

**Comment by 7stud** [comment]
BackOrder,

I added some screen captures to my original post.

**Comment by bolandross** [comment]
Having the same problem on my Mac, seems to be an issue on retina screens only though. 7stud, can you confirm that?

**Comment by bolandross** [comment]
<img width="287" alt="screen shot 2017-05-17 at 20 09 19" src="https://cloud.githubusercontent.com/assets/5481702/26169122/d58d5230-3b3c-11e7-8467-f8e9fa4314d7.png">
Also, this is what I get when opening the information panel for the Shoes.app. Important for this issue is the "Open in Low Resolution" checkbox, which can't be unchecked. This is something that has to be enabled by the app developer, I think there is a .plist entry for that.

Also, the Version number seems to be invalid, but I guess this is off topic now 😅

**Comment by ccoupe** [comment]
You could edit the plist and add this 
```
<key>NSHighResolutionCapable</key> <true/>
``` 
in the proper place.   I don't have a retina display so there is no way for me to test. If that works, I would expect other drawing problems to appear shortly.

**Comment by ccoupe** [comment]
I've uploaded [a shoes 3.3.3 beta]https://walkabout.mvmanila.com/public/shoes/shoes-3.3.3-osx-10.9.tgz) that enables retina in the plist.  Does that work? No way for me to know, so I'll need you to test it. 

> Also, the Version number seems to be invalid, but I guess this is off topic now :sweat_smile:

Although this appears to be cosmetic - only Finder -> Show Info displays it and it does not keep Shoes from working, it does point to a weakness in the build scripts/rakefiles dating back to long ago and needs to be fixed.  Thanks for reporting that.

**Comment by bolandross** [comment]
@ccoupe Thanks for the quick upload! I just tested it on a Retina MacBook and have good news:
The checkbox is now **not** greyed out anymore and Shoes runs in retina mode as default. All the labels and text elements are now sharp and not blurred anymore.
<img width="280" alt="screen shot 2017-05-18 at 10 41 53" src="https://cloud.githubusercontent.com/assets/5481702/26193817/ab3d8fd4-3bb6-11e7-88d4-ace487ac0215.png">

**Comment by ccoupe** [comment]
@bolandross  - thank you the follow-up and the testing.

I fixed the Version string problem  with the [here](https://walkabout.mvmanila.com/public/shoes/shoes-3.3.3-osx-10.9.tgz).  It should show `Shoes walkabout 3.3.3 r(2923)
