### ISSUE TITLE
Cleaning up Shoes repository

### ISSUE THREAD

**Issue by BackOrder** [Shoes3/shoes3#312]
This task involves cleaning up Shoes repository. The following came up from email conversations with @ccoupe. Please, share your feedback and ideas here.

- Name convention for Rake [targets](https://github.com/Shoes3/shoes3/tree/master/make). Lets' say **platform-version[-arch][-cross]** where you could find `windows-7-64bits`, `osx-sierra-cross`, etc.
- Remove unused, unsupported and unmaintained targets: `darwin`, `mingw`, `osxgtk`, `xmsw32`.
- Remove unused and outdated static files: `README.2008`, `README.2011`, `README.federales`, `Bloopsaphone`, `ftsearch`, `hpricot`, `JSON`, `manual-snapshots`, old directories and old rakefiles at root directory.
- (Re)move test files in root directory such as `radar.ods` and `brownshoes.svg`.

Anything else? @passenger94 , @dredknight ?

**Comment by BackOrder** [comment]
**bloopsaphone** is currently unsupported by current targets and also unmaintained. Shall we remove?

One interesting thing about this extension is that it provides a Sound class and a Bloops class (a .blu sound player). There is a [blu tuner](https://github.com/ashbb/blu_tuner) source code online. Perhaps something @dredknight might like for his game.

@ccoupe would you mind trying to build this with one of your targets and see if it works? If you think it's worthwhile to keep or shall I remove it and all its references?

**Comment by BackOrder** [comment]
The following steps are necessary to fully remove `ftsearch` from Shoes:

- Include **picky** and **yajl** gems in Shoes by default (@ccoupe?)
- Replace [search.rb](https://github.com/Shoes3/shoes3/blob/master/lib/shoes/search.rb) with [search_picky.rb](https://github.com/Shoes3/ebook/blob/master/search_picky.rb) from Shoes eBook.
- Generate and include Picky database on Shoes Manual for Shoes release
- Remove `ftsearch` from various Rakefiles and Makefile.
- Finally remove [ftsearch directory](https://github.com/Shoes3/shoes3/tree/master/req/ftsearch).

**Comment by ccoupe** [comment]
> bloopsaphone

The problem was that it was never cross platform and uses a very old and low level lib. Sound in Linux has improved (more complex) since then but I'm not sure we can depend on one lib for all linux variants. I don't know what Windows provides now and of course there is OSX.  At the time, no one would admit to using it or wanting to use it.

**Comment by BackOrder** [comment]
Bloopsaphone is actually implemented using the very cross-platform [PortAudio](http://www.portaudio.com/). It shouldn't be a stretch to make it work with updated libraries. 

The point here would be to make it work on **one** platform and see if it's worthwhile. Otherwise, I could remove it for now, or just leave it there, and open an issue for a future Sound class implementation. We may explore PortAudio, [OpenAL](https://www.openal.org/), [LAME](http://lame.sourceforge.net/) for MP3 support and so on. At a later time.

By the way, what is your take on **ext** vs implementing inside Shoes? For example, sqlite3, hpricot, ftsearch, chipmunk and bloopsaphone are all implemented in an ext. SVG and Charts are however implemented directly in Shoes core code.

**Comment by BackOrder** [comment]
Additionally note on commit 3086cdc: the removal of mingw target may be only partial because the code extensively uses `/mingw/` matching pattern, which means other targets may also share the code. For example, my previous Shoes building environment revel the `RUBY_PLATFORM` is **i386-mingw32** which would match. Removing any further code related to mingw will require testing.

**Comment by BackOrder** [comment]
Additional note on commit 	1367cc2: the removal of **darwin** target may be only partial because the code extensively uses /darwin/ matching pattern, which means other targets (mavericks, snow, xmavericks, xsnow and yosemite) may also share the code. Removing any further code related to darwin will require testing.

**Comment by BackOrder** [comment]
Additional note on commit f171c77: require building yajl-ruby from source. The new version of Shoes includes a new version of Ruby, which will not allow to gem install yajl-ruby without compiling. `gem install yajl-ruby` on Windows will attempt to build the gem and thus requires RubyInstaller DevKit available. Ultimately, both Picky and Yalj-Ruby should be included in Shoes release as mentioned above.

**Comment by ccoupe** [comment]
Anyone who clones now, it going to get a build that won't work because the gems are not build for 3 or 4 platforms.

**Comment by BackOrder** [comment]
You can revert it back if you feel strongly about this one. No problem. The commits are made in such way to make it easy to revert.

**Comment by ccoupe** [comment]
Furthermore why are these commits showing up in #258 ? That doesn't seem correct.

**Comment by BackOrder** [comment]
> Furthermore why are these commits showing up in #258 ? That doesn't seem correct.

Uh? Not here. And your commit comment went on shoes/shoes instead of shoes3/shoes3. Some kind of Github bug? Maybe clear your browser cache?

**Comment by ccoupe** [comment]
It may be a github bug. but the email of the commit I got was titled
`Re: [shoes/shoes] Shoes Federales - 3.2 (#258)` with a message body of 
```txt
@BackOrder pushed 1 commit.

    5a7c046 Cleaning up static files for #312

—
You are receiving this because you are subscribed to this thread.
View it on GitHub or mute the thread.
```
Makes no sense:  It's a re: of a shoes/shoes pull request that shoes/shoes will never answer. Wouldn't be in my browser cache since it was an email .

**Comment by ccoupe** [comment]
Actually, it's not easy for me to rollback the commit since I didn't make it and I don't want sync my copy with github at this time.

**Comment by BackOrder** [comment]
> Actually, it's not easy for me to rollback the commit since I didn't make it and I don't want sync my copy with github at this time.

Not any easier for anyone. haha

No worries. Reverted for you.

**Comment by ccoupe** [comment]
> portaudio

Ah yes! I remember when when their 2.0 release broke my audio system for all apps on the linux  box and caused one hell of cleanup problem to get 1.9 back.  Wiki's by nature can be out of date but https://app.assembla.com/wiki/show/portaudio/Notes_about_building_PortAudio_with_MinGW is not so inspiring.  Perhaps we could do something like vlc and detect if portaudio is installed and ffi into it but I am not inclined to build the .dll or .so and include them in Shoes.  Please make a new issue if you want bloopsaphone because **cleanup** was the reason it is not it Shoes 3.

**Comment by BackOrder** [comment]
Thanks for the feedback. I will open a new issue about this.

**Comment by dredknight** [comment]
heya! Thanks for the suggestion. Unfortunately I dont think I have enough in house Shoes knowledge to contribute with anything meaningful here.

**Comment by BackOrder** [comment]
@dredknight this is actually why your feedback is valuable. The clean up is part of an effort to make Shoes accessible to everyone or at least a wider audience. Same goes for #311 (Msys2 and Windows). Ultimately, this cleaning is part of a bigger simplification process for Shoes.

This simplification should allow you, for example, to be able to build your own Shoes by yourself and move around the code with at least some kind of better understanding of what's going on.

So this specific issue here is about removing dead wood, anything that is unused, no longer maintained and is making a mess for anyone who wants to understand how Shoes works.

**Comment by dredknight** [comment]
@BackOrder that is awesome :)! I will follow this with interest. I will happily test any version on my app. It is going to become even more complex in the future :D.

**Comment by BackOrder** [comment]
@dredknight I'm so curious about your app. Any screenshot or something? Unrelated to this issue... we should have some place to showcase what is being done in Shoes. It might inspire other people to use Shoes. Maybe a page on the main webside.

**Comment by dredknight** [comment]
some oftopic but you can download it from [here](http://www.moddb.com/mods/might-magic-heroes-55/downloads/mmh55-reference-manual).
It is the official guide for an unofficial mod for heroes of might and magic V.
That will be nice :).

**Comment by BackOrder** [comment]
@dredknight The wheel with images is awesome, fully interactive!

**Comment by dredknight** [comment]
Thanks @BackOrder  :) :) ! It took a lot of effort and git hub tickets in this section to complete :D. The other tabs besides the wheel grew as branches of the app later.

**Comment by ccoupe** [comment]
Turns out make/darwin/* was used. OSX no longer builds. Please test things before committing to master.

**Comment by BackOrder** [comment]
Need a revert?

**Comment by ccoupe** [comment]
I've got them from a backup. I'll add the to git if needed.

**Comment by ccoupe** [comment]
Warning: OSX 10.6 aka, snow leopard is likely to be deleted (since they haven't for quite a while and no good way to test)

**Comment by BackOrder** [comment]
It sounds fair. It was good to support it for some time. Thanks.

Same goes Windows XP. Microsoft has been particularly aggressive in their upgrade strategy including forcing users to upgrade to Windows 10 regardless of them agreeing.

**Comment by ccoupe** [comment]
Also on the chopping block is i686-linux (32 bit) as a distributed package - can always build from source it you happen to have such a box or VM and care enough. 

> Microsoft has been particularly aggressive

Apple is not shy with with the deprecation broad sword.  There are real security problems with those old OS versions. They both have monetary reasons as well.

**Comment by BackOrder** [comment]
What about structuring the **make directory** in such way:

```
make/
   linux/
      i686_linux
      pi2
      x86_64_linux
      xarm6hf
      xwin7
   osx/
      mavericks
      xmaverics
      yosemite
   win32/
      msys2
      win7
```

**Comment by BackOrder** [comment]
This is very good. Things are getting clearer.

What do you think about moving `fixed` and `bugs` directory within `Tests` directory?

**Comment by ccoupe** [comment]
> What do you think about moving fixed and bugs directories within Tests directory?

Unclear what my thoughts were for fixed/ (they could be just be merged into bugs/ ? or deleted?) Tests was intended for a place for automated tests to reside testunit or minitest stuff - a convention I broke by putting the plot tests in there - those are not automated tests, but they aren't user bug reports scripts either.

**Comment by BackOrder** [comment]
Deleted would do provided they outlive their purpose. The idea is grouping files and directories. If you consider those have served their purpose, the remove.

**Comment by ccoupe** [comment]
There is a [new beta for Windows](https://walkabout.mvmanila.com/public/shoes/shoes-3.3.3-gtk3-w32.exe
) that includes all the picky gems for win7 as well as the ftsearach ext. This should allow you to test your help.rb. It would be 'very helpful' if you created a remote branch  for the manual replacement code and issue pull requests on that brach.

**Comment by ccoupe** [comment]
You want a win7-custom.yaml that has some additions
``'ruby
InclGems:
  - sqlite3
  - nokogiri-1.6.7.1-x86-mingw32
  - mini_portile2-2.0.0
  - byebug-8.2.1
  # - columnize-0.9.0
  - rb-readline-0.5.3
  - win32-shortcut-0.2.5
  # picky needs:
  - activesupport-5.0.0.1
  - concurrent-ruby-1.0.2
  - i18n-0.7.0
  - multi_json-1.12.1
  - picky-4.31.3
  - rack_fast_escape-2009.06.24
  - thread_safe-0.3.5
  - tzinfo-1.2.2
  - url_escape-2009.06.24
  - yajl-ruby-1.3.0
```

**Comment by BackOrder** [comment]
> It would be 'very helpful' if you created a remote branch for the manual replacement code and issue pull requests on that brach.

How do I do that? I am not familiar enough with GitHub on such topics. Not a big user of git either.

**Comment by BackOrder** [comment]
> There is a new beta for Windows that includes all the picky gems for win7 as well as the ftsearach ext. This should allow you to test your help.rb.

Picky hasn't been included in the beta.

```
cshoes -g list

*** LOCAL GEMS ***

bigdecimal (1.2.6)
byebug (8.2.1)
io-console (0.4.3)
json (1.8.1)
mini_portile2 (2.0.0)
nokogiri (1.6.7.1 x86-mingw32)
psych (2.0.8)
rake (10.4.2)
rb-readline (0.5.3)
rdoc (4.2.0)
sqlite3-ruby (1.3.9)
win32-shortcut (0.2.5)
```

**Comment by ccoupe** [comment]
Oops. I uploaded the wrong one. [It's uploaded now](http://walkabout.mvmanila.com/public/shoes/shoes-3.3.3-gtk3-32.exe). 24Mb is size.

**Comment by ccoupe** [comment]
> How do I do that? I am not familiar enough with GitHub on such topics. Not a big user of git either.

Gotta laugh - the irony is strong.Iit was you who convinced me to move to git. Because all the real projects do.  Remember that?  I learned from [RTFM ](https://git-scm.com/documentation). A deep dive you have to go through but basically you create a local branch of **your** copy of the shoes repo - perhaps 'picky' for example.

You 'git checkout master' or 'git checkout picky' Not sure how your gui app does it but it should if' it's worth anything. So you chose picky and make some changes to that  code branch you think should be saved.  Now you need a remote branch (at github) so your  local branch  (picky .e.g) can be moved up to github.  How that is done is a google search and trial and error. Then you can issue a pull request (PR) and I can merge approve/lgnore/deny your request and  merge into the github master (may not be same a your master branch).

 @passenger94 - is this almost correct?

You can issue a pull request (PR is the lingo)

**Comment by BackOrder** [comment]
> Gotta laugh - the irony is strong.It was you who convinced me to move to git. Because all the real projects do. Remember that?

Indeed, it is. You never wondered why I sent you code by email? The weird thing about Git is that it feels the need to be different and the commands are all weird. You'd think after using CVS, SVN and Mercurial for a very long while, I'd know how to use Git just as well. I'm mostly sticking to Github Desktop.

This was regardless a good move for Shoes. We have been able to successfully track changes in the code, track issues, and Shoes improved considerably since then.

Thanks for the pointers. Stay tuned.

**Comment by BackOrder** [comment]
Forked shoes3 in https://github.com/BackOrder/shoes3

Already committed a working Picky replacement for ftsearch.

Now I have another pending commit (not yet in the repo) that removes ftsearch but no way to test it since new Windows target is not ready. Would you like me to commit to the fork and you can test on your system before making a pull request?

**Comment by ccoupe** [comment]
>  removes ftsearch

No need for a delete commit. It should be as simple as remove one line in the custom-yaml files and rebuilding them all once I get all platforms with copies of the gems - tonight's task.

**Comment by BackOrder** [comment]
Ah, it should be noted that there are several references to ftsearch all over the place. The list of files affected by the removal are `make/make.rb`, `platform/nix/Makefile`, `Rakefile`, every `tasks.rb` file and `req` directory.

**Comment by ccoupe** [comment]
We can't know if the references are actually used.  Lot's of dead code. Once you submit a PR for your picky using shoes.rb/help.rb and I can figure out how to merge it then it's my task to build all the Shoes and give them some simple manual tests. Then we can figure out what old ftsearch refs are not required.

**Comment by BackOrder** [comment]
A pull request is currently pending for you. Let me know if you need help.

**Comment by BackOrder** [comment]
Let's not forget to move code from [rakefile_mingw.rb](https://github.com/Shoes3/shoes3/blob/master/rakefile_mingw.rb) to wherever it should go and subsequently remove the file from the root directory.

**Comment by BackOrder** [comment]
The sample directory is growing. Shall we restructure? It would need some fix in Shoes Manual to include samples.
```
   Samples/
      Expert/
         ...
      Good/
         ...
      Simple/
         ...
```

**Comment by ccoupe** [comment]
You may find that the manual (sidebar menu) doesn't allow that level (4)

**Comment by BackOrder** [comment]
> You may find that the manual (sidebar menu) doesn't allow that level (4)

It didn't stop me. :)

**Comment by ccoupe** [comment]
Bloopsaphone should be a separate  issue.  Most of the above discussion above has been accomplished. Closing.
