### ISSUE TITLE
Farnsworth-Munsell 100 Hue Color Vision Test (Sample)

### ISSUE THREAD

**Issue by BackOrder** [Shoes3/shoes3#314]
Added a new expert sample [Farnsworth-Munsell 100 Hue Color Vision Test](https://github.com/Shoes3/shoes3/blob/master/samples/expert-colours.rb) in commit b55cf902850e4d001cd069dcedf2d8311f0c8567.

* Fully coloured
* Drag and drop
* Completion progress
* Animation on success
* Help key (h)

References:
https://en.wikipedia.org/wiki/Farnsworth-Munsell_100_hue_test

**Comment by BackOrder** [comment]
![image](https://cloud.githubusercontent.com/assets/8844578/22896334/b40f34a4-f1ed-11e6-9dd2-7a8db441e9c3.png)
![image](https://cloud.githubusercontent.com/assets/8844578/22896342/ba9a1c44-f1ed-11e6-80e9-02359ac2ffbb.png)

**Comment by dredknight** [comment]
This is great :)! Did it up to 90%

**Comment by BackOrder** [comment]
@dredknight thanks. Press h for some hint.

**Comment by ccoupe** [comment]
For some reason, Shoes doesn't find this from the manual->futhermore->samples. in new builds  of Shoes.  I have no idea why.

**Comment by ccoupe** [comment]
And now it shows up. Perhaps we could find a more descriptive name that 'expert-colours'.

**Comment by BackOrder** [comment]
> Perhaps we could find a more descriptive name than 'expert-colours'.

Your suggestions are welcomed. **Farnsworth-Munsell 100 Hue Color Vision Test** or any part of it sounds complicated. Also, I was thinking to eventually add few more colours samples.
