### ISSUE TITLE
refresh an Image?

### ISSUE THREAD

**Issue by 7stud** [Shoes3/shoes3#323]
It would be nice if there was a way to make Shoes ignore the image cache and go get the image from disk(or the web) again.  Can that currently be done?

**Comment by BackOrder** [comment]
Could you provide a sample code where the problem occurs?

**Comment by ccoupe** [comment]
There is no easy way to clear the image cache from inside an active Shoes program and  no way to tell Shoes not to cache an image.  The latter might be possible in a future release. 

In the meantime, dedicated coders could find the key into the sdbm filesafter a deep dive into source - much of it Ruby and inside shoes and figure out how and delete and image from the cache. See lib/cobbler.rb

**Comment by BackOrder** [comment]
A sample code would really help. I became aware Shoes is caching in issue #304. Never met caching problem. It may mean the way I use Shoes work around caching altogether. Got few ideas..
