### ISSUE TITLE
Github release tags

### ISSUE THREAD

**Issue by BackOrder** [Shoes3/shoes3#324]
I was looking on Github for the [Shoes Splash Screen](https://github.com/Shoes3/shoes3/blob/master/samples/expert/expert-curve-animation.rb) to turn it into a sample. This is challenging because one has to dig into all the commits / history until finding the proper previous version.

The upcoming 3.3.3 version should use [Github Release](https://github.com/Shoes3/shoes3/releases) to make our lives easier when we have to dig into the past. It basically uses [Git Tagging](https://git-scm.com/book/en/v2/Git-Basics-Tagging).

Additionally, it would be great if it would be possible to tag previous releases.

**Comment by ccoupe** [comment]
I'm going to close this. Reopen if you feel strongly.  From what I've read,  it's not going to work as expected and brings some "easy to forget" overhead for releasing .
