### ISSUE TITLE
Back and forward buttons support for Shoes Manual

### ISSUE THREAD

**Issue by BackOrder** [Shoes3/shoes3#33]
The Shoes Manual currently does not support back and forward mouse buttons. A list of read sections would have to be built and handling click events on **back button (value 4)** and **forward button (value 5)**. Implementation will take place in https://github.com/Shoes3/shoes/blob/master/lib/shoes/help.rb.

**Comment by ccoupe** [comment]
Oh yes! Using the search feature is clumsy without some navigation back to the search or whatever page you started from.

**Comment by BackOrder** [comment]
Reference implementation 80f39325430caabd450376ee04a3ab975509b236.

**Comment by BackOrder** [comment]
Fully implemented feature including buttons on screen, mouse buttons and alt left and right arrows.
