### ISSUE TITLE
Native Tooltips

### ISSUE THREAD

**Issue by BackOrder** [Shoes3/shoes3#340]
Do you all remember Popup text auto-scaling issue #294 ? It is fairly easy to add **Tooltips** to widget in Shoes. Here is a small test adding a tooltip to a button. It should be possible to mixin a Tooltips method for every widget. Or perhaps Canvas class could host it?

Modifying `shoes_native_button` function in `gtk.c`:
```c
if (!NIL_P(shoes_hash_get(attr, rb_intern("tooltip")))) {
  gtk_widget_set_tooltip_text(GTK_WIDGET(ref), RSTRING_PTR(shoes_hash_get(attr, rb_intern("tooltip"))));
}
```

Sample usage:
```ruby
Shoes.app do
   button("Click me!", tooltip: "Shoes button now has tooltips?!")
end
```

![image](https://cloud.githubusercontent.com/assets/8844578/23838106/48bca70a-0768-11e7-95cc-0dc827e19e65.png)

How does it fare with longer text?

![image](https://cloud.githubusercontent.com/assets/8844578/23838128/7c86653a-0768-11e7-9527-323e3db9c4e2.png)

**Comment by ccoupe** [comment]
Awesome!

**Comment by dredknight** [comment]
Great :)!

**Comment by BackOrder** [comment]
Thanks guys! Tooltip is now implemented for `button`, `check`, `edit_box`, `edit_line`, `list_box`, `progress`, `radio`, `slider` and `text_edit_box`.

It may be possible to add tooltip to `Image`, `TextBlock`, `Shape`, `Svg`, `Video` and `Plot` but will require the use of [`GtkTooltip`](https://developer.gnome.org/gtk3/stable/GtkTooltip.html) with a defined area.

Would changing tooltip at runtime interesting? Got an idea...

**Comment by BackOrder** [comment]
Now comes with a tooltip getter and setter on all the widgets above. 

```ruby
Shoes.app do
   flow do
      @b = button("button", tooltip: "some tooltip") do
         @p.text = @b.tooltip
      end
      @p = para
   end
   
   every(1) do |n|
      @b.tooltip = "tooltip ##{n}"
   end
end
```

**Comment by BackOrder** [comment]
And `Video` also has tooltip...

![image](https://cloud.githubusercontent.com/assets/8844578/23880321/57e09d60-0829-11e7-9ef1-3c5657e351e8.png)

**Comment by dredknight** [comment]
Man.. you got into some god-mode the last couple of weeks....

**Comment by BackOrder** [comment]
@dredknight haha! Something wonderful happened after moving few widgets around — Shoes internals became "_obvious_". Wanna do this? Wanna do that? Oh, just put this here, put that there. Got the feeling it will only get better.
