### ISSUE TITLE
VLC reports a display error

### ISSUE THREAD

**Issue by BackOrder** [Shoes3/shoes3#341]
Open a video with `samples/expert-video-player.rb` using **cshoes** and it will display the following error — `[0576d36c] core vout display error: Failed to set on top`.

**Comment by ccoupe** [comment]
Thats a vlc error error - not Shoes and I've never found the magic to stop it.

**Comment by BackOrder** [comment]
This is a partial duplicate of **Regression: 3.3.2 Video on Windows** #273. Closing this issue in favour of its predecessor.
