### ISSUE TITLE
Move is undocumented?

### ISSUE THREAD

**Issue by dredknight** [Shoes3/shoes3#342]
Just noticed that I couldnt find anything for Move in the manual.
Not a sample but just a snippet that comes from @BackOrder's  example #314 

```Ruby
 motion do |left, top|
      @top_rect.move(left - (@controller.width / 2), top - (@controller.height / 2)) unless @controller.nil?
   end
```
I was wondering how is he moving those squares along the mouse.

**Comment by BackOrder** [comment]
![image](https://cloud.githubusercontent.com/assets/8844578/23924585/a1478bea-08e1-11e7-9ad4-12179ddd4c35.png)

**Comment by dredknight** [comment]
Thanks. I missed it somehow.
