### ISSUE TITLE
Shoes API deprecation

### ISSUE THREAD

**Issue by BackOrder** [Shoes3/shoes3#343]
Shoes has some methods that would be best deprecated but in a fashionable manner. For example, `to_pattern` for `Background` and `Border` classes is irrelevant because they are both already patterns ([see comment](https://github.com/Shoes3/shoes3/issues/317#issuecomment-281839746)). Another example is [ListBox is not an actual ListBox](https://github.com/Shoes3/shoes3/issues/337#issuecomment-287245760).

The deprecation allows to provide a replacement method when necessary. Using `require_relative "shoes/deprecated"` in `lib/shoes.rb#self.visit` seems to work (better place?).

![image](https://cloud.githubusercontent.com/assets/8844578/24027042/338077fa-0a9b-11e7-9ee1-23b63445cf05.png)

`lib/shoes/deprecated.rb`
```ruby
require 'rubygems'

class Shoes 
   module Types
      class Background
         extend Gem::Deprecate

         deprecate :to_pattern, :none, 2017, 10
      end
   end
end
```
Deprecated class method:
```ruby
class SomeClass
   extend Gem::Deprecate
   
   class << self
      deprecate :some_class_method, :none, 2017, 10
   end
end
```
Replacing a method by another:
```ruby
class SomeClass
   extend Gem::Deprecate
   
   def some_class_method
      new_shiny_method
   end
   deprecate :some_class_method, :new_shiny_method, 2017, 10
   
   # Ruby or C level replacement
   def new_shiny_method
      # do something shiny
   end
end
```

**Comment by BackOrder** [comment]
This is already completed but would be nice to document on the wiki. Any recommendation where it should be?

**Comment by ccoupe** [comment]
Wiki files live in a single backing store - new-file-name.md has to be unique among all the other articles. The appearance of a Two Level system in the menus is maintained by hand editing the menus for each section and editing the _sidebar.md's.  Unless you have a git clone of the wiki I do the editing of the menus. So, write the article, suggest a category on this issues and hopefully I'll remember when I get around to stitching new wiki category and/or articles into the menus.  There's three 'loose' articles (bsd and two msys2) so a fourth is not a large problem.

**Comment by BackOrder** [comment]
Alright!
