### ISSUE TITLE
Windows Gtk3 theme is missing.

### ISSUE THREAD

**Issue by ccoupe** [Shoes3/shoes3#345]
Hoisted up from a comment in #311 to be it's own issue. It's not msys2 specific as it affect all Windows builds.

1) Shoes is not using the win32 theme that gtk2 had. - normal priority - in 3.3.3
2) Someway for users to download and set the theme - enhancement - maybe not in 3.3.3

http://stackoverflow.com/questions/37035936/how-to-get-native-windows-decorations-on-gtk3-on-windows-7-and-msys2
[Adwaita-icons ](http://www.linuxfromscratch.org/blfs/view/svn/x/adwaita-icon-theme.html)

**Comment by ccoupe** [comment]
It's working but it's got some downsides, perhaps big downsides.

1.  It's noticeably slower when Shoes displays widgets or the file/folder dialogs.  
2.  It's one more addition to the pre_build step when compiling - noticeable because Adwaita icons are very complete. - Lot's of them.
3. It increases the nsis packaged file size by 90%  from 13MB to 25MB.  Qtifw installer increases by 12MB or so to 42MB
4. It slows the installer and uninstaller - lots more files to display. 

[Here's a Shoes](https://walkabout.mvmanila.com/public/shoes/Shoes-3.3.3-gtk3-w32.exe) built with msys2, and newest msys2 dep and the MS-Window theme options. Note the slight name change.

**Comment by ccoupe** [comment]
The perfect way forward would be new handcrafted theme that doesn't depend on the bloated Adwaita. That will be a task for someone else to do - not me.  The process of installing themes is not hard unless they depend on other themes - like the built-in Win32 does. Just copy the files into a share/themes/<your-name>, generated to indexes (perhaps) and if want you own  icons (please!), put them in share/icons/<your-name> - you might need to generate the cache in your testing and set you /etc/gtk-3.0/settings.ini to the new theme.   It's also complicated enough that you might want to do a side project instead of stuffing a Windows only cobbler option.   

Themes might be a good candidate for those qtifw add-on components.

**Comment by BackOrder** [comment]
Could Adwaita be stripped out for Shoes? Maybe update icon cache would help:

* https://developer.gnome.org/gtk3/stable/gtk-update-icon-cache.html
* http://askubuntu.com/questions/279773/what-is-icon-theme-cache

**Comment by ccoupe** [comment]
> Could Adwaita be stripped out for Shoes? Maybe update icon cache would help:

It could be stripped down. I tried for a day.  You have to know themes and GTK3 and  which icons and sizes Shoes/Gtk3/Windows needs otherwise you're just building (already slower) and testing (never fast) and you need a decent test program - all widgets, all file/folder dialogs and a willingness to suffer segfaults until you get it right.

**Comment by ccoupe** [comment]
Copied from #311 

>https://www.gnome-look.org/browse/ord/latest/
>There are a lot of themes available for GTK 2 and GTK 3 over there. 

Most them won't change Shoes in any useful manner.  Gtk themes can be for all apps,(like adwaita)  or specific app groups (gnome-desktop apps) or even a specific app like Nautilus for gnome-shell. Shoes/Windows needs an app specific light weight theme. 90% non starters on that list of gtk3 themes (my guess)

Should Shoes  ever get the  ability to switch to user specified theme,s it's going to need some sort of way to sort those 723 gtk3 theme into usuable for Shoes and not usable.

**Comment by BackOrder** [comment]
The font looks so good!

> It's noticeably slower when Shoes displays widgets or the file/folder dialogs.

Indeed. It's clearly loading file-by-file. Needs to update icon cache.

> It increases the nsis packaged file size by 90% from 13MB to 25MB. Qtifw installer increases by 12MB or so to 42MB

There are a whole lot of icons unnecessary. We already talked about icon sizes in issue #10. Those which we could safely remove would only amount to 733kb. Half of the file size is on `256x256` with a whooping 7mb.

On the other side, it does look better.

> `qtifw-Shoes-3.3.3-gtk3-w32.exe`

How about `Shoes-3.3.3-gtk3-w32-qtifw.exe` instead? It would be also nice to offer a portable installation (7z) version of Shoes.

> Themes might be a good candidate for those qtifw add-on components.

I like the idea but it would mean more maintenance for us. It would mean to write package code for each theme, upload to the server, etc. A cobbler version would allow to download, extract and install from gnome look website. It would even be possible to provide thumbnails.

By the way, I noticed widgets are indeed changed when trying new themes but not windows decoration. This only happens in Shoes. GTK 3 demo code does display the decoration properly.

![image](https://cloud.githubusercontent.com/assets/8844578/24204716/afb4c81e-0eef-11e7-89f7-5beaabecde87.png)

**Comment by ccoupe** [comment]
Their is a precomputed icon.cache included in the Adwaita  dir along with theme.index.
Shoes includes the gtk-update-icon-cache.exe so you can run and see if it makes a difference; note all the work needed in theme.index is you start removing things.

**Comment by BackOrder** [comment]
Tests reveal that removing icons do not result in speed increase. I had successfully removed `64x64`, `96x96` and `256x256`. Perhaps we should keep them, perhaps we shouldn't.

Running `gtk-update-icon-cache.exe` is not making any difference even with `--force --include-image-data` (97mb cache is produced). A simple gtk program that only opens a GTK File Chooser is also slow. This may mean something is not right. Also, it is slow on the first file open but not afterwards. There may be a way to cache icons/theme in Shoes.

Take note that the directory `shoes/share/icons/hicolor` has no content beside directories.

**Comment by ccoupe** [comment]
According to the internet ;-) gtk 3.14 changed some things in themes. Adwaita uses  a variant of css to build css which can be quite complex/lengthy - takes time to parse and draw and cache. Perhaps there needs to be more done than running the icon cache.

**Comment by BackOrder** [comment]
Where is the CSS you are talking about? There seems to be PNGs, SVGs, cursors but no CSS. Here are some links for CSS optimizers.

https://github.com/yui/yuicompressor
http://csstidy.sourceforge.net/

**Comment by ccoupe** [comment]
You have to know where to look - I haven't done it, and I didn't save the reference to where it is. Sigh.
Maybe helpful to understand https://blogs.gnome.org/mclasen/2014/06/13/a-new-default-theme-for-gtk/

**Comment by BackOrder** [comment]
https://github.com/GNOME/gtk/tree/master/gtk/theme/Adwaita

> Adwaita is a complex theme, so to keep it maintainable it's written and processed in SASS. The
generated CSS is then **transformed into a gresource file** during gtk build and used at runtime in a 
non-legible or editable form.

http://unix.stackexchange.com/questions/175385/where-may-i-find-a-reference-scheme-for-gnome-3-theming-e-g-adwaita

[How To Hack GNOME’s Adwaita GTK Theme](http://worldofgnome.org/how-to-hack-gnomes-adwaita-gtk-theme/)

**Comment by ccoupe** [comment]
It appears the css is compiled into the gtk libraries when gtk 3.1.4.15 was built. Many questions may be solved be looking at  /c/shoesdeps/src/gtk+-3.14.15/gtk/resources or wherever you put the src.  The win32 theme is there, we can probably figure out what icons are really needed.

**Comment by ccoupe** [comment]
I'm becoming convinced that the slow down is related to the icon.cache related. My little isp.rb script (in walkabout.mvmanila.com/public) creates a copy of para, edit_box, list_box and button that starts of filechooser.  The listbox needs an icon - wedge down,  With only hicolor copied it shows the broken image but speed is OK. Add the adwaita icons and the para's draw and after a pause the native widget appear. Click the button for the filechooser and it's fast. 

It's not secretly running the gtk-update-icon-cache.exe nor does it notice if you do but the pause is just about the same amount of time.

**Comment by BackOrder** [comment]
Well, you were right about Adwaita css files. They are huge. Possibly in 10K lines range in total or more. The win32 css are much smaller, roughly in 2K range.

It's likely that nobody notices on Linux because it loads when the window manager is started.

**Comment by ccoupe** [comment]
Many odd things. Why can't I generate a cache file on hicolor ? Because there are no icons, just directories! Xwin7 doesn't have any either in hicolor (an older gtk3). hicolor is 80MB on ubuntu and Adwaita is 1.9MB (just cursors). Reversed.  No help there. FWIW, the hicolor cache on ubuntu is 50MB! much larger than the msys2 adwaita cache. 

Clearly we need the Adwaita stuff for more modern gtk3 but  I do hate bloat.  I'll probably try building gkt 3.15 instead of 3.14 and see if anything gets better.

**Comment by ccoupe** [comment]
Well, the fun never ends.  gtk-3.15.12 an beyond drags in epoxy with drags in mesa and no options I can see to disable them. This not how one should debug a theme problem - also a warning about future problems that may limit Shoes 3.3 -plenty of trouble with Ruby 2.3 already.

**Comment by BackOrder** [comment]
> Why can't I generate a cache file on hicolor ? Because there are no icons, just directories! Xwin7 doesn't have any either in hicolor (an older gtk3). 

Indeed, I mentioned the empty directories.

> hicolor is 80MB on ubuntu and Adwaita is 1.9MB (just cursors). Reversed. No help there. FWIW, the hicolor cache on ubuntu is 50MB! much larger than the msys2 adwaita cache.

Hicolor cache is updated with `--include-image-data`. Adwaita with this option is 97MB.

Tests reveal updating icons cache with image data makes no difference. Maybe something is wrong with our gtk? Maybe it needs some tweaking or additional configuration options.

> RE: gtk-3.15.12 

Can Shoes get a break someday? Maybe `--disable-libepoxy` would work.

**Comment by ccoupe** [comment]
For the current gtk 3.6.9 deps (win7 and xwin7), I have discovered the secret to enabling the built in ms-theme **without** having to include bulky Adwaita icons.  The mere presence of a 'etc/gtk-3.0/settings.ini file like below seems to set the MS theme:
```
[Settings]
#gtk-theme-name=win32
#gtk-theme-name=ms-windows
```
Having looked at some of Gtk code, I think some of this magic is bug in gtk-3.6.9. Doesn't help the msys2 builds but those have many problems.

**Comment by ccoupe** [comment]
There is also very real chance that Gtk3 on Windows can load themes from AppData (per user, not per app). I see many benefits if this is true.

**Comment by ccoupe** [comment]
One problem with having the user download and switch themes is that Windows wants Admin rights to wrire into `Common Files (x86)`. Fortunately, Gtk has some not well known/documented  ways. 

If you create %USER%\%APPDATA%\Local\gtk-3\settings.ini  that it will override any previous setting found during initialization.  I tried it. It works. Now, we need a place to store the user  supplied/downloaded themes so GTK can find them and of course GTK has many options for doing that. I just need to find one that is user writeable - ~/.themes would be the fallback because dot files are visible in Windows.

**Comment by ccoupe** [comment]
Moved user themes to a a new issue #354
