### ISSUE TITLE
Click event not working when a scroll bar is scrolled down

### ISSUE THREAD

**Issue by BackOrder** [Shoes3/shoes3#35]
The click event is not working when there is a vertical scroll bar scrolled down (slightly or entirely). 

***TEST SCENARIOS***
**TEST (1)**
* Run the script below
* Open Shoes console (alt-/)
* Click anywhere in the window
* Check Shoes console

*EXPECTED RESULT* **the button number and coordinates displayed in Shoes console.**

**TEST (2)**
* Scroll down
* Click anywhere in the window
* Check Shoes console

*EXPECTED RESULT* **the button number and coordinates displayed in Shoes console.**

> *CURRENT RESULT* **nothing is displayed.** :heavy_exclamation_mark:

**TEST (3)**
* Scroll all way up
* Click anywhere in the window
* Check Shoes console

*EXPECTED RESULT* **the button number and coordinates displayed in Shoes console.**

```ruby
Shoes.app {
   click { |n, l, t| info "#{n}, (#{l}, #{t})" }
   (0..100).map { [*('A'..'Z')].sample(rand(25) + 1) }.each { |n|
      para n
   }
}
```

**Comment by BackOrder** [comment]
The following code snippet demonstrates that **keypress is not affected** by this issue.

```ruby
Shoes.app {
   keypress { |n| info "keypressed: #{n}" }
   (0..100).map { [*('A'..'Z')].sample(rand(25) + 1) }.each { |n|
      para n
   }
}
```

**Comment by BackOrder** [comment]
The problem may be related to #2 and shoes#42 considering that the clickable region seems to be limited to the window size. The text in bold shows the inner limit, anything clicked beyond that will not be caught by the click event.

```ruby
Shoes.app {
   click { |n, l, t| info "#{n}, (#{l}, #{t})" }
   (0..100).map { [*('A'..'Z')].sample(80) }.each_with_index { |n, i|
      para (i == 28 or i == 29) ? strong(n) : n
   }
}
```

**Comment by passenger94** [comment]
i think i have it
needs testing ...

**Comment by passenger94** [comment]
should be good now but lots of test won't hurt, please

**Comment by ccoupe** [comment]
Thanks. OSX behaves properly (enough - who really counts pixels ;^)
