### ISSUE TITLE
How to change a button's background?

### ISSUE THREAD

**Issue by spachner** [Shoes3/shoes3#353]
Hi,

Is there any possibility to change a button's background. I tried everything without success. I am running MacOS

regards

spachner

**Comment by ccoupe** [comment]
Hi. At the moment, this doesn't seem to be supported. I vaguely remember that this was discussed for the next release but wasn't 'settled' one way or the other.

**Comment by ccoupe** [comment]
@spachner - After poking around this doesn't appear to be possible, _cross platform._ You could create you're own button with a Shoes Widget - I believe others have done that.

**Comment by BackOrder** [comment]
The challenge might only be on the macOS side. GTK allows themes for which you did some work before @ccoupe.

**Comment by ccoupe** [comment]
Sorry @BackOrder . It's a problem on both platforms. Gtk deprecations old and new. And it works wonky.
No doubt OSX could style the NSButtonCell (painfull) but if Gtk can't do it, it's not going to happen.

**Comment by BackOrder** [comment]
Perhaps an alternative solution might be in order. I would like to recommend @spachner to use SVG to design his buttons. He can chose whatever shape, style and colours he would like.

**Comment by dredknight** [comment]
@ccoupe  @BackOrder  I saw the mailing list request and I got an idea about button with picture widget.
What do you think about this?

```Ruby
Shoes.app do

	def widget_button (img, action )
		img.hover { img.scale 1.25, 1.25 }
		img.leave { img.scale 0.8, 0.8 }
		img.click { public_send(action) }
	end
	
	def button1_action
		window(title: "button 1 action", width: 200, height: 200, resizable: false) { para "Button works" }
	end
	
	def button2_action
		alert "Button 2 action"
	end
	
	widget_button (image "#{DIR}/static/shoes-icon.png", left: 30, top: 30, width: 50), "button1_action"
	widget_button (image "#{DIR}/static/man-ele-image.png", left: 30, top: 120, width: 50), "button2_action"
	
end
```

**Comment by BackOrder** [comment]
@dredknight this is exactly what my suggestion is all about, though I had in mind SVG buttons rather than rasterized images. It's possible to add a pushed image too. Either way you got it right. One could create a button widget like your tooltip.

**Comment by dredknight** [comment]
hm.. the only reason I use images is cause I don't have a clue how SVG works. I gotta spend some time digging.

**Comment by BackOrder** [comment]
> hm.. the only reason I use images is cause I don't have a clue how SVG works. I gotta spend some time digging.

Both are actually fine. They both have their own advantages and disadvantages.

**Comment by ccoupe** [comment]
@dredknight , Nice! If the second the second arg to widget_button was a proc (along with code changes inside), you could do
```ruby
	widget_button (image "#{DIR}/static/shoes-icon.png", left: 30, top: 30, width: 50), {
           window(title: "button 1 action", width: 200, height: 200, resizable: false) { para "Button works" }
       }
```
Just like a real button. 
Either way, you should send that to the mailing list so Anna can finish her school project.

**Comment by BackOrder** [comment]
```ruby
Shoes.app do
    def woojet_button(img, &action)
        img.hover { img.scale 1.25, 1.25 }
        img.leave { img.scale 0.8, 0.8 }
        img.click { action.call if block_given? }
    end

    woojet_button(image "#{DIR}/static/shoes-icon.png", left: 30, top: 30, width: 50) do
        window(title: "button 1 action", width: 200, height: 200, resizable: false) { para "Button works" }
    end
    woojet_button(image "#{DIR}/static/man-ele-image.png", left: 30, top: 120, width: 50) do
        alert "Button 2 action"
    end
    woojet_button(image "#{DIR}/static/shoes-icon-red.png", left: 30, top: 210,  width: 50)
end
```

**Comment by dredknight** [comment]
@ccoupe @BackOrder thank you for elaborating. I cannot find what is **&action** exactly. I mean I see what it does and probably I can use it from now on but where I can read about what it is and how ruby handles those things? Google says & is used as "and" expression and nothing else.

**Comment by BackOrder** [comment]
The ampersand in Ruby means a block (either `do; end` or `{ }`). So here we are saying the method is expecting an optional (if block_given?) block as an argument. Hence is allows to construct in a Ruby natural way such as:

```ruby
button("hello") do
   para "hello world!"
end
```

This Shoes code snippet is in fact internally implemented using a &block. So the previous code I shared with you does exactly that for your custom button widget.

**Additional references:**
- [Mastering Ruby blocks in less than 5 minutes](https://mixandgo.com/blog/mastering-ruby-blocks-in-less-than-5-minutes)

**Comment by ccoupe** [comment]
This wonderful example is now at [the wiki](https://github.com/Shoes3/shoes3/wiki/Create-A-Button-with-Image)  Thanks.
