### ISSUE TITLE
Slot background does not cover scrolled space

### ISSUE THREAD

**Issue by dredknight** [Shoes3/shoes3#355]
I was messing with some slots today which should hold information with unspecific size.
Placed some background on the slot and added the scroll: true option but when it was executed and I tried to scroll down to see the full output it seems that the background wallpaper is some meters shorter than it should be. Basically I assume that the background size covers just the original slot size and not the resized one (post scrolling).

P.S. this is work on Shoes 3.3.2 R2759

Is there a way to make the background cover everything from top to bottom ?
```Ruby
Shoes.app(title: " v1.0", width: 500, height: 500, resizable: true ) do
	background green
	@main = stack left: 0.05, top: 0.15, width: 0.9, height: 0.8, scroll: true do
		background beige
		100.times do |i|
			para "#{i} times"
		end
	end
end
```

**Comment by ccoupe** [comment]
I'm not surprised. There are several similar open bugs going back many years with background and scroll bars. Your code manages to show at _least_ three bugs in Shoes Linux, maybe more so it's keeper!
* background (beige) doesn't know about changes in vertical  size
* background (beige) doesn't know to limit it's width when a scroll bar appears
* initial layout is not correct for the scrollbar - until resized manually.

The only possible work-around  I can think off would  involve refresh() or refresh_slot()  (name  depending on your version of Shoes). I don't have a lot of hope for that.

**Comment by dredknight** [comment]
Thank you @ccoupe !

I did try refresh_slot but I am not sure If I utilized refresh_slot properly. There is no example case in the manual and I did use what I could find here between the issues.
```Ruby
Shoes.app(title: " v1.0", width: 500, height: 500, resizable: true ) do
	background green
	@main = stack left: 0.05, top: 0.15, width: 300, height: 400, scroll: true do
		background beige
		100.times do |i|
			para "#{i} times"
		end
	end
	@main.refresh_slot()
end
```

**Comment by dredknight** [comment]
Alright, alright here is a workaround with ractangle

```Ruby
Shoes.app(title: " v1.0", width: 500, height: 500, resizable: true ) do
	background green
	@main = stack left: 0.05, top: 0.15, width: 0.9, height: 0.8, scroll: true, scroll_top: scroll_max do
		rect(left: 0, top: 0, curve: 10,  width: 0.5, height: 0.9, fill: rgb(245,245,220))
		100.times { |i| para "#{i} times" }
	end
	
	start { @main.contents[0].style width: 0.98*@main.width , height: @main.scroll_height }
end
```

There is one drawback though. If you try to resize the app the slot containing the elements will resize as well because it is set as **stack left: 0.05, top: 0.15, width: 0.9, height: 0.8**

However the rectangle will not resize because width is set to **width: 0.98*@main.width**
Is there a way to the element size to be set subjective toward the container when defined outside of it?
for example this row:
**@main.contents[0].style width: 0.98 , height: @main.scroll_height**

The width should automatically be set to 0.98 from the width of the **main** slot dynamically.

**Comment by dredknight** [comment]
P.S. actually I found a workaround I did use before.
Just put a stack with scroll over a stack with background so there is no need the background to be scrolled anymore.

I will leave this issue open for a day or two if anyone wants to add something.

**Comment by ccoupe** [comment]
I want to keep this open because the underlying problem is not fixed in Shoes.

**Comment by ccoupe** [comment]
If I'm reading the code correctly,  there are some fundamental issues.  Background is more like like Shapes (stars, circles) and a widget and does not know much about anything the outer slot contains or looks like.  It was never designed to work the way folks expect. Intention or oversight?  

Personally, I don't like it being a widget creature and in the contents list with other widgets in the slot.  BTW,  you get some other fun bugs if background is not the first widget in the slot.. In my ideal world background would be a property of a slot (a canvas in C). In Shoes Ruby it would be an argument to  flow and stack creation -` stack width:  200, background: yellow`.   

I need tosee  if/how  Shoes4 handles these bugs before putting in much more work on my solution.

**Comment by ccoupe** [comment]
Congratulations to @dredknight!  Shoes 4 has two different bugs!  Not everyone can find so many bugs in 10 lines of code.  Related issues #38 , #2. 

I Created a 'background' branch to experiment.  I make no guees when  this will be resolved. 3.3.3 if easy but I don't expect easy.

**Comment by dredknight** [comment]
I admit I am talented at finding bugs :D. Thank you for your efforts.

**Comment by ccoupe** [comment]
This was not too hard but it's not well tested (.e.g. osx, windows)  Here's is the bug355.rb code after a big scroll. 
![fix355-1](https://user-images.githubusercontent.com/222691/27774960-bb590e2c-5f59-11e7-8108-d02cd2aca72b.png)

I like it.  Background is still a widget/pattern so no changes to the Shoes scripts needed. The manual needs an update I supposed.

**Comment by ccoupe** [comment]
Turns out, the manual depends on the old behavior for backgrounds.

**Comment by dredknight** [comment]
This looks marvelous! 

This means the existing guide is valid for the new implementation?

**Comment by ccoupe** [comment]
Actually the new behavior breaks the manul so the neither this issue of #38 is fixed.

**Comment by ccoupe** [comment]
Having looked at what the manual does I can see how my simplified hack failed.  I found a clue on how do tho what you want in **current** Shoes.  In the original bug way above (bugs/bug355.rb) replace the stack creation so it looks like this:
```ruby
    #@main = stack left: 0.05, top: 0.15, width: 0.9, height: 0.8, scroll: true do
    @main = stack margin_left: 10, margin_top: 10, margin_bottom: 20, margin_right: gutter do
```
Try it. I works here.  Changing the internal behavior of background as I attempted to do broke too many existing things and we have a Shoes way already I'm going with the old way.

**Comment by dredknight** [comment]
Thank you @ccoupe it works!
The code behind my simple app is a bit more complex though also I have a couple of other fields in that background so I left the previous workaround with using a background slot for colour while all other stuff a colourless above it.
![image](https://user-images.githubusercontent.com/12410314/27932864-f5d5ec54-62a7-11e7-9642-ddec35bbad27.png)

The list with elements that is shared through scroll is done on the go. In code language it looks like this:
First an empty slot with scroll capability is created and then elements are added depending on filter.
```Ruby
@q = stack left: 20, top: 75, width: 420, height: 400, scroll: true;
list_array.each do |f|
    @q.append do
             para f
      end
end
```

The weird thing that happened with it was initialized is that the scroll bar appeared randomly with inappropriate size. If the user moves the scroll it goes in place with the appropriate size just as on the previous pic. A code I use to fix this is adding a start line to auto-move it after itialisaton.
```Ruby
start { @q.scroll_top = 1 }
```
![image](https://user-images.githubusercontent.com/12410314/27933171-05e4edec-62a9-11e7-83cc-f11182fd18e1.png)

I believe this happens because the scroll is drawn at slot creation (when it is empty which explains the positioning and the size is probably the default smallest size) and redrawn any time it is utilized by the user or the code.

I dont need any fix for this just saying for the sake of Shoes :).
Thanks for the help really appreciated!

**Comment by ccoupe** [comment]
Shoes can be very mysterious about when things get drawn . The misplaced scroll bar happens to me to and when I went the margin_right: gutter and delete the scroll: true on the slot creation.

**Comment by ccoupe** [comment]
Actually, the code using gutter is still flawed, as you've discovered. Since there is lots of existing code that depends on the current background behavior I think I'll try adding  a new Style. Perhaps `background green, expandable: true` I'm not wed to 'exandable`. Perhaps @backorder will help?

**Comment by ccoupe** [comment]
I believe I have a backwards compatible solution. background can accept a scroll: true argument 
```ruby
Shoes.app(title: " v1.0", width: 300, height: 500, resizable: true ) do
    background green
    @main = stack left: 0.05, top: 0.15, width: 0.9, height: 0.8, scroll: true do
        background beige, scroll: true
        100.times do |i|
            para "#{i+1} times"
        end
    end
end
```
'expandable' was clumsy and 's_scroll` was already defined in the C.  Since this  doesn't affect existing scripts use of background it's safe to add.

**Comment by dredknight** [comment]
Seems legit and somehow intuitive that you want the background to be "scrolled". Good job :)
