### ISSUE TITLE
"Download" options are not documented?

### ISSUE THREAD

**Issue by dredknight** [Shoes3/shoes3#358]
Hello once again :).

I've been messing with some download stuff in shoes as I want to make a cloud-like addons on demand.
So the thing I am building will download some files and manage them automatically.

**Download** method is pretty straight forward but in the docs it is mentioned it has some optional styling which I could not find anywhere.
For example the guide says you can do this:

download url, save: my_file_path

Which works and is totally cool. But there are some stuff that are mentioned without any examples. For example:

> Each download thread also fires **start, progress** and **finish** events.

How do I use them? Lets say that I want a progress bar to be loading while a file is being downloaded?
Also I feel that there are a couple of other important things that are not explained.

```Ruby
Shoes::Download.instance_methods 
```
returns other stuff like - _:gui, :transfered, :percent, :start_download, :finish_download, :length_ and a bunch more.

Can anyone shed some light over this or at least share a good example of those methods?
I dont mind making some docs for the guide later :).

**Comment by ccoupe** [comment]
There are some samples/simple/simple-download.rb uses those args and simple-download1.rb dissects the http header.

**Comment by ccoupe** [comment]
You also have the download.rb in your lib/shoes/  directory to study.

**Comment by dredknight** [comment]
I did check download.rb but was kind of confused.

Thanks for the samples note, I always forget about them.

I cannot understand why this does not work though it is quite similar to download_simple.rb
```Ruby
Shoes.app do
	@p = progress width: 200
	button("Download", left: 0, top: 100) do
		download "http://ipv4.download.thinkbroadband.com/50MB.zip", save: "test_t.pak", progress: proc { |dl| p.fraction = dl.percent }
	end
end
```
The url is test http download page where you can download files of different sizes.
There is some magic I kind of do not understand here...

**Comment by dredknight** [comment]
I made the download thing.
it seems that the link the app was accessing was sending back a temporary link that I had to use to get the download. It seems this is a commodity these days but I have never ditched into the HTTP request thing before.

Thanks for the help @ccoupe now looking at it Shoes support all a dev needs to know it is just you need to know more than what shoes offer.

Cheers

**Comment by ccoupe** [comment]
Was it a http -> https redirect? Shoes 3.3.3 has a fix for that and yes it is very common.

**Comment by dredknight** [comment]
Yes, this is it.

Here you are a working sample :).
```Ruby
require 'net/https'
require 'uri'

Shoes.app do

	def dl_button slot, text, url, state = nil
		button(text, left: 310, top: 0, width: 100, state: state) do
			slot.append { progress left: 313, top: 33, width: 92, height: 3 }
			uri = URI.parse(url)
			debug("uri is #{uri}")
			http = Net::HTTP.new(uri.host, uri.port)
			debug("http is #{http}")
			http.use_ssl = true
			debug("http is #{http}")
			http.verify_mode = OpenSSL::SSL::VERIFY_NONE
			debug("http is #{http}")
			request = Net::HTTP::Get.new(uri.request_uri)
			debug("request is #{request}")
			resp = http.request(request)
			debug("resp is #{resp}")
			real_url = http.request(request)['location']
			debug("real_url is #{real_url}")
			download real_url, save: "qqqq.pak", progress: proc { |dl| slot.contents[1].fraction = dl.percent }
		end
	end

	@URL='https://www.dropbox.com/s/hbudjsf84jn1nfy/Legacy%20pack?dl=1'
	@my_stack = stack do
		background yellow
	end
	dl_button @my_stack, "download things", @URL

end
```

**Comment by dredknight** [comment]
FYI, I just got on this one. It seems all one need to know has nothing in common with Shoes.
What you need is the Ruby class HTTP -> https://ruby-doc.org/stdlib-2.4.1/libdoc/net/http/rdoc/Net/HTTP.html

Everything one need to know to practice the darks arts of getting static and redirected URLs is there.

Cheers.

**Comment by ccoupe** [comment]
This being redone it shoes 3.3.4 - Net/http is slow on windows. SSL doesn't work on Windows - lot's and lots of bugs and annoyances. Yesterday  I did get a https hack that works (so far - branch rb23). The better solution is libcurl and the Typhoeus gem - works for some Shoes (Windows, x86_64-linux) but not for the others. Odd linker based issue i think.   When that is done the manual really does not and big change

**Comment by dredknight** [comment]
So basically you change the backend. From user perspective the code will remain the same?

**Comment by BackOrder** [comment]
> So basically you change the backend. From user perspective the code will remain the same?

Yes, `download` is part of Shoes API. It somehow makes sense when you think about it because it provides a way to download things without having to learn external library and it is integrated to a visual component (i.e., progress). Notice Shoes is self contained in a way that normal programming doesn't need any `require`.

**Comment by ccoupe** [comment]
download will stay the same - for most things (99%). When you need some thing clever like a http put or passwords then you'd call the typhoeus api instead of net/http or open_uri.  Why 99% certainty - the old code couldn't handle a puts like the manual say. I'd have heard about that bug before now.
