### ISSUE TITLE
Language thing.

### ISSUE THREAD

**Issue by dredknight** [Shoes3/shoes3#360]
I was asked why Polish special chars are not shown in Shoes -  ę , ą , ż, ź , ł , ó , ć.
This is a font thing but how should I know which font will support those letters?

**Comment by ccoupe** [comment]
If it's Windows that you're dealing with then you need to find out what truetype font that they are using in other applications that display properly. Shoes has/had a user in Serbia or Croatia which some 'unique' glyphs and they displayed. Shoes loads all the fonts on a users system  (if it can load it). It needs to be UTF-8 compatible.  Beware: if the strings are in a sqlite3 DB that some sqlites3 may  not support utf-8. (see the commented line in samples/simple/simple-sqlite3.rb

**Comment by ccoupe** [comment]
I decided to see what was wrong with samples/simple/simple-sqlite3.rb - For some reason, it thinks the
script uses US-ASCII encoding - the Shoes error console message is pretty clear, so ask your Polish user to check their console for error messages.  In the case of the simple-sqlite3.rb inserting this as line number one works. It might be something you need to do for your scripts. You shouldn't have too but ? 
```ruby 
# encoding: utf-8
```

**Comment by dredknight** [comment]
@ccoupe what the Polish guy is doing is opening a txt file that is presented as a text in shoes and translating the English text to Polish. The file is already UTF8 because I made them so. Basically whenever he translates a file all the text is presented in Shoes except the glyphs. In this case I believe it is a font issue.

I will do some iterations with other fonts and let you know.

Cheers

**Comment by ccoupe** [comment]
> What is the command to get the font for Shoes::Subtitle?

I believe subtilte just uses the 'current' font with different point size, weighting/ style. 

>Also the Polish text that is not working on his side is working on my side.

Remote debugging is fun ;-)

>I am utilizing Shoes 3.3.3 r2921 while the app he is using is utilizing the latest stable version (3.3.2)

I don't _think_ any thing done in 3.3.3  would have changed font handling. I am aware of a private company, proprietary  Shoes app that does language translation with fair number of users so it can be done.

**Comment by dredknight** [comment]
> I don't think any thing done in 3.3.3 would have changed font handling. I am aware of a private company, proprietary Shoes app that does language translation with fair number of users so it can be done. 

This is great that Shoes is used for production!

Anyways, I did some minor edits in the skillwheel app and now it can supports multiple language translations. I am waiting for the Polish guy to translate some 2000 files and I will test  english vs polish on my side.

Also the Shoes wheel app just passed 1800 downloads :D.

**Comment by dredknight** [comment]
Closing this one. So far no issues in translations.
