### ISSUE TITLE
System Tray

### ISSUE THREAD

**Issue by ccoupe** [Shoes3/shoes3#363]
via https://github.com/shoes/shoes/issues/285

see https://docs.oracle.com/javase/tutorial/uiswing/misc/systemtray.html

Currently I have no idea if or how Shoes can do this cross platform.
[For Gtk](https://developer.gnome.org/gtk3/stable/GtkStatusIcon.html ) and note the deprecation in 3.14

This is a more Shoes Amenable [gtk class](https://developer.gnome.org/gio/stable/GNotification.html)

**Comment by ccoupe** [comment]
OSX - [Start here](https://support.apple.com/en-us/HT204079) . There will be an api somewhere. 
[Like ](http://cocoathings.blogspot.com/2013/01/introduction-to-user-notifications-in.html
)
They seem similar enough so there could be a Shoes LCD  way, there are Shoes design issues to think through. Shoes needs a widget/class to attach it's callback/blocks and configure manipulate and **not** be a Shoes GUI widget with a canvas.  

For example, we could create a NotifyOS  non gui class ( like SvgHandle is). Perhaps we could move some of those Shoes.app.methods like fullscreen or set_app_icon into that class (or ancestor class). I'm starting to really like this idea although it's huge amount of work.

**Comment by ccoupe** [comment]
As expected, unification of the two apis Cocoa and Gtk is going to result in a skinny set of features - No replies so there's no need to deal with buttons in notifications. Title, subtitle, icon/image would be the only arguments. Something like
```ruby
  OsNotify.new("My Bot", "responded to a tweet",   "#{DIR}/images/done.png")
```
Is that useful?  Could be, I guess. Opinions?

It could be paired with an alert or confirm to be more useful for some designs:
```ruby
  OsNotify.new("Long Running Solver", "needs your attention")
  if confirm("continue solution generation"
     find_solution
  else
    clean_up
   Shoes.quit
end
```
That would be suspend the Shoes gui threads until you get it front and center and deal with the dialog.  Is that sufficient? 

FWIW,  more advanced notification things require that Shoes implement/become a GApplication (linux, windows) which is a big deal and would probably require using Gtk3 on OSX. If possible.

**Comment by BackOrder** [comment]
The proposed API doesn't feel Shoes-like, especially using it with new keyword. `osnotify` is descriptive but not great. Notification/Tray is actually considered a GUI component as it includes a visual representation of itself. Other than that, adding the feature seems like a good idea.

What do you think of `systray` ?

```ruby
   systray("Long Running Solver", "needs your attention") # ordered parameters
   systray title: "Long Running Solver", notification: "needs your attention"
```

**Comment by ccoupe** [comment]
> What do you think of systray ?

systray is fine with me and it is more Shoes like even though there will not be a Shoes visible GUI widget to back it - it's really just a message to the desktop manager - function call if you will. Thanks for the feedback. It's a good opportunity for me to really work with our/your refactoring of the C code.

**Comment by ccoupe** [comment]
Sadly, I missed [seeing](https://developer.gnome.org/gio/stable/GNotification.html#g-notification). So, my simple scheme isn't going to work. GApplication (or GtkApplication) is not something Shoes is written to deal with. Implementing GtkApplication is a big deal. It affects main loop and  command line handling, ruby init changes, quite possibly packaging changes.  **A lot of work**.  There's probably some other downsides I haven't thought of. 

On the positive side of GtkApplication is systray, obviously, but also dbus compatiblty (for linux), better control of gtk resources (like themes). We also get something to hang menus on, if we had them. Because of the code changes to main.c.//world.c/app.c/shoes.rb then we might as well just use the Gtk3 for OSX and dump cocoa.m.

**Comment by ccoupe** [comment]
As I often the case, things could be a little easier that I expected.  On branch systray, replace gtk_init ()  in shoes/native/gtk.c (shoe_native_init) with a call to gtk_application_new and setup a a call back for the 'activate' signal.    systray is working (linux) and so far other Shoes things appear normal.

Windows however is complaing with a could of gtk errors and a crash when running the systray test.

**Comment by ccoupe** [comment]
The windows problem with calling 'gtk_application_new' is that it ignores the given argc/argv and and re-reads the windows command line args (from cshoes.exe) - [documented](https://developer.gnome.org/gio/stable/GApplication.html#g-application-run).  The proper fix requires work and understanding and should be done. 

That said, there is a workaround for Windows - the deprecated in Gtk 3.14 [GtkStatusIcon](https://developer.gnome.org/gtk3/stable/GtkStatusIcon.html). It does work - Windows systray is not as  clever as GNotification or Cocoa. but it works!

**Comment by ccoupe** [comment]
Shoes Windows beta [3.3.4 with systray ](https://walkabout.mvmanila.com/public/shoes/shoes-3.3.4-gtk3-32.exe)

**Comment by BackOrder** [comment]
What do you think of the new approach for implementing types/native widgets so far?

**Comment by ccoupe** [comment]
> What do you think of the new approach for implementing types/native widgets so far?

I like it know that rake file is more intelligent about what to compile.

**Comment by ccoupe** [comment]
There's a Shoes [3.3.4 beta ](https://walkabout.mvmanila.com/public/shoes)
