### ISSUE TITLE
Can I get progress bar for any step my shoes make?

### ISSUE THREAD

**Issue by dredknight** [Shoes3/shoes3#364]
Hey everyone,
 
      I am building small app that will have cloud-like capability. In few words all the content will be stored online in the form of archived packages which will be downloaded on demand. For the operation visuals I do use progress and it works fine:
```Ruby
download real_url, save: "download_target", progress: proc { |dl| progress_slot.fraction = dl.percent }
```

I wonder if progress can be attached to any operation? For example extracting archives? Can I do something like this:
```Ruby
extract_zip( "file.zip","destination"), progress: proc { |arch_progress| progress_slot.fraction = arch_progress.percent }
```

Lets say a task require a couple of different operations to complete. Is it possible to build progress to follow the advancement of all the parts of the task. In the current example I want:
- to download a file
- extract all of its contents
- rearrange some of the files to specific place

Can I make all those tasks work under one progress hood?

**Comment by BackOrder** [comment]
Obviously you can! Three tasks? 100% / 3 = 33.3%. The progress bar goes from 0 to 1, so it would mean each task gets up to 0.33 value where 0.33 means the task is 100% completed.

**Comment by dredknight** [comment]
ah.. sure I think I was going for a bit too sophisticated method where each task was actually reporting progress just like the DL but the power of the progress was divided by 3.  So each part contributes in real time for 0-33%,34%-66% and 67%-100%. But having a second thought it is not required a at all.

Thanks for helping me with my overly complicated mind.

**Comment by BackOrder** [comment]
>  So each part contributes in real time for 0-33%,34%-66% and 67%-100%.
> Thanks for helping me with my overly complicated mind. ;)

It's even more simple than that. You can use the existing value in the progress bar and add to it. So all your current task has to care about is its own range (0 to 0.33, or **0 to 1 divided by the number of tasks** if you want something that can support adding or subtracting tasks).

By the way, I put a bounty on issue #79 if you are ever bored.

Best of luck!

**Comment by dredknight** [comment]
hm... there is just one thing that I dont think is possible though. Following the real time progress of some operations. For example **extract_zip**.  I cannot entitle it with :progress like you can do with **download**.

The 79 issue seems awesome, I am a fan of automation and try to include wherever is reasonably possible. I will see if I can tackle it.

**Comment by BackOrder** [comment]
> For example extract_zip. I cannot entitle it with :progress like you can do with download.

Which library are you using? It may or may not support progress. Worst case scenario? You have 0 and 1 (extracted). There is very likely to be a block you can pass to your extract method where you can tackle bytes extracted, progress or whatnot.

> The 79 issue seems awesome, I am a fan of automation and try to include wherever is reasonably possible. I will see if I can tackle it.

The backporting itself and some of the specs should be fairly easy.

> P.S. hahahaha I just saw the bounty thing is actually real. What an awesome idea!

Thanks. Yes, it's absolutely real. Bounty source holds the money until the bounty is fulfilled, so it's already paid, and then transfer it to the bounty hunter who accomplished the task. I recently saw that on a couple of other projects and also thought it is awesome.

**Comment by BackOrder** [comment]
> require 'zip' - this is zip 2.0.2 gem

Possible. According to https://github.com/rubyzip/rubyzip (see below) you have access to a list of files in an array for which you will know the size. You could use a counter divided by the number of files to establish the progress fraction. Let's say there are 5 files, it would go like this ~ 0/5, 1/5, 2/5, 3/5, 4/5, 5/5. The latter 5/5 gets you to 1. 

**Reading a Zip file**
```ruby
Zip::File.open('foo.zip') do |zip_file|
  # Handle entries one by one
  zip_file.each do |entry|
    # Extract to file/directory/symlink
    puts "Extracting #{entry.name}"
    entry.extract(dest_file)

    # Read into memory
    content = entry.get_input_stream.read
  end

  # Find specific entry
  entry = zip_file.glob('*.csv').first
  puts entry.get_input_stream.read
end
```

**Comment by ccoupe** [comment]
Rubygems has a gzip/unzip inside that is callable by shoes - I do it installing gems from cobbler.  If I remember it has something that could be used to drive progress If you know what the total is - number of files for example.

**Comment by dredknight** [comment]
Thanks all :) Closing this one.
