### ISSUE TITLE
Shoes and threads?

### ISSUE THREAD

**Issue by dredknight** [Shoes3/shoes3#367]
Hello Guys I am trying to do an HTTPS request and while doing that the user to see the Spinner.

How it works

The user clicks a button the spinner starts rolling.
Then the http operations are started, the text is read and put into file.  
Check the block below. When it is executed the spinner starts rolling when all http operations finish.
Here is how the code looks like:

```Ruby
button("download some file") do
	@text_slot.clear do			
		spinner left: 113, top: 90, start: true, tooltip: "waiting for something?"
	end
	new_text = launch_http_operations @url
	File.open('some file', "w") do |f|
		f.write new_text 
	end
end
```
I tried using **thread** but it seems it doesn't work either. 

```Ruby
button("download some file") do
	@pack_contain.clear do			
		threads << Thread.new { spinner left: 113, top: 90, start: true, tooltip: "waiting for something?" }
	end
	new_text = launch_http_operations @url
	File.open('some file', "w") do |f|
		f.write new_text 
	end
end
```

I have the feeling that it is happening because of how GTK draws block. It do the whole block and only when the whole code is executed it applies the changes.

**Comment by dredknight** [comment]
Alright, following the GTK drawing logic I found a way!

First when you click the button draw everything that should be instantly drawn.
Everything else that will be pending later put into a thread, where at the end of the thread the spinner.stop is called.
```Ruby
button "my button" do
				@pack_contain.clear { @s = spinner left: 113, top: 90, start: true, tooltip: "waiting for something?" }
				Thread.new do
					new_text = launch_http_operations @url
					File.open('some file', "w") do |f|
		                               f.write new_text 
	                                end
                                        @s.stop
                                 end
end
```

**Comment by BackOrder** [comment]
Dealing with threads in Shoes is a challenge because Ruby (MRI/YARV) comes with GIL. Basically, it runs one thread at a time. This is not exactly GUI friendly. Shoes is the one tying GTK and Ruby together, which means they have their own separate threads. Some things might work (like you just did) while other things might not be so friendly (Windows didn't like my combination of Typheous/CURL and progress).

We should have a programming tips page on the Wiki. Such as what you just came up with and the famous `start` block. Don't forget to close this issue if no further action is needed.

**Comment by BackOrder** [comment]
Oh, forgot to mention that full thread support (without GIL) is planned for Ruby 3.x... somewhere around 2020. Don't hold your breath. haha

**Comment by dredknight** [comment]
Hahaha, thanks for the information. I did try to put both - the spinner and the other stuff in their own threads but then Shoes started to crash.

Border line all shoes drawings should remain in shoes - other tasks are safe to be in thread.

**Comment by dredknight** [comment]
Found a way to draw GTK inside a thread. What you should do is add the drawing in a start {}. I assume that start {} launches a Shoes native thread. This way you escape the external thread messing with the drawing.
```Ruby
Thread.new do
						@custom_ncf_package.each_with_index do |ncf, i|																				####### Iterate over all currentely chosen creatures and install them
							FileUtils.copy_file "NCF_repository/packs/#{folder}/NCF_#{ncf}.pak", "../data/NCF_#{ncf}.pak"
							FileUtils.copy_file "NCF_repository/packs/#{folder}/Icons/Creature_#{ncf}.dds", "../Complete/icons/Creature_#{ncf}.dds"
							@bar.fraction = ((i+1).to_f/@custom_ncf_package.count).round(2)
						end
						start { alert("Installation complete", title: nil); }
					end
```
