### ISSUE TITLE
visit is not working

### ISSUE THREAD

**Issue by BackOrder** [Shoes3/shoes3#37]
The Shoes Manual on page **Furthermore > Internet** contains links to Shoes github, blogs, mailing list, etc. The code in https://github.com/Shoes3/shoes3/blob/master/lib/shoes/help.rb uses **visit** to open a web browser on the given URL. ***This doesn't work on Windows but does work on MacOS X.***

Also, The Shoes Manual stipulates that visit is intended to load Shoes application rather than web pages.

> **visit(url: a string)**
> Changes the location, in order to view a different Shoes URL.
>
> Absolute URLs (such as http://google.com) are okay, but Shoes will be expecting a Shoes application to be at that address. (So, google.com won't work, as it's an HTML app.)

**Comment by BackOrder** [comment]
A multiplatform alternative for visit. Works on Windows and MacOS X but need testing on Linux.

```ruby
def open_url(url)
  if RbConfig::CONFIG['host_os'] =~ /mswin|mingw|cygwin/
    system("start #{url}")
  elsif RbConfig::CONFIG['host_os'] =~ /darwin/
    system("open #{url}")
  elsif RbConfig::CONFIG['host_os'] =~ /linux|bsd/
    system("xdg-open #{url}")
  end
end
```

**Comment by ccoupe** [comment]
xdg-open works. Thanks for reminding me about it.

**Comment by BackOrder** [comment]
```ruby
Shoes.app {
   visit("http://www.numinoes.com/")
}
```

Running with cshoes.exe yields in:
> Le chemin d'accès spécifié est introuvable.

Meaning **Path not found.**

**Comment by passenger94** [comment]
visit and xdg-open both works on Linux Ubuntu

**Comment by ccoupe** [comment]
Assigning milestone 3.2.21.
