### ISSUE TITLE
using Shoes and database?

### ISSUE THREAD

**Issue by dredknight** [Shoes3/shoes3#371]
Hello once again :),

If you have ditched around my app you will see that the architecture of the data is gathered in txt files in"design" folder. I was wondering if this information cannot be thrown into a database instead of being kept into files. User experience will not change but I assume performance will increase a bit.

I have experience with maraDB and MySQL but only used them through CLI or GUI interface so my vision about how I use code to control the DB is unclear and when it comes to shoes it is clearly muddy.

I see that by default shoes has sqlite3 gems which I assume is light version of mysql?
So what I ask is 3 things:
- Does it worth it to make the migration ?
- Can I rely on how Shoes and sqlite3 work?
- Any example place where I can begin studding ?

Straight out the bat I found [this tutorial I am going to try](http://zetcode.com/db/sqliteruby/). If you have any better ideas or propositions you know I am on :).

**Comment by BackOrder** [comment]
> Does it worth it to make the migration ?

Yes. I'm using SQLite for several years on small scale projects and prototypes with changing requirements. It is drastically simpler to setup, use and admin than MySQL or PostgreSQL.

> Can I rely on how Shoes and sqlite3 work?

Yes, SQLite3 has been around for a long time providing embedded database for local database (not client-server). It's basically lightweight and one of the most popular database engine ever. It's been used in many well known projects including, most likely, your very own web browser.

As anything else in computing, if you are afraid of data corruption, you should do backups.

> Any example place where I can begin studding ?

https://github.com/sparklemotion/sqlite3-ruby

**Comment by dredknight** [comment]
After looking at it for a few moments I think it works the same as normal client-server database with the following differences.

- DB processes run only when app is running

Also when it comes to how data is handled in comparison to my current model I will have to make a script that parse the current data from files to the DB. Than I have to save the db to a file.

When it comes to the app it will load the already existing DB and read from it to populate the panes the user is clicking on.

@BackOrder  thanks!

**Comment by BackOrder** [comment]
You are welcome! You are on the right track. A one-time conversion script will transfer data into your SQLite database and then all subsequent work will be in SQLite. **PRO tip:** sqlite3 command line might come handy at times, especially for admin tasks or exploring freely your database, it's worth learning.

**Comment by dredknight** [comment]
This is true. Btw I managed to migrate all my data into the sql so now 1.5MB of files shrinked to less than 100kbs which is awesome :).

While tailoring the application to the DB I bumped into a behaviour I did not expected.
Here is an example of what I mean:
```Ruby
classes = read_skills "design/factions/#{item}.txt"
debug(classes)
```
This returns array of three elements as follows -> [ one, two, three]
Now I want to move the query from the files to the DB tables sa follows:
```Ruby
classes = DB.execute( "select name from classes where faction = '#{item}'" )
```
This fetches three rows from the table and puts it in classes just as the previous example with the difference that each row is put in a separate array so the output is -> [ [one], [two], [three]]

I assume this is default behavior but can I go around it? or is it better to use the new behaviour?

**Comment by BackOrder** [comment]
How about you use sqlite3 command line and take a look at the data inside? They may have been improperly filed in or wrong type or such.

**Comment by dredknight** [comment]
I am not sure I understand what do you mean by wrong type or improperly filled.
Basically the db is something like this:
id  name(string)
0    one        
1    two
2    three
3    four

there is a column that I use for filter so I get one two and three. 
Do you want to say that while migrating I may have inserted an array of one string element instead of just string?

**Comment by BackOrder** [comment]
Basically or exactly?

Could you share your table definition?

**Comment by dredknight** [comment]
This is how I made it along with the parser. You can see what is inside from the picture below:

############ create table with classes list, primary stats and secondary skills
	 db.execute <<-SQL
	  create table classes (
		id varchar(2),
		name string,
		primary_s string,
		secondary_s string,
		heroes string,
		faction string
	  );
	SQL
	count = 0
	Dir.glob("design/factions/**/*").reject{ |rj| File.directory?(rj) }.each do |fn|
		file_name = fn.split("/")[-1].split('.')[0]
		(read_skills fn).each do |n| 
			primary = read_skills "design/classes/#{n}/primary.txt"
			secondary = read_skills "design/classes/#{n}/secondary.txt"
			heroes = read_skills "design/classes/#{n}/heroes.txt"
			db.execute "insert into classes values (?, ?, ?, ?, ?, ?)", count, n, primary.join(","), secondary.join(","), heroes.join(","), file_name
			count+=1
		end
	end

![image](https://user-images.githubusercontent.com/12410314/30781861-8039ab22-a12f-11e7-8670-13f096f10500.png)

Here is an example query I make:
classes = DB.execute( "select name from classes where faction = 'sylvan'" )

**Comment by BackOrder** [comment]
Perhaps you should send me your database and a code snippet how you read it. I will take a look.

**Comment by dredknight** [comment]
[Here is the db](https://drive.google.com/file/d/0B7vvjKq9ScRUSG1qcmdqZWhuRjQ/view?usp=sharing).
it resides in the same folder as the script. Here is a reading sample that shows the issue:
```Ruby
require 'sqlite3'
Shoes.app do
        DB = SQLite3::Database.new "skillwheel.db"
        classes = DB.execute( "select name from classes where faction = 'sylvan'" )
        debug(classes)
end
```

**Comment by dredknight** [comment]
Alright I found out what is going out. It seems that this is the default behavior of the query.
It returns array (the result) of arrays (each row in the result).

Take a look at this nifty [article ](http://ruby.bastardsbook.com/chapters/sql/).

It is quite long so search for "Each entry in the array is itself an array," paragraph.

**Comment by BackOrder** [comment]
Great find. I was busy with resizing feature. Got something working but it only allows to resize up but not down from the initial window size.

**Comment by dredknight** [comment]
@BackOrder  SQLite is awesome :). 

The whole architecture is now in the DB while all texts and pics are outside. App works just marvelously fast compared to what it was before.
Also because of the DB a lot of the parsers were included in the migration script so they are no longer needed in the app code which shrunk by ~10%.

Thank you for all advice :)

**Comment by BackOrder** [comment]
@dredknight I'm very happy for you! :)
