### ISSUE TITLE
Programmatically enable/disable resizable

### ISSUE THREAD

**Issue by BackOrder** [Shoes3/shoes3#372]
This feature allows to programmatically change resizable passed down to Shoes.app (or a window). There is still some work to do because while the feature fully works, setting resizable to false will unfortunately resize the window back to its default. Hence, it has been committed to a remote branch.

![image](https://user-images.githubusercontent.com/8844578/31048454-36e62f0c-a5eb-11e7-84b7-37ce25ae290f.png)

![image](https://user-images.githubusercontent.com/8844578/31048459-4f681662-a5eb-11e7-8ac2-44a614af8aac.png)

```ruby
Shoes.app(width: 250, height: 100, resizable: false) do
    @p = para
    flow do
        button("enable") do
            app.resizable = true
        end
        button("disable") do
            app.resizable = false
        end
    end
    animate do
        @p.replace "resizable #{app.resizable}"
    end
end
```

Additional references:
- https://github.com/BackOrder/shoes3/tree/resizable
- Issue #370: unable to resize when resizable = false
- Issue #370: unable to resize smaller than default window size

**Comment by ccoupe** [comment]
Oops, this the issue to talk about what's happening on older Gtk3.  After executing line 754 of gtk.c
```C
gtk_window_resize(GTK_WINDOW(app->os.window), app->width, app->height);
```
Is when the 
```txt
(shoes:21292): Gtk-WARNING **: Toplevel size doesn't seem to directly depend on the size of the geometry widget from gtk_window_set_geometry_hints(). The geometry widget might not be in the window, or it might not be packed into the window appropriately
```
occurs - the code to call `gtk_window_set_geometry_hints` was executed.  There we also many
warnings from the compiler in this section of the code so those all need looking at.

**Comment by BackOrder** [comment]
Are you in sync with the repo? There only place there is `gtk_window_resize` in [shoes_native_app_resize_window](https://github.com/Shoes3/shoes3/blob/master/shoes/native/gtk.c#L667). `gtk_window_resize` is constrained by geometry.

The part I wrote ultimately went to use `gtk_widget_set_size_request`. Refer to [comment](https://github.com/Shoes3/shoes3/issues/370#issuecomment-333319735).

**Comment by BackOrder** [comment]
Woah. There was a huge bug on Github. It displayed a previous version of the code. Now it all uses `gtk_widget_set_size_request`. o_O

**Comment by ccoupe** [comment]
setting NULL instead of gk-window fixes the Gtk console warning - as you suggested.
`gtk_window_set_geometry_hints(GTK_WINDOW(gk->window), NULL,`

The compiler gtk3 deprecation warning are going to be trouble some.  I hate to ignore warning but we may have to.

**Comment by BackOrder** [comment]
> I hate to ignore warning but we may have to.

This [solution](https://github.com/budgie-desktop/budgie-desktop/commit/ff3d7c9c0fc17f4fb23c172f8c8874ab4a7d6602) in Vala makes me think that a simple dummy call to `gtk_widget_get_preferred_width/height()` at appropriate places in the code will resolve the warnings.

```
(<unknown>:77048): Gtk-WARNING **: Allocating size to GtkBox 0x812d81300 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
```

**Comment by ccoupe** [comment]
That one I do want to fix - it's very visible.  Finding the proper places is the challenge. I'm not going to get to it very soon so If you want to give it a try then go for it. `shoes -c` is good test.

I was talking about the compiler warnings: the deprecations with different versions of gtk3. Those are not as easy as I hoped.

**Comment by BackOrder** [comment]
This is a common problem when people moved to 3.20. There are so many hits on google but very little to none solutions.

You may want to take a look at [gtkwidget.c](https://github.com/GNOME/gtk/blob/master/gtk/gtkwidget.c) top comment. A lengthy informative comment related to geometry management.

It shouldn't be hard to find out: all widgets must check for preferred width and height. And a step-by-step debugging on `shoes -c` would probably show that. (Notice also splash screen doesn't output warnings because it has no widgets, only Shoes elements that are cairo based anyway).

**Comment by BackOrder** [comment]
I removed two lines in [gtk/gtkbuttonalt.c](https://github.com/Shoes3/shoes3/blob/master/shoes/native/gtk/gtkbuttonalt.c#L34) and let gtk use its own preferred width/height and it works. Not sure what the actual implications would be to that but `shoes -c` works without a hitch. Maybe buttons would have a minimal size a bit larger that what shoes normally had.

An attempt to use gtk_widget_get_preferred_width/height within the user functions gtk_button_alt_get_preferred_width/height caused a core dump. First, I tried similar to VALA code with the widget and some dummy &x, &y variables. Secondly, I tried with NULL per the documentation but it yielded in more warnings. Finally, I tried with the actual minimum and natural passed to the function but it core dumps.

**Comment by ccoupe** [comment]
Now merged to master branch. Osx behaves differently on the bugs/bug372.rb script:  After resizing and clicking disable the osx window stays at the new size which I think is better but it's such an edge case I'm not going to spend much thought about it.

**Comment by BackOrder** [comment]
This should be the expected behaviour. I think GTK is being naughty on this one.
