### ISSUE TITLE
Can not see the list of architectures

### ISSUE THREAD

**Issue by CaptainPhilipp** [Shoes3/shoes3#378]
So i tried to package app, and i need to choose some architecture,
but i see [only that (nothing)](https://github.com/CaptainPhilipp/rom_experiments/blob/master/2017-10-26_23-07-15.png?raw=true)

Why is the list of architectures empty? How can i fix that?

`walkabout 3.3.3 r2994`
fit `TIGHT_SHOES`

**Comment by ccoupe** [comment]
It needs an online connection (or the server script is failing). It seems to be a server problem. I'll look into it.

**Comment by BackOrder** [comment]
It seems to be affecting FreeBSD as well.

Opening **Shoes Console** (`alt-/`) displays the following error when Shoes Packager is opened: 

```ruby
Error in <unknown> line 0 | 2017-10-26 16:16:24 -0400
control can't have :state of enabled

```

Cand you open Shoes Console and see what you got in there?

**Comment by CaptainPhilipp** [comment]
In console i see only that:
```
Warn in <unknown> line 0 | 2017-10-26 23:22:11 +0300
Ignoring byebug-8.2.1 because its extensions are not built.  Try: gem pristine byebug --version 8.2.1

Warn in <unknown> line 0 | 2017-10-26 23:22:11 +0300
Ignoring chipmunk-6.1.3.4 because its extensions are not built.  Try: gem pristine chipmunk --version 6.1.3.4

Warn in <unknown> line 0 | 2017-10-26 23:22:11 +0300
Ignoring ffi-1.9.10 because its extensions are not built.  Try: gem pristine ffi --version 1.9.10

Warn in <unknown> line 0 | 2017-10-26 23:22:11 +0300
Ignoring nokogiri-1.6.7.1 because its extensions are not built.  Try: gem pristine nokogiri --version 1.6.7.1

Warn in <unknown> line 0 | 2017-10-26 23:22:11 +0300
Ignoring picky-4.31.3 because its extensions are not built.  Try: gem pristine picky --version 4.31.3

Warn in <unknown> line 0 | 2017-10-26 23:22:11 +0300
Ignoring sqlite3-1.3.13 because its extensions are not built.  Try: gem pristine sqlite3 --version 1.3.13

Warn in <unknown> line 0 | 2017-10-26 23:22:11 +0300
Ignoring url_escape-2009.06.24 because its extensions are not built.  Try: gem pristine url_escape --version 2009.06.24

Warn in <unknown> line 0 | 2017-10-26 23:22:11 +0300
Ignoring yajl-ruby-1.3.0 because its extensions are not built.  Try: gem pristine yajl-ruby --version 1.3.0
```

**Comment by ccoupe** [comment]
It's a server problem. They changed the version of Ruby to 1.9.3 but the library seems to be 1.9.1 with a missing method Array.bytesize via cgi gem

**Comment by CaptainPhilipp** [comment]
uh oh, yes, I missed the main line:

```
Error in <unknown> line 0 | 2017-10-26 23:32:38 +0300
control can't have :state of enabled
```

Ok, thx!
How long do you think it will take to solve the problem?

**Comment by BackOrder** [comment]
> How long do you think it will take to solve the problem?

Ну, погоди!)))

**Comment by BackOrder** [comment]
Да нет! Google translate не надо. Я в прошлом жил и работал в Москве. :stuck_out_tongue_closed_eyes:

**Comment by ccoupe** [comment]
The selector/website is working again. However I get a lot of errors/warnings on my terminal from concurrent-ruby thead pool? - The output appear to be the right size.

**Comment by dredknight** [comment]
@ccoupe could you give me a release with the fix when ready ? I suspect this may be the culprit that makes parallel sessions crash (windows). I never had an issue with secondary+ sessions on Shoes with any version up to 3.3.3 included.

**Comment by ccoupe** [comment]
@dredknight - this fix was to a webserver script - no changes to Shoes.  We really haven't changed much for windows since 3.3.3 - those resize methods, systray, some ssl fixes and download speed.
