### ISSUE TITLE
Opening Shoes Splash and Shoes Manual programmatically crashes

### ISSUE THREAD

**Issue by BackOrder** [Shoes3/shoes3#39]
Cobbler was missing the feature to be able to go back to splash screen rather than quitting Shoes entirely. Unfortunately, it is not possible to add this feature right now because calling **Shoes.splash** crashes Shoes. Works fine on MacOS X.

```ruby
Shoes.app {
   button("splash")  { Shoes.splash and close }
   button("manual")  { Shoes.show_manual and close }
   button("console")  { Shoes.show_log and close }
   button("file")  { Shoes.show_selector and close }
   button("cobbler")  { Shoes.cobbler and close }
   button("package")  { Shoes.app_package and close }
   button("shy")  { Shoes.package_app and close }
}
```

**Comment by ccoupe** [comment]
This is related to #44. If it works in OSX, don't depend on it.

**Comment by BackOrder** [comment]
Running cshoes.exe reveals the same error as in issue #23 after clicking on splash button (opening splash screen). This may support that it is a Windows only issue.

```
(cshoes.exe:3992): Pango-CRITICAL **: pango_win32_font_map_get_font_cache: asser
tion `font_map != NULL' failed
**
Pango:ERROR:pangowin32.c:831:pango_win32_font_finalize: assertion failed: (win32
font->fontmap != NULL)
```

**Comment by ccoupe** [comment]
Latest 3.2.22 (r1905) on Windows doesn't fail or complain on the cshoes. console.

**Comment by BackOrder** [comment]
Confirmed on Windows 8, r1892. You fixed many issues at once when you updated font related code.
