### ISSUE TITLE
Package apps like the shoes toolkit

### ISSUE THREAD

**Issue by arjunmenon** [Shoes3/shoes3#407]
Hey
The shoes toolkit installer for linux automatically copies the required files to system lib and creates icons in menu. Easy enough to use later, without terminal.

But programs packaged with shoes generates a .run file, which needs to be executed in shell each time.
If the packaging was similar to the toolkit, that would be much better. 

Shoes can ask for icons and desktop configs and then create the appropriate package, which can be a better executable for any end user. They can directly access apps from their system apps menu.

Even better would be creating debian files and the like for distribution in app store, but that is a separate adventure to take.

I guess this is the same for other platforms as well.

**Comment by ccoupe** [comment]
@arjunmenon - take a look at[ linux-shoes repo](https://github.com/Shoes3/linux-shoes) which creates a .deb (or rpm or...) Unlike shoes packaging it is platform specific - you can't run it from osx or windows but there is much goodness for those who want their app to be more like normal apps.
