### ISSUE TITLE
Pango-WARNING couldn't load font

### ISSUE THREAD

**Issue by BackOrder** [Shoes3/shoes3#48]
Shoes unveils a series of warnings emitted by Pango library on Windows. 

> (cshoes.exe:2456): Pango-WARNING **: couldn't load font "Lacuna Not-Rotated 17.3
33984375px", falling back to "Sans Not-Rotated 17.333984375px", expect ugly outp
ut.

Recap from #46:
* MacOS X and Linux version have a launch script handling Pango dynamic setup.
* Includes **pangorc, pango.modules, pango-querymodules** files.
* Windows version doesn't need all the DLLs required by Pango, so those are not included.
* Windows version might need setting up Pango at installation time in https://github.com/Shoes3/shoes3/blob/master/platform/msw/base.nsi.

**TESTING LACUNA FONT**
```ruby
Shoes.app {
   font "#{DIR}/fonts/Lacuna.ttf"
   para "#{Shoes::FONTS}\n"
   
   para "THIS IS A NORMAL FONT | this is a normal font\n"
   para "THIS IS A LACUNA FONT | this is a lacuna font\n", :font => "Lacuna Regular"
}
```
***CONSOLE OUTPUT***
> (shoes.exe:9868): Pango-WARNING **: couldn't load font "Lacuna Not-Rotated 16.0009765625px", falling back to "Sans Not-Rotated 16.0009765625px", expect ugly output.

***RENDERING***
![image](https://cloud.githubusercontent.com/assets/8844578/5931223/c80e73de-a668-11e4-8bd7-ff7274ace9cc.png)
The rendering seems to work despite the warning.

**Comment by BackOrder** [comment]
Shoes::FONTS is empty when starting a new Shoes app on Windows whereas there are 492 fonts available in the MacOS X version.

**Comment by ccoupe** [comment]
Shoes font loading is a separate step from the graphical tool kit init.  The old msw native windows code had a way to load them. For example, OSX 10.6 and 10.9 have two different native api's. that Shoes can be compiled for.  For Windows gtk, we need the old msw code that iterates through the fonts and then presents font info in a way Gtk2 Pango/Cairo is happy with.  If we can do that then we can dump fontconfig.dll, font.conf and friends on Windows.  That should (he hopes) make the Pango Lucuna error messages go away as well.

**Comment by BackOrder** [comment]
The accepted answer is an interesting read for you @ccoupe: http://stackoverflow.com/questions/26615767/pango-unable-to-find-fonts-with-librsvg

**Comment by ccoupe** [comment]
@BackOrder , that would be bad news if we have to run pango-querymodules. cshoes.bat? shoes.bat

**Comment by BackOrder** [comment]
Isn't pango-querymodules a run-once thing? We can manage that from NSIS.

**Comment by ccoupe** [comment]
Good observation. I'm used to the linux/osx handling where it runs every Shoes time.   You should have pango-querymodules.exe in the gtk bundle bin/ if you want to try it.

**Comment by BackOrder** [comment]
There is no Pango DLL modules on the Windows build. That would be something needed before calling pango-querymodules.

**Comment by ccoupe** [comment]
There are no pango.modules on some Linux either or the names have been changed to protect the innocent!  Also it appears that Shoes/linux doesn't do the pango-querymodules dance (just OSX) so I'd prefer we not add the dance to Windows if we don't have to.

Your sandbox/share/ has the pango manual in html and more. In particular win32 calls to manage fonts.

We know that Shoes is perfectly happy with the fonts, and fontconfig is primarily  used to build the Shoes font list (and perhaps thats all it does). Only gtk/windows/pango complains about those two fonts.  Research and deep thought  is needed. 

Perhaps NSIS can install the two fonts and Shoes/Windows doesn't issue load them from loose files?
Perhaps Shoes/gtk.s  should not call the the Linux centric code and call the win32 centric code to find and build the the internal font.

**Comment by BackOrder** [comment]
The question is what are the Pango modules for? From Pango website:

> Dynamically loaded modules then handle text layout for particular combinations of script and font backend. Pango ships with a wide selection of modules, including modules for Hebrew, Arabic, Hangul, Thai, and a number of Indic scripts. Virtually all of the world's major scripts are supported.

My understanding is that Shoes for all platforms may not properly support fonts localization. Even on MacOS X, there would be some modules missing (as seen on stackoverflow). This would be a separate issue to file.

> We know that Shoes is perfectly happy with the fonts, and fontconfig is primarily used to build the Shoes font list (and perhaps thats all it does). Only gtk/windows/pango complains about those two fonts. Research and deep thought is needed.

The Pango manual says either one can be used — fontconfig or win32 fonts api. This might be a case where win32 is a winner when it comes to runtime speed but fontconfig is already implemented and running fc-cache using NSIS might cut it, speed afterwards will be matched.

> Perhaps NSIS can install the two fonts and Shoes/Windows doesn't issue load them from loose files? Perhaps Shoes/gtk.s should not call the the Linux centric code and call the win32 centric code to find and build the the internal font.

Installing the fonts wouldn't solve the problem. Normal Windows applications would install the fonts but it acceptable for an open source software to have its own fonts directory. Also, it serves as an example to Shoes programmers on how to load non-system fonts.

The **Pango message handler** from stackoverflow should tell us the exact reason for these errors. Then we can figure out what to do next.

**Comment by ccoupe** [comment]
updating to fontconfig 2.11.1 does not fix the problem

**Comment by BackOrder** [comment]
> updating to fontconfig 2.11.1 does not fix the problem

Thanks for testing this one! How about Pango message handler?

**Comment by ccoupe** [comment]
As we have discussed somewhere, Theres a lot to do with getting fontconfig really working properly and the new version I built from source has some 'features' we might want.
