### ISSUE TITLE
Para does not handle array and hash properly

### ISSUE THREAD

**Issue by BackOrder** [Shoes3/shoes3#49]
Shoes has a strange way to interpret values at runtime. **The reasonable expectation is that values should be changed in the order they are changed in the code.** See the example below to get a better idea of the issue. This issue does not affect MacOS X — the size of the array Shoes::FONTS are respectively 492, 492 and 493 when tested with a slightly modified version of the code below.

**TEST**
```ruby
Shoes.app {
   para Shoes::FONTS
   para "\n"
   para "#{Shoes::FONTS}\n"
   font "#{DIR}/fonts/Lacuna.ttf"
   para "#{Shoes::FONTS}\n"
}
```

**EXPECTED RESULT** the first *Shoes::FONTS* should be empty.

**ACTUAL RESULT**
```
Lacuna Regular
[]
["Lacuna Regular"]
```

**Comment by ccoupe** [comment]
This issue probably belongs under #48.  Shoes does load some font's at startup.

**Comment by BackOrder** [comment]
We both know better. How many times I had to wrap things with **timer(0) { }** because some object was not available at the time of the call.

**Comment by ccoupe** [comment]
I've got butt load of fonts for that script above on my Windows 7. But I'm using the FONTCONFIG_FILE and the fonts.conf.

**Comment by BackOrder** [comment]
> I've got butt load of fonts for that script above on my Windows 7. But I'm using the FONTCONFIG_FILE and the fonts.conf.

This is a very good news for issue #46 but not for this issue here. You misunderstand the sample code above. I happened to use font related code because the problem arose while testing for the previous issue but they are unrelated.

The value of Shoes::FONTS is correct when writing **para "#{Shoes::FONTS}\n"** but not when writing **para Shoes::FONTS**. How is that possible?!

Do you remember in https://github.com/Shoes3/shoes3/blob/master/lib/shoes/help.rb where **@edit_search** at line 292 was not available during runtime despite an EditLine being instantiated at line 265 and thus I had to do **timer(0) { @edit_search.focus }** ?

**Comment by ccoupe** [comment]
Slightly modified the script 
```ruby
Shoes.app {
   para Shoes::FONTS
   para "\n----------------------------------------------\n"
   para "#{Shoes::FONTS}\n"
   para "\n----------------------------------------------\n"
   font "#{DIR}/fonts/Lacuna.ttf"
   para "#{Shoes::FONTS}\n"
}
```
Notice how one the second block is a proper list representation with commas between items and the first is not. The first has a font in Japanese glyphs and the second has an escaped unicode string. The third block does have the Lacuna (alpha sorted order).

**Comment by BackOrder** [comment]
Yes, indeed. Would it be possible the first para uses inspect and the second uses to_s? There are two interesting observations: 1) Lacuna font is not in the first para when FONTCONFIG_FILE is properly set, 2) using info on the first one instead of para shows the same result as the last one.

Here is a screenshot on Windows for posterity. First without FONTCONFIG_FILE defined:

![image](https://cloud.githubusercontent.com/assets/8844578/5932455/fbc3e098-a67b-11e4-95ec-c0405ed735ab.png)

With FONTCONFIG_FILE and fonts.conf file:

![image](https://cloud.githubusercontent.com/assets/8844578/5932491/9418543c-a67c-11e4-9430-150aa7c96ecf.png)

![image](https://cloud.githubusercontent.com/assets/8844578/5932493/a5330c3a-a67c-11e4-9de2-0a70fc62a799.png)

Using info instead of para Shoes::FONTS:
![image](https://cloud.githubusercontent.com/assets/8844578/5932530/7a78f904-a67d-11e4-8dd5-3449ee48bd82.png)

**Comment by ccoupe** [comment]
```ruby
Shoes.app {
   ft =  ["1", "2", "3"]
   para ft
   para "\n******\n"
   para "#{ft}"
}
```
No fonts involved.

**Comment by BackOrder** [comment]
Excellent example. Here is a revised version. The to_s and inspect are working properly.

```ruby
Shoes.app {
   ft =  ["1", "2", "3"]
   para ft
   para ft.to_s
   para ft.inspect
   para "\n******\n"
   para "#{ft}"
}
```

**Comment by BackOrder** [comment]
And it doesn't go well for hashes. Nothing is displayed.

```ruby
Shoes.app {
   a = [1, 2, 3]
   b = { :a => 1, :b => 2, :c => 3 }
   para a
   para b
}
```

**Comment by BackOrder** [comment]
Using IRB  from Ruby has proven more than interesting.

```
irb(main):002:0> a = [1, 2, 3]
=> [1, 2, 3]
irb(main):003:0> h = { :a => 1 }
=> {:a=>1}
irb(main):004:0> puts a
1
2
3
=> nil
irb(main):005:0> puts h
{:a=>1}
=> nil
```

**Comment by ccoupe** [comment]
Srly?  Which part of the Shoes doc said you could pass a hash or an array to para and it would be hunky dory?  Perhaps it should throw an exception instead?

**Comment by BackOrder** [comment]
Very difficult to know what to do here. You often say Shoes is not Ruby but it is perhaps more to do with reasonable expectations. In any case, expert-irb.rb when using puts does report the same as regular IRB. Now an array passed to para is kind already similar to puts except that puts separates each elements by a newline. Handling hashes only needs a conditional in Shoes internals and convert using to_s.

**Comment by ccoupe** [comment]
Not difficult at all. 

If it helps: "Para is not puts and puts is not printf()".  You get an array or a hash from where ever (a yaml file or Shoes::FONTS or download.headers. You know textblock wants a string with optional styles. 

Your irb script needs to much more expert.

You might not know that Shoes textblock creates  (I think) a new segment when it sees  "\n" and that effects what you see in stacks and flows layout

**Comment by BackOrder** [comment]
Well, I could live with that. Initially the issue was Lacuna would be printed out on the first para, which made no sense, but it was in fact related to #46. So this would conclude and close the issue. Thanks for the clarification.
