### ISSUE TITLE
commented lines on app_package.rb / package an app not working

### ISSUE THREAD

**Issue by passenger94** [Shoes3/shoes3#58]
Those lines are commented on app_package.rb
```ruby
      para "Advanced installer -- Must be a .shy (directory) to package"
      flow do
        @defadvopts = check  do
          @advpanel.show if @defadvopts.checked?
          @advpanel.hide if !@defadvopts.checked?
          @options['advopts'] = @defadvopts.checked?
        end
       para "I want advanced options"
      end
```
is there any reason for that ? because uncommented it works fine 
tested with single script and directory, packaging for Linux and windows (didn't try advanced options)
the **@defadvopts = check** is expected to exist otherwise script stops at line 302 : **@options['advopts'] = @defadvopts.checked?**

**Comment by ccoupe** [comment]
That was my clumsy attempt to get 3.2.20 out the door w/o the advanced packaging panel showing.
I'll change that to something like:
      flow do 
        @defadvopts = check :checked => false, :state => "disabled"
        para "Advanced options. Disabled"
      end

and leave the comments in.

**Comment by passenger94** [comment]
:-D :-D  
That's what happens sometimes when doing a lot of great work !!
