### ISSUE TITLE
Automatically initializing a Radio Button

### ISSUE THREAD

**Issue by ccoupe** [Shoes3/shoes3#6]
Was https://github.com/shoes/shoes/issues/167

**Comment by ccoupe** [comment]
There are several issues with Radio buttons. 
```ruby
Shoes.app do
  stack do
    flow {
      @r1 = radio :group, checked: true
      para "one"
    }
    flow {@r2 = radio :group; para "two"}
    flow {@r3 = radio :newgrp; para "close"}
    flow {@r4 = radio :newgrp; para "far"}
    @r4.checked = true 
    start { 
      para "checked one = #{@r1.checked?}\n" 
      para "checked far = #{@r4.checked?}\n"
    }
    button "Now check" do
      para "One: #{@r1.checked?}\n"
      para "Two: #{@r2.checked?}\n"
      para "close: #{@r3.checked?}\n"
      para "far: #{@r4.checked?}\n"
    end
  end
end
```
Note that the start { } is required for Gtk for all the normal delayed evaluation confusion rules. 
On OSX, the above example produced _one_, not two groups of radios. Indeed, the group argument is not used.   

Apple suggests using a NSMatrix with mode:NSRadioModeMatrix. This will require a new implementation of Shoes radio that doesn't share much if anything will the existing ShoesButton. We'll need a 'unspecified' matrix and matrices that match 'given' groups.  - Nil, string, :symbol in Ruby terms.  Of course we will need a NS hash to manage the groups. 

One other problem: On OSX, The start {} doesn't display until the button is pushed. That might be an unrelated bug.

**Comment by ccoupe** [comment]
ruby.c handles the groups and setting the buttons off and on just fine.  It's osx that thinks all buttons without a matrix must be in a hidden matrix.  One hack worth trying: Creating an explicit NSMatrix with 1 row, 1 column for each Shoes radio button so that osx won't manage them all collectively.  Odd thinking but it might work.

**Comment by ccoupe** [comment]
This is a nasty problem. The semantic mismatch between OSX radios and Shoes radios is high. No wonder it was never fixed. Still isn't.  Shoes treats radios just like checkboxes and Shoes manages the groups on/off settings. OSX radiobuttons assume there is a NSMatrix that will manage them and misbehave if there isn't.   Radio buttons in Shoes are pretty clunky (as are checkboxes)  but solving that breaks backwards compatibility so that's a different issue than this bug report.

**Comment by ccoupe** [comment]
The radio buttons need new images so they look more like OSX radios but the style below should be good enough for a while.
![temp-radio](https://cloud.githubusercontent.com/assets/222691/6792821/34820348-d182-11e4-95e8-2cb4c3cb64ee.png)

**Comment by BackOrder** [comment]
Is that normal the radio and para are misaligned vertically?

**Comment by ccoupe** [comment]
I haven't committed the code changes yet - its just a BezelStyle setting. They need to be drawn with NSImages which I haven't created (or borrowed).

**Comment by ccoupe** [comment]
For comparison, here's the old radios CFLAGS << ' -DOLD_RADIO'
![old-radios](https://cloud.githubusercontent.com/assets/222691/6793376/2845806c-d189-11e4-890f-e0de0bc43f6e.png)

**Comment by ccoupe** [comment]
Considering this note that Apple is deprecating/planning to deprecate NSCell and NSMatrix https://developer.apple.com/library/mac/releasenotes/AppKit/RN-AppKit/,  It may not be worth the effort to draw the icon with the tiny white dot in the center.
