### ISSUE TITLE
Keyup and keydown not documented

### ISSUE THREAD

**Issue by BackOrder** [Shoes3/shoes3#61]
Both **keyup** and **keydown** are supported but not documented in the manual. The following example shows that a keydown event is triggered when ***a key is pressed***, keypressed will be triggered ***as long as it is pressed***, and keyup will be triggered when ***a key is released***.

```ruby
Shoes.app {
   keyup { |n| para "keyup: #{n}\n" }
   keydown { |n| para "keydown: #{n}\n" }
   keypress { |n| para "keypress: #{n}\n" }
}
```

**Comment by passenger94** [comment]
breaking the strict alphabetic order to group keydown/keyup together befor keypress for following details 
added "and as long it is pressed," to keypress event
what do you think ?
```
==== keydown { |key| ... } » self ===

triggered at the moment a key is pressed ! see [[Events.keypress]] below for details

=== keyup { |key| ... } » self ===

triggered when a key is released ! see [[Events.keypress]] below for details

=== keypress { |key| ... } » self ===

Whenever a key (or combination of keys) is pressed, and as long it is pressed, the block gets called.  The
block is sent a `key` ....................................................
```

**Comment by BackOrder** [comment]
Thanks for taking the challenge, @passenger94 !

> triggered at the moment a key is pressed ! see [[Events.keypress]] below for details

Revision:
> **T**riggered whenever a single key is pressed, the block gets called. The block is sent a key which is a string representing the character (such as the letter or number) on the key.

I am thinking that we cannot refer keypress for additional details because keyup and keydown don't support combination of keys. Don't forget a capital letter at the beginning of a sentence and dot at the end!

The keypress part seems good. Does it accurately reflect the behaviour? This is what I initially wrote but suddenly it doesn't seem entirely accurate because in fact the block gets called multiple times when a key or combination o keys remains pressed. How about 

> Whenever a key (or combination of keys) is pressed, the block gets called, and will be repeatedly called as long as it is pressed.

What do you think?

**Comment by passenger94** [comment]
ooops didn't noticed they don't support combination of keys !!

but the event do get triggered with multiple keys but a single letter is sent to the block !?

**Comment by BackOrder** [comment]
> but the event do get triggered with multiple keys but a single letter is sent to the block !?

Shift, ctrl and alt are ignored by keyup and keydown. So if you press, say, alt-shift-a, it will only be triggered by the letter a. Also, keypress will not be triggered by shift, ctrl or alt alone (or even together), it does need a normal character either alone or in a combination with shift, ctrl and/or alt.

**Comment by passenger94** [comment]
yes i noticed :-) but since keydown/keyup reports something when pressing alt-shift-a, i thought i could look at it like if the event get triggered (sending for some reason only the 'a' to the block) or like you say keydown/keyup only sees the 'a' hence sending that to the block
sorry for confusion :-D

**Comment by BackOrder** [comment]
No problem! We live and learn.

Let's say that Shoes needs our help.

**Comment by passenger94** [comment]
```=== keydown { |key| ... } » self ===

Triggered whenever a single key is pressed, the block gets called. The block is sent a key which is a string representing the character (such as the letter or number) on the key.  For special keys, a Ruby symbol is sent, rather than a string, see [[Events.keypress]] for a list of special keys.

=== keyup { |key| ... } » self ===

Triggered whenever a single key is released, the block gets called. The block is sent a key which is a string representing the character (such as the letter or number) on the key.  For special keys, a Ruby symbol is sent, rather than a string, see [[Events.keypress]] for a list of special keys.

=== keypress { |key| ... } » self ===
Whenever a key (or combination of keys) is pressed, the block gets called, and will be repeatedly called as long as it is pressed.  The block is sent a `key`   .....................
```
What do you think ?

**Comment by BackOrder** [comment]
A revision below. Please, take note that keyup and keydown do **not** support any kind of special keys. Hence, it should **not** be mentioned into these sections. Let's also add some code sample, shall we?

> === keydown { |key| ... } » self ===
>
> Triggered whenever a single key is pressed, the block gets called. The block is sent a key which is a string representing the character (such as the letter or number) on the key. 

```ruby
Shoes.app {
   @info = para "Press a key."
   keydown do |k|
      @info.replace "#{k} was PRESSED."
   end
}
```

> === keyup { |key| ... } » self ===
>
> Triggered whenever a single key is released, the block gets called. The block is sent a key which is a string representing the character (such as the letter or number) on the key. 

```ruby
Shoes.app {
   @info = para "Press a key and maintain it."
   keyup do |k|
      @info.replace "#{k} was RELEASED."
   end
}
```

> === keypress { |key| ... } » self ===
> Whenever a key (or combination of keys) is pressed, the block gets called, and will be repeatedly called as long as it is pressed.  The block is sent a key  .....................

**Comment by BackOrder** [comment]
You were given access to the repository, @passenger94. 

It means that you can commit changes directly rather than having pull requests. Now, remember to test your changes before committing anything. You need to pull first in case the repository changed, retest your changes if necessary, and commit. You break it, you fix it.

https://help.github.com/articles/closing-issues-via-commit-messages/
Use **closes #61** in your commit message and you will automatically close this issue.

You can go ahead and update the manual.

Enjoy.

**Comment by passenger94** [comment]
ok will do (i surely need revisions before commiting)  but here's what i get on my system
```ruby
Shoes.app {
   keydown do |k|
      para "#{k} was PRESSED.\n"
   end
}
```
![specialkeys](https://cloud.githubusercontent.com/assets/10730930/6179762/c42d31e0-b31c-11e4-9928-0a81db6e7460.jpg)


in keypress doc there is a clear distinction between special keys and keys combo
> For special keys and key combos, a Ruby symbol is sent, rather than a string.

> The list of special keys is as follows: `:escape`, `:delete`, `:backspace`,
`:tab`, `:page_up`, `:page_down`, `:home`, `:end`, `:left`, `:up`, `:right`,
`:down`, `:f1`, `:f2`, `:f3`, `:f4`, `:f5`, `:f6`, `:f7`, `:f8`, `:f9`, `:f10`,
`:f11` and `:f12`.

**Comment by BackOrder** [comment]
Thanks! You are correct. It also works on Windows as you described, so you can indeed write about the special keys. The distinction is that modifier keys and special keys are different. Good work.

**Comment by jhabril** [comment]
keydown and keyup not work on macOS

**Comment by ccoupe** [comment]
@jhabril  do you have an example?  On OSX keypresses work for me. What version of Shoes are you using? What version of OSX?

**Comment by jhabril** [comment]
OS X El Capitan Version 10.11.6 
Shoes 3.3.2 r2737

# I don't get an error but the code doesn't work 
keyup { |n| para "keyup: #{n}\n" }
keydown { |n| para "keydown: #{n}\n" }

# works great  on Windows, MacOS and Ubuntu.
keypress do |k|  
      case k
             # works great 
      end
    end

Thanks for your help.

**Comment by ccoupe** [comment]
The  current Shoes for OSX  is [3.3.7 ](https://shoes.mvmanila.com/public/shoes/shoes-3.3.7-osx-10.10.tgz) and there is a  [3.3.8 beta](https://walkabout.mvmanila.com/public/shoes/shoes-3.3.8-osx-10.10.tgz). There are improvements in keyhandling since 3.3.2.  Please note, I am no longer maintaining Shoes with any regularity so 3.3.8 beta maybe as could as it gets.

**Comment by jhabril** [comment]
Thanks, I tried 3.3.7 and 3.3.8 works on MacOS El Capitan

keyup and keydown dosen't work.
   keyup { |n| para "keyup: #{n}\n" }
   keydown { |n| para "keydown: #{n}\n" }

I will try again, thanks a lot.
