### ISSUE TITLE
missing shape documentation

### ISSUE THREAD

**Issue by passenger94** [Shoes3/shoes3#62]
saw it @Shoes4
only first shape declaration is documented in manual [ shape(left, top) ]

```ruby
Shoes.app do
    PI = Shoes::PI
    TWO_PI = Shoes::TWO_PI
    
    fill red(0.2)
    shape(10, 20) do
        move_to(90, 55)
        arc_to(50, 55, 50, 50, 0, PI/2)
        arc_to(50, 55, 60, 60, PI/2, PI)
        arc_to(50, 55, 70, 70, PI, TWO_PI-PI/2)
        arc_to(50, 55, 80, 80, TWO_PI-PI/2, TWO_PI)
    end
    shape(50, 100, width: 100, height: 100, fill: red(0.6)) do
        move_to(90, 55)
        arc_to(50, 55, 50, 50, 0, PI/2)
        arc_to(50, 55, 60, 60, PI/2, PI)
        arc_to(50, 55, 70, 70, PI, TWO_PI-PI/2)
        arc_to(50, 55, 80, 80, TWO_PI-PI/2, TWO_PI)
    end
    shape(width: 50, height: 50, fill: red(0.9), strokewidth: 5, 
                                    left: 90, top: 180, stroke: darkblue) do
        move_to(90, 55)
        arc_to(50, 55, 50, 50, 0, PI/2)
        arc_to(50, 55, 60, 60, PI/2, PI)
        arc_to(50, 55, 70, 70, PI, TWO_PI-PI/2)
        arc_to(50, 55, 80, 80, TWO_PI-PI/2, TWO_PI)
    end
    contents.each {|sh| info "#{sh.style}"}
    Shoes.show_log
end
```
:width and :height style does nothing on the shape, expected, i think, but should we document this ?
there's 3 ways of declaring the shape : (left, top) or (left, top + styles) or (styles), for clarity only keep first and last in manual ? (*there's also shape {} but is kind of implicit ?*)
also there's a rotate style @Shoes4 example which does nothing in Shoes3.2
note that using whatever nonexisting style for ex  *:blahblah => 152* doesn't trigger a warning or error about the missing style

**Comment by BackOrder** [comment]
> there's a rotate style @Shoes4 example which does nothing in Shoes3.2

Could you add screenshot(s)? This will give us a reference to compare with.

**Comment by BackOrder** [comment]
The manual in **Shoes > Styles** stipulates that styles apply to all elements. **Elements > Shape** refers to **Elements > Common**, which in turn also mention styles. Does it cover the issue your reported?

**Comment by passenger94** [comment]
yes you're right, this is the way to look at it !!!
but manual is a bit confusing then ! it feels like shape is a special case, at least in 3.2, Shoes4 is more strict : shape must be instanciated with styles now.
why not, in manual, hiding shape(left, top) and keeping only shape(styles) ? would be more consistent


arc_to is not avalaible in latest shoes4 ! and :rotate style does nothing in shoes4 and shoes3 at least on my system, just checked !

screenshot for sample above (shoes3.2) :
![shapes](https://cloud.githubusercontent.com/assets/10730930/6167922/7ac59c9c-b2c0-11e4-9a7b-1f1c6bc03a8d.jpg)

**Comment by BackOrder** [comment]
The manual is confusing at times. For example, oval has two definitions — oval(left, top, radius) and oval(styles). It will take time to improve coherence. It would make sense to document  `shape(styles) » Shoes::Shape`.

It is acceptable to ignore non-existing styles. Otherwise it would certainly fill up the Shoes Console for no particular advantage. Ruby is a forgiving language.

Rotate doesn't seem to be a style. See the sample from the manual below:

```ruby
 Shoes.app do
   fill "#333"
   rotate 45
   rect 30, 30, 40, 40
 end
```

![image](https://cloud.githubusercontent.com/assets/8844578/6168065/ad31d000-b28f-11e4-97da-d51cad51244b.png)

**Comment by passenger94** [comment]
yes the rotate method works fine but in @Shoes4 sample i noticed the rotate style, so without checking first with shoes4, i thought it was doing what one expect a rotate contortion do to a regular shape in this dimension of the universe :-D
what do you think would be best, adding  `shape(styles) » Shoes::Shape` or replacing `shape(left, top)` ?

**Comment by BackOrder** [comment]
Adding `shape(styles) » Shoes::Shape` would be best considering that shape(left, top) also does work.

**Comment by passenger94** [comment]
```
=== shape(styles) { ... } » Shoes::Shape ===

Describes an arbitrary shape to draw, initialized using a style hash.  The following styles are relevant:

 * `top`: the y-coordinate for the shape.
 * `left`: the x-coordinate for the shape.
 * `center`: do the coordinates specifie the rectangle's center? (true or false).
 * `cap`: sets the shape of the line endpoints.
 * `stroke`: color of the ouline of the shape.                  
 * `strokewidth`: size of the outline of the shape.
 * `fill`: color of the shape.

These styles may also be altered using the `style` method on the Shape object.
```
other styles like margin, etc... are avalaible, while, as said, some are not relevant (:width, :height)
except :center (described in rect and oval) those are the one which appear on a non styled shape (by default)

**Comment by BackOrder** [comment]
Good, I like it. 


**Revision:**
Change the other of the words seem to make more sense.
> `cap`: sets the line endpoints of the shape.

Typo is in bold here: 
> `stroke`: color of the **outline** of the shape.

You can commit with these changes.
