### ISSUE TITLE
Hardcoded environment path variables

### ISSUE THREAD

**Issue by BackOrder** [Shoes3/shoes3#66]
Hardcoded environment path variables refer to @ccoupe.

**Shoes.app/Contents/MacOS/lib/ruby/gems/2.1.0/environment**
```
export PATH="/Users/ccoupe/.rvm/gems/ruby-2.1.5@global/bin:/Users/ccoupe/.rvm/rubies/ruby-2.1.5/bin:$PATH"
export GEM_HOME='/Users/ccoupe/.rvm/gems/ruby-2.1.5@global'
export GEM_PATH='/Users/ccoupe/.rvm/gems/ruby-2.1.5@global'
export MY_RUBY_HOME='/Users/ccoupe/.rvm/rubies/ruby-2.1.5'
export IRBRC='/Users/ccoupe/.rvm/rubies/ruby-2.1.5/.irbrc'
unset MAGLEV_HOME
unset RBXOPT
export RUBY_VERSION='ruby-2.1.5'
```

**Comment by ccoupe** [comment]
What magic did Shoes do to execute that?

**Comment by BackOrder** [comment]
Harry Potter meets Shoes.

Turns out I had an old Shoes 3.2.17 for MacOS X archive and the file is also there.

**Comment by ccoupe** [comment]
I'm sure there are similar  hardcoded things when  copying any installed Ruby (and even the special cross compiled and chrooted builds do a Ruby install).  The question is "Does it effect Shoes functionality?" and if yes, how did you find he problem with a Shoes script.

**Comment by BackOrder** [comment]
The effects are unclear. Found out in a purely coincidental manner. Shoes might silently swallow any errors or warnings. Hardcoded things are unhealthy.

**Comment by ccoupe** [comment]
Someone should tell Apple and Ruby about that hardcoding problem! do a grep -R ccoupe Shoes.app/*. Why is my name buried in all those binary .bundles (it's not otool linkage)? even a few linux .so have my name in them.

**Comment by BackOrder** [comment]
Ran `grep -R ccoupe *` on tightmingw directory using msys:

```
$ grep -R ccoupe *
Binary file libgif-4.dll matches
Binary file libjpeg-9.dll matches
static/manual-en.txt:See the [[http://github.com/ccoupe/shoes/wiki Shoes 3.2 Wik
i]] and learn about Gems
static/manual-en.txt: * [[https://github.com/ccoupe/shoes Shoes 3.2 source code.
]]
static/stubs/app-install.tmpl:  #shyname = File.basename("/home/ccoupe/Projects/
unshy/ytm.shy")
Binary file static/stubs/shoes-osx-install matches
```

**Comment by ccoupe** [comment]
I'm going to call this one complete.  rvm is no longer used to build Shoes for OSX 10.6 or 10.9 and there is nothing reasonable that can be done for embedded path names in compiled dependencies (dll, dylib, or so) without stripping all the info that allows it to link.
