### ISSUE TITLE
edit_line does not align

### ISSUE THREAD

**Issue by ccoupe** [Shoes3/shoes3#7]
Was https://github.com/shoes/shoes/issues/229

**Comment by ccoupe** [comment]
This is a weird bug.  For shoes_native_edit_line the incoming place->iy arg is +4 and it sticks for all widgets that follow. Additional edit_lines in a flow will increase iy by another 4. Also place->iw is 104 instead of 100. Why or how would flow layout do that?

**Comment by BackOrder** [comment]
There are hardcoded default styles in Shoes code that may indirectly affect edit_line.

**Comment by ccoupe** [comment]
I suspect the answer is at ruby.c:3172

**Comment by BackOrder** [comment]
You are right. It makes sense.

**Comment by ccoupe** [comment]
There are other places in ruby.c where #SHOES_QUARTZ is used to adjust  place.h and place.ih. 
Commenting out the other adjustments near line 3172 and leaving place.h and place.ih appears to work.
