### ISSUE TITLE
Clean up rakefiles

### ISSUE THREAD

**Issue by ccoupe** [Shoes3/shoes3#70]
Fixing #50 provides a new set of APP['CONSTANTS'] that should be used in each env.rb and task.rb or at least create new constants from them with names that make sense.  12 sets! 

This would also be a good time to clean up the comments, remove unused methods and other oddities. Move constants the user must set to the top of the file, ...

Since this is not critical or entertaining and a lengthy process, it's low priority.

**Comment by BackOrder** [comment]
This would be absolutely fantastic. Few suggestions on the top of my head:

* The main Rakefile should be behave as a dispatcher
* Each target should provide their own raketask.rb
* YAML based target configuration (paths, etc.)
* Refactoring duplicated codes in targets

You might remember when I submitted files for MINGW target build on Windows, it included raketask.rb. It is possible to require make/*/raketask.rb where each target specific tasks will be added and available (rake -T).

**Comment by ccoupe** [comment]
Cross compiling make them ugly and difficult,  particularly with extconf.rb which has to be forced to build for a different platform than the one running extconf/mkmf. Ruby makes it messy and Ruby changes a lot. 

Now that I've poked around a bit with cleanup on my mind one big confuser is the use of ENV['VAR'] to pass values from Rakefile to env.rb and if the ENV['var'] doesn't exist (and it won't in Shoes 3.2) use what we really want.  env.rb and tasks.rb are not  subprocesses. ENV is only needed for the ext/gem builds because they are spawned subprocesses. 

No doubt that was an attempt to have one env.rb and one tasks.rb for all platforms that would be externally driven. Probably for Hackety Hack to procreate it's self with a `sh rake build`. That stopped working years ago. With  Shoes 3.2 we have a way to drive the packager externally for any platform,  from any platform without rake or compilers needing to be invoked.  The cowboy in me says all that can go in every env.rb I see,

Most of the new VERSION constants would apply to tasks.rb. Somehow, that seems wrong. But you got go with what you have.

**Comment by BackOrder** [comment]
Wouldn't be a better approach to use YAML target configuration file and dynamically create ENV variables from the YAML when needed?

**Comment by ccoupe** [comment]
@BackOrder - I'm sure which point you're responding too. HH config or ext/gem building or ?

For ext/gem, one possibility would be to use multiple extconf.rb (macextconf, mingwextconf armhfextconf) and execute the one you want from instead of extconf.rb you can also pass commandline args for macextconf.rb if needed.  That would make them a lot easier to deal with if you need to modify them. For sqlite3 that might the way to go. ftsearch - not so much.  It will only get worse if we decide to include new gems with more dependencies.

**Comment by BackOrder** [comment]
> @BackOrder - I'm sure which point you're responding too. HH config or ext/gem building or ?

You mentioned that only ext/gem building are using ENV variables. Those ENV variables should be generated at runtime in such way we can get rid of all ENV hardcoded references from Rakefile and target files.

Hardcoded matters should always be on top of a file or in a YAML configuration file.

By the way, `devdll = "C:/Devkit/mingw/bin"` in https://github.com/Shoes3/shoes3/blob/master/make/tightmingw/env.rb#L92 should be `devdll = "#{ENV['RI_DEVKIT']}/mingw/bin"` (from `require 'devkit'`).

**Comment by ccoupe** [comment]
Status Report: Just a couple more to do (snow, mavericks, xsnow) and then delete some constants stuff in Rakefile that shouldn't be needed anywhere, snort. They still aren't pretty. 

Unsure what to do with make/mingw and make/darwin - the loose/tight doesn't matter all that much to mingw or OSX.

**Comment by BackOrder** [comment]
> Unsure what to do with make/mingw and make/darwin - the loose/tight doesn't matter all that much to mingw or OSX.

My feedback is that loose Shoes was actually useful to explore and fix things. Leaving legacy target may be acceptable. Now the target names are unclear and it makes it difficult to know what those are for. Shall we reconsider renaming all targets in a coherent and comprehensive manner?

**Comment by ccoupe** [comment]
Loose Shoes on OSX could be useful for a Shoes developer, but its' a bit of a mess at the moment.

I'm listening if you have a proposal for target naming but remember that  changes to  packaged Shoes names/structures will bubble up, down and around the user packaging, the website, your projects and mine.

**Comment by BackOrder** [comment]
The package names seem acceptable but the target names in make directory are confusing. For Windows alone: mingw, tightmingw, xmingw32, xmsw32. The name in **rake -T** are also confusing.

Perhaps changing the structure would make it easier to understand with a pattern to be repeated on each platform, such as, for make sub-directories:

* windows-mingw-32
* windows-mingw-cross-32
* windows-mingw-tight-32
* windows-native-32

**Comment by BackOrder** [comment]
https://github.com/Shoes3/shoes3/commit/12b34bcb733ce70806060200e88045407d728998#diff-9b6f128e0f6d45004d090c8735ae4e50R159

> cp "#{libn}", "#{TGT_DIR}/" unless File.exists? "#{TGT_DIR}/#{keyf}"

The problem with this approach is that it won't update a library if it is newer but instead only if it is not present. This is what Rake **file** and **rule** are for and would be Rakefile best practice. See link below.

http://madewithenvy.com/ecosystem/articles/2014/rake-rule-tasks/

> But, in a gist, it means: the task will only be executed if the file does not exist, or unless it has a file task dependency with a newer timestamp than itself.

**Comment by ccoupe** [comment]
This part of the task.rb is a ruby method to find and copy the libraries that Ruby and Shoes need. In the case of xsnow, these are the 10.6 libraries and they _do not_ want to be confused with newer 10.9 libraries nor can rake derive the the list with simple time stamps or file name parsing.  Using cp_f might be more clear.

**Comment by BackOrder** [comment]
It wouldn't confuse 10.6 libraries with 10.9 but you might be right about cp_f being more clear. The rakefiles were not exactly written in a Rakeish manner to start with. The cleaning seems to going well. Keep it up!

**Comment by ccoupe** [comment]
target snowleopard (10.6 on 10.60 doesn't compile the hpricot exts because of a bad -Wno-something directive in the extconf.rb . Loose Shoes on darwin (all osx versions) is _probably_ incorrect. Loose Shoes on mingw is untested, probably not correct.  

On the bright side, I can build the major platforms that are distributed with one shell script . I don't care that much about Loose Shoes on Windows  or OSX. New developers can handle the tightshoes configuration just as easily as Loose Shoes (since the configure values are the same)

 I'd rather tackle the extconf.rb mess.  One platform at a time, sigh.

**Comment by BackOrder** [comment]
I'm liking the changes so far because things are getting orderly and a bit more clear. Still thinking it would be a good idea to move out the namespaces to their respective targets. What do you think?

https://github.com/Shoes3/shoes3/blob/master/Rakefile#L322

**Comment by ccoupe** [comment]
It's been a bottom up cleanup so far which was the original intent for this issue. OSX is the more complex platform and the source of much confusion and errors. Declining ROI on the 10.6 stuff doesn't help either.

Some of your suggestions suggest a top-down or rethink/re-architect of the whole mess which may be the only way to really get the warts off and should consider my ideas about making gems/exts more independent build-ables.

**Comment by ccoupe** [comment]
I'm going to keep the namespace for a while but I am going to rename things to be a little more consistent.  darwin, linux, mingw will be the Loose Shoes names - same as it ever was. Tight Shoes names will change slightly. They all need a name space (osx:|| win32:|| linux:) same as before. 

There will be native builds and not native builds (cross compile or down shifting). The latter have an'x' in front of their name. xwin7, x86_64-linux, xi686-linun, xsnowleopard.  It's easier just do it than explain.

**Comment by ccoupe** [comment]
For win7 and xwin7 targets, the rake build will look for win7-custom.yaml and xwin7-custom.yaml. (respectively). These files are not in github. They are local customizations that won't be overwritten with a github pull or fetch.   For example my win7-custom.yaml might like this
```
Deps: E:/shoesdeps/mingw
Ruby: C:/Ruby21
MS-Theme: false
Debug: true
```
Debug is true/false - false if not specified at all. It sets/unsets the ENV['GDB']. 
MS-Theme is true/false (false if not given). False is the old 3.2.21 appearance and true uses MS-Windows theme GTK2/Windows.

**Comment by BackOrder** [comment]
Excellent. Very promising. This should be documented somewhere since it is in .gitignore.

**Comment by ccoupe** [comment]
https://github.com/Shoes3/shoes3/wiki/Custom.yaml

**Comment by ccoupe** [comment]
Added mavericks-custom.yaml. Mine looks like:
```ruby
Deps: /usr/local
Zlib: /usr/local/opt/zlib/lib
Debug: true
CFLAGS: -DNEW_RADIO
```
