### ISSUE TITLE
New  process for building, distributing Shoes gems

### ISSUE THREAD

**Issue by ccoupe** [Shoes3/shoes3#72]
It's really annoying to build all of Shoes just to fix a gem. It's really annoying to build gems (and ext) just to fix something unrelated to them. It will even more annoying if we wanted to replace or add gems in the future. 

My half baked idea is that there would be no ext - so ftsearch and chipmunk would be converted to gems.  Those and the gem hpricot and sqlite3 would be in some gem archive file - Shoes.gems for example that would be part of a download and install. In the install phase when Shoes runs for the first time, it see it doesn't have it's built in gems and install them. We add a button to Cobbler to download and install newer Shoes.gems if available. 

Since gems can have pre-compiled binary payloads we would have to provide  Shoes.gem for each platform to be included when we do rake package.  

The task of building and updating  the gems is mostly separated from Shoes and very dependent on rubygems doing what I think it can do.

**Comment by BackOrder** [comment]
This change is certainly appealing. We already talked about the possibility to add new gems and replace old ones (Nokogiri instead of hpricot, Picky instead of ftsearch).

There might be on caveat in the scenario proposed above — during development, I would often test things in tightmingw directory where the gems should be readily available. It means that they might have to be preinstalled instead of installing them at installation time.

**Comment by ccoupe** [comment]
Indeed, that is a weakness.  Something that might be easier and still provide some separation between gem building and shoes building would be to copy  the gem contents into the resulting shoes (tightmingw in this case) similar to what it does now.  The gems source/build  would not live in the shoes3.2 directories.  For the gem building side , building a gem could copy it into the an existing tightmingw (if it exists) replacing what was there.. Sadly, this wouldn't simplify much, if at all. More thinking.

**Comment by BackOrder** [comment]
It should definitively copy the gems into the resulting Shoes. The advantage here is that it would be possible to build them separately. Rake tasks could be written in such way to only build those gems if not built, when changed and/or when the specific tasks are invoked.

**Comment by ccoupe** [comment]
Yes, the gems should be (re)built only if needed.  The scheme needs to deal with the cross compile problems and dependent so/dll/dylib that might not be in the Shoes location.  I don't know how well rakecompiler can handle what I'm thinking of. Just don't know.

**Comment by BackOrder** [comment]
Rake provides **rule** and **file** rules that would allow to do something like that. It won't build the rule when the target of the rule is already present.

**Comment by ccoupe** [comment]
I'm going to start this effort but trying to get Nokogiri to build/cross compile and replace hpricot in Shoes and see what happens and learn what has to be done.

**Comment by ccoupe** [comment]
Yikes! Nokogiri is complicated. I still haven't found the incantation to cross compile the windows binary gem.  The good news is that Shoes Cobbler had no problem download and installing the  binary gem on Windows. That wasn't working the last time @BackOrder and I tried. 

 It's important to note that they appear to have statically linked/copied  libxml2 and libxslt1 - in Shoes we'd prefer to use the libxml2.dll that we distribute. Nokogiri (on Windows)  also includes the nokogiri.so for 1.9.3, 2.0.0 and 2.1.0. Only one of which we could use and of course it includes all the source and doc so it's a huge gem. 

They appear to include their own copy of libxml2 and libxslt1 source code (and patches to them) but I haven't found the incantation to build a gem with and x86_64_linux binary inside. I see hints that it can be done with difficulty.  OSX? I'm even less sure how that would work w/o xcode installed.  What I can see is a very difficult task ahead.  Thinking about the Picky dependencies (and dll duplications) suggest it would be an even harder task. 

There only two things that require built-in gems - samples/expert-funnies.rb and samples/simple-sqlite.rb. XML parsing and composing SQL statements from Ruby are not beginning programming topics.  In my simple mind, if folks need to do those tasks from Shoes it's not too much to ask  for them to install devkit. xcode or issue the apt-get/yum/zypper commands.  Shoes already knows how use existing gems on a users system if told to.  So, rather than enhance the built-in gems I'm leaning towards not including them. 

For the rare situation when a developer wants  to package a shoes app with binary gems of their choosing, there would be a way to do that in Shoes if the developer is willing to build the binary gem.

**Comment by ccoupe** [comment]
I've managed to separate gem and extension building from building Shoes for targets xwin7, win7 and xarm6hf. Basic documentation at https://github.com/Shoes3/shoes3/wiki/Gems-for-Shoes.  Commits will follow shortly.  I still have to do OSX changes and testing to do but the design  'doesn't suck much'. 

Then I can try to build nokogiri and picky and all it's deps - many, many many gems.

**Comment by ccoupe** [comment]
This took a lot longer and more effort than I thought.  It's a tolerable process, for patient and observant. It should be easier.  Nokogiri-1.6.6.2 is included in Shoes 3.2.23 betas -  trimmed to just the essentials to reduce bloat (a lot of that gem).

**Comment by ccoupe** [comment]
I started the explanation for why I want this feature and think it is something that Shoes 3.2 (MRI Ruby) can do that is completely platform specific but oddly generic.   https://github.com/Shoes3/shoes3/wiki/Gempacks

**Comment by ccoupe** [comment]
I'm thinking of closing this issue unless folks think it should stay open. 3.2.23 does have new handling for gem building and distribution when building Shoes. Gem handling when users want to package gems or build gems from source is a different issue.
