### ISSUE TITLE
Shoes is always built with debugging symbols

### ISSUE THREAD

**Issue by BackOrder** [Shoes3/shoes3#73]
Running `objdump --syms shoes.exe` (also on cshoes.exe) shows a long list of symbols. Verified official release and my own built on Windows, both contain debugging symbols.

**REFERENCES**
Sample without symbols
```
$ objdump --syms E:/Programmes/Ruby/DevKit-x86-4.7.2/mingw/bin/gcc.EXE

E:/Programmes/Ruby/DevKit-x86-4.7.2/mingw/bin/gcc.EXE:     file format pei-i386

SYMBOL TABLE:
no symbols
```

**Comment by ccoupe** [comment]
yes and no. Tight doesn't strip at all (it can now) the cross compiled one does a strip x. Anything more aggressive  has been a problem but that was long ago.  `strip -h`

**Comment by BackOrder** [comment]
The commit stripped off 2k on cshoes.exe and shoes.exe but still not fully stripped as objdump still reports symbols.

**Comment by ccoupe** [comment]
Feel free to try more aggressive strip  options on your Shoes exe or the dll's and let me know what works better (or doesn't work because you strip too much).

**Comment by BackOrder** [comment]
Take note that the rake task does **not** strip cshoes.exe nor shoes.exe. It only strips dll and so files according to the output. I did strip both manually and it seems fine.
