### ISSUE TITLE
Crashing Shoes when method_missing is invoked

### ISSUE THREAD

**Issue by BackOrder** [Shoes3/shoes3#74]
The following code snippet will crash Shoes. It is a method suspected to be associated with Canvas. Some other methods of the same nature, such as left, also crashes Shoes when used with info.

```ruby
Shoes.app {
  info top
}
```

**Comment by BackOrder** [comment]
**App#method_missing** is called to handle undefined methods using **shoes_app_method_missing()**. There is a bug causing argv being corrupted, containing garbage instead of the actual method name.

https://github.com/Shoes3/shoes3/blob/master/shoes/ruby.c#L1991 (shoes_app_method_missing)
https://github.com/Shoes3/shoes3/blob/master/shoes/ruby.c#L4799 (App#method_missing)

**Comment by ccoupe** [comment]
it's related to the finding canvas methods from Shoes::Types::App
```ruby
Shoes.app {
  info self.class
  info nothing
}
```
produces the expected behavior. ` info top=7` also doesn't crash but it's unclear whether top is a variable or method.

**Comment by ccoupe** [comment]
FWIW, `info nothing` goes thru 3 calls to shoes_app_method_missing (superclasses?) before giving up.

**Comment by BackOrder** [comment]
shoes_app_method_missing() checks first if it is a canvas and then execute ts_funcall2, those would support **top**. A gdb session has shown that shoes_color_method_missing is never reached. `top = 7` is an assignment plain and simple. Finally, testing using `printf("argv = %s\n", argv[0]);` can crash Shoes on its own because they are not strings.

Another test:
 * gdb shoes.exe
 * break ruby.c:1221
 * run
 * in Shoes do alt-/

method_missing is strangely trigged with argc = 3... and argv containing garbage.

**Comment by ccoupe** [comment]
They are ruby strings (VALUES) so you have to convert them to C strings before you can printf. gdb will not convert VALUES (which can be a hash, array, class, method, fixnum or any other Ruby thing).

**Comment by ccoupe** [comment]
Here's an interesting one.
```ruby
Shoes.app {
  info self.class
  info nothing
  puts "is this reached"
  info "got here"
}
```
the puts and info 'got here' are not executed.

**Comment by BackOrder** [comment]
> They are ruby strings (VALUE) so you have to convert them to C strings before you can printf. gdb will not convert VALUE (which can be a hash, array, class, method, fixnum or any other Ruby thing).

It's a good call. Ran into problems though. Attempted the following in shoes_app_method_missing(): using rb_parse_args(), rb_string_value_cstr(), StringValueCStr(), rb_id2name(SYM2ID(cname)). The latter is actually used in shoes_color_method_missing(). Not enough? I did use rb_string_eval() with a puts of the values.

**Results? Corrupted data.**

**Comment by ccoupe** [comment]
You really need to track down the Ruby embedded api doc. Its a single text file,  that is included in rubydocs or ruby source or somewhere. I can never remember where it is or what the name is.

**Comment by ccoupe** [comment]
README.EXT in ~/.rvm/src/ruby-2.1.5

**Comment by BackOrder** [comment]
Thanks, @ccoupe ! This will be so helpful in the future. Shall we have a **Suggested Reading** link on the wiki with this kind of documents/links?

I did try few more things but it is totally unsuccessful. Even printing **self** should be a walk in the part but it is not working either as you can see below. Note that **rb_warn()** works pretty well for testing Ruby values.

**Simple printf()**
```C
2007      printf("-[%s]-\n", RSTRING_PTR(self));
(gdb)
≡¡║e`]-_Çgÿ-ü☻
```

**rb_eval_string()**
```C
2003      snprintf(msg, sizeof(msg), "puts \"%s (%s)\";", rb_id2name(SYM2ID(cnam
e)), RSTRING_PTR(self));
(gdb)
2004      rb_eval_string(msg);
(gdb)
eval:1: warning: encountered \r in middle of line, treated as a mere space
?e?P ) (?^?g}_?g???☻
```

**rb_warn()**
```C
2005      rb_warn("undefined method `%s' for %s", rb_id2name(SYM2ID(cname)), RST
RING_PTR(self));
(gdb)
E:/Programmes/Ruby/DevKit-x86-4.7.2/home/Ian/shoes3/tightmingw/lib/shoes.rb:152:
≡¡║' ing: undefined method `(null)' for █^Çg}_Çg0oë☻
```

**Comment by BackOrder** [comment]
Finally managed to properly display the information on screen. 

```C
rb_warn("shoes_app_method_missing: %s, %s\n", RSTRING_PTR(rb_inspect(self)), 
   RSTRING_PTR(rb_inspect(cname)));
```

```
$ tightmingw/cshoes.exe bug074.rb
bug074.rb:2: warning: shoes_app_method_missing: (Shoes::Types::App "Shoes"), :co
ntents
```

**Comment by BackOrder** [comment]
Tracked down the problem down to **shoes_canvas_get_top()** in the macro **PLACE_COMMON**. It is challenging to debug a macro as you already know. When `info top` is called within top level Shoes.app, canvas would never be filled and ended up being NULL. This is now fixed on Windows, needs testing on other platforms.

Now, `info nothing` issue is another story.

**Comment by ccoupe** [comment]
No ill effects on Linux.  Congrats of a difficult deep dive!

**Comment by BackOrder** [comment]
Thanks, @ccoupe! I appreciate your kind words. GDB doesn't make it easy to debug macros and it's also hard to know when they are called. We will have to find something to improve debugging in  MACROLAND.

Any suggestion on `info nothing` while I am stirring the pot?
