### ISSUE TITLE
Cairo, Pango, Fontconfig.

### ISSUE THREAD

**Issue by ccoupe** [Shoes3/shoes3#78]
There are a number of bug reports having to do with Shoes and Pango warnings when running on Windows.  Before hacking at font.conf or nsis or just flailing around I thought I'd look at the source code and configure options to see if there might be a better solution.  You can't figure out fontconfig without knowing a little about Pango and you can't figure that out without dealing with Cairo.  Until now, cairo and pango are just black box that work fine. But they don't on Shoes//Windows/GTK. 

That turns out to be a very interesting place and way too much to document on the issues list. I started a wiki article [[Tower of Cairo]https://github.com/Shoes3/shoes3/wiki/Tower-of-Cairo] to document the exploration. There are so many hints of things we could use cairo for (svg back end, pdf back-end) Ctrl-P ? Of course we have to be willing to (re)build cairo and pango from source but we knew that would happen eventually. Just like we have to build Ruby from source. 

Issues affected are #69, #54, #48, #23 and probably more.

**Comment by ccoupe** [comment]
This may become even more complicated.  The dependencies on Windows are many years old and hundred of patches have been applied since then.  Some of them for pango win32 fonts.  Certain pango versions require certain versions of glib and cairo.  Ubuntu 14.04 is fairly recent and we know gtk and shoes are happy. OSX also has dependcies on some of the same libs and Brew installed recent ones so we should be safe upgrading the Windows deps. However, it may not fix anything and it might create new bugs.

**Comment by BackOrder** [comment]
Here is a small snippet for listing dependencies. Run it into tightmingw directory. It would be great to build a tree to display the relationship amongst the components.

```ruby
require("pp")

Dir["*.{exe,dll}"].each { |file|
  output = %x[objdump -x #{file} | grep "DLL Name"].split("\n").collect { |n| n.gsub(/.*: (.*)/, '\1') }
  
  puts "#{file}: #{output}"
}
```

The list below is top-level components, which means no other component is reported depending on them.
```
cshoes.exe
shoes.exe
libcairo-gobject-2.dll
libeay32.dll
libffi-6.dll
libgcc_s_sjlj-1.dll
libgdbm_compat-3.dll
libiconv-2.dll
libyaml-0-2.dll
sqlite3.dll
ssleay32.dll
```

**Comment by ccoupe** [comment]
That appears to be the list of Ruby dependencies for ext/gems (mostly). A tree would be most helpful tracking down the dependencies in *.pc   I'm trying to build all the deps starting from zlib-1.2.8 up and somebody is holding on to a old libpng.

**Comment by ccoupe** [comment]
I'll commit some changes in a few hours that use the newer dependencies and fixes these bugs. Too soon to close the issues.   When fontconfig can't match a request it may not return anything reasonable. So, I'm a more explicit about setting fonts (in gtk.c) and providing something that will match that in fonts.conf

There is a cost - I'm not all that happy with the font appearance on Windows compared to Linux (or even the old scheme on Windows. Duplicating the build of dependencies has to be done on a mingw tightshoes setup - a pain but my configure scripts could be run through a simple sed script and that would ease the task.  Just set make/win/7/env.rb - ShoesDep to point to the newly built dependencies.

We still need to run the fc-cache.exe as part of the installation, but its now part of whats bundled up with Shoes. 

There's also ground work for gtk icon-themes but that's a different issue.

**Comment by ccoupe** [comment]
I don't remember closing this. Sorry
