### ISSUE TITLE
bug in shadow effect won't give correct fill value to shadow

### ISSUE THREAD

**Issue by passenger94** [Shoes3/shoes3#81]
https://github.com/Shoes3/shoes3/blob/master/shoes/effects.c#L208
sample app
```ruby
Shoes.app :width => 350, :height => 200, :resizable => false do
    image :top => 20, :left => 20 do
        fill "#127"
        nostroke
        oval 10, 10, 200, 50
        #shadow 53, 20, fill: black
        shadow distance: 53, radius: 20, fill: black
    end
end
```
![shadow1](https://cloud.githubusercontent.com/assets/10730930/6607971/76ed59be-c843-11e4-82cc-26343a78effc.jpg)

```c
 cairo_set_source_rgba(cr, color->r / 255., color->g / 255., color->b / 255., color->a / 255.);
```
correcting cr to cr2 in line 227
```c
 cairo_set_source_rgba(cr2, color->r / 255., color->g / 255., color->b / 255., color->a / 255.);
```
![shadow2](https://cloud.githubusercontent.com/assets/10730930/6608007/d68d057c-c843-11e4-938d-ef0a4a1a1b1e.jpg)

sending a pull request

**Comment by ccoupe** [comment]
We should note that blur and shadow are completely undocumented.

**Comment by passenger94** [comment]
yes we might use examples from effects issues to document them (also glow) 
image effects only, i think, so belongs to image part of manual or special page for image effects ?
