### ISSUE TITLE
custom placement of shadow in image shadow effect

### ISSUE THREAD

**Issue by passenger94** [Shoes3/shoes3#85]
Actually the placement of the shadow is driven only by the distance attribute/style : 
https://github.com/Shoes3/shoes3/blob/master/shoes/effects.c#L218
so the shadow can only be placed in a diagonal from top-left corner to bottom-right corner
with following code the shadow placement could be tweaked with the help of displace_left/displace_top optional styles 
if displace_left or displace_top or both are used then distance is not taken into account - also backward compatibility -
(i choose displace_left/displace_top, could be left/top or x/y or move_left/move_top ...  ? )
(from line 211 on)
```c
  cairo_surface_t *source = cairo_get_target(cr);
  int width  = cairo_image_surface_get_width(source);
  int height = cairo_image_surface_get_height(source);
  VALUE fill = ATTR(attr, fill);
  int dx = ATTR2(int, attr, displace_left, 0);                      //new
  int dy = ATTR2(int, attr, displace_top, 0);                       //new

  cairo_surface_t *target = cairo_image_surface_create(CAIRO_FORMAT_ARGB32, width, height);
  cairo_t *cr2 = cairo_create(target);
  if (dx != 0 || dy != 0)                                           //new
      cairo_set_source_surface(cr2, source, dx, dy);                //new
  else                                                              //new
      cairo_set_source_surface(cr2, source, distance, distance);    //new
  cairo_paint(cr2);
  cairo_set_operator(cr2, blur_op);
```
example app : 
```ruby
Shoes.app :width => 350, :height => 200, :resizable => false do
    image :top => 20, :left => 20 do
        fill "#127"
        nostroke
        oval 20, 20, 200, 50
        ### below settings are all valid for same result
        #shadow 53, 20, fill: rgb(0, 0, 0, 0.75), displace_left: -20, displace_top: 30
        #shadow distance: 53, radius: 20, fill: rgb(0, 0, 0, 0.75), displace_left: -20, displace_top: 30
        shadow radius: 20, fill: rgb(0, 0, 0, 0.75), displace_left: -20, displace_top: 30
    end
end
```
with displacement as above
![shadow4](https://cloud.githubusercontent.com/assets/10730930/6628095/05c8ee54-c903-11e4-97a4-23de8cd60bb3.jpg)

 without displacement `shadow 53, 20, fill: rgb(0, 0, 0, 0.75)` : 
![shadow3](https://cloud.githubusercontent.com/assets/10730930/6620685/632b992e-c8d2-11e4-9b45-2f4aebeec90e.jpg)

**Comment by passenger94** [comment]
ok for a pull request ? with displace_left/top as style attribute ?

**Comment by BackOrder** [comment]
Keep up the excellent work. Remember to test on multiple platforms and add a milestone before closing an issue.
