### ISSUE TITLE
slider control not documented and enhancement

### ISSUE THREAD

**Issue by passenger94** [Shoes3/shoes3#88]
slider control exists but not documented (with *fraction* and *fraction=* methods)
i made a pull request with enhancement : ability to initialize a slider control with **:fraction** style attribute (same name as existing method, could be changed to *value* for example), works for me on linux - ubuntu.
A test app 
```ruby
Shoes.app do
    stack do
        @p = para ""
        slider fraction: 0.5 do |sl|
            @p.text = "changed : #{sl.fraction}"
        end
    end
end
```
![slider01](https://cloud.githubusercontent.com/assets/10730930/6791738/baeef1a0-d1b1-11e4-96d9-77e171cfe54d.jpg)

**Comment by ccoupe** [comment]
Slider has a method 'change' that isn't in the progress widget - what does it do? does it work?

**Comment by passenger94** [comment]
yes it works ! That method is essentially the block given to the slider method : 
```c
g_signal_connect(G_OBJECT(ref), "value-changed",
                   G_CALLBACK(shoes_widget_changed), (gpointer)self);
```
```c
shoes_widget_changed(GtkWidget *ref, gpointer data)
{ 
  VALUE self = (VALUE)data;
  shoes_control_send(self, s_change);
}
```
s_change is the :change symbol, coming from the change method put as a procedure in the :change attribute
```c
shoes_canvas_slider(int argc, VALUE *argv, VALUE self)
{
  rb_arg_list args;
  VALUE slider;
  SETUP();

  rb_parse_args(argc, argv, "|h&", &args);

  if (!NIL_P(args.a[1]))
    ATTRSET(args.a[0], change, args.a[1]);    //  <---here

  slider = shoes_control_new(cSlider, args.a[0], self);
  shoes_add_ele(canvas, slider);
  return slider;
}
```
used also with edit_line, edit_box, list_box

**Comment by passenger94** [comment]
Does it work on windows, osx ?
if so i could update the manual

**Comment by ccoupe** [comment]
Your example works well on OSX,  Windows and Ubuntu 14.04.  Please do update the manual.

**Comment by passenger94** [comment]
ok will try to do it asap, not sure i can do it until 2/3 days from now, feel free to build something if in a hurry for the release !
shall we keep the change methods commented in ruby.c maybe removed ?

**Comment by ccoupe** [comment]
Believe me:  my release schedules are flexible.  The last one took a week from saying 'we ought to' to getting it done.  I don't mind having commented code. It helps remember what didn't work or was there. Of course we need to clean it up after a few months or as part of a general clean up.

**Comment by passenger94** [comment]
here's a draft
```
== Slider ==

Sliders allows you to adjust a value, from 0.0 to 1.0, thanks to the handle that can be moved with the mouse or by using the arrow keys. !{:margin_left => 100}man-ele-slider.png!

here's a sample showing you a slider in action :

{{{
 #!ruby
Shoes.app do
    stack margin: 10 do
        flow do
            @sl = slider fraction: 0.35, state: nil do |sd|
                @p.text = "value : #{sd.fraction}"
            end
            @p = para "", margin_left: 10
        end
        button "switch slider state" do
            @sl.state = (@sl.state == "disabled" ? nil : "disabled")
        end
    end
end 
}}}

For more methods beyond those listed below, also look into the [[Common]]
methods page. Because you get those methods on every slider as well.

=== fraction() » a decimal number ===

Returns a decimal number from 0.0 to 1.0, depending on how far along the slider bar we are.

=== fraction = a decimal number ===

Sets the slider to a decimal number between 0.0 and 1.0.

=== state » a string ===

See [[Styles.state]] style for details.

=== state = nil, "disabled" or "readonly" ===

See [[Styles.state]] style for details.
```

*we shall replace the image with a screencap taken in Windows for consistency*

![manualslider](https://cloud.githubusercontent.com/assets/10730930/6831491/ea956fd6-d320-11e4-831b-ab12577c714b.jpg)

**Comment by passenger94** [comment]
side note : we could add further enhancement to slider easily, the ability to choose directly the range of the slider and control the step
https://github.com/passenger94/shoes3/blob/master/shoes/native/gtk.c#L1418
```c
shoes_native_slider(VALUE self, shoes_canvas *canvas, shoes_place *place, VALUE attr, char *msg)
{
    double start = 0.0;
    double end = 1.0;
    double gap = 0.01;
    if (RTEST(ATTR(attr, startpoint))) start = NUM2DBL(ATTR(attr, startpoint));
    if (RTEST(ATTR(attr, endpoint))) end = NUM2DBL(ATTR(attr, endpoint));
    if (RTEST(ATTR(attr, step))) gap = NUM2DBL(ATTR(attr, step));
#ifdef GTK3
  SHOES_CONTROL_REF ref = gtk_scale_new_with_range(GTK_ORIENTATION_HORIZONTAL, start, end, gap);
  //SHOES_CONTROL_REF ref = gtk_scale_new_with_range(GTK_ORIENTATION_HORIZONTAL, 0., 1., 0.01);
#else
  SHOES_CONTROL_REF ref = gtk_hscale_new_with_range(start, end, gap);
  //SHOES_CONTROL_REF ref = gtk_hscale_new_with_range(0., 1., 0.01);
#endif
```
and some changes in ruby.c and ruby.h (symbols needs to be created)
works on linux (cocoa needs to be done), if you're interested  i open a new issue for this (3.2.23 milestone ?)

**Comment by ccoupe** [comment]
File an issue for anything you like. The worst that will happen is it won't get done promptly.  @passenger94 , do you have good Gtk skills? The Gkt3 code almost works - except for computing the clip region which was the big change from gtk2 to gtk3. It was more difficult than I could figure out. That's an example of a issue that needs be filed even if no one wants to work on it.

**Comment by passenger94** [comment]
i'll look into this and try to figure out if it's in my capacity ...
