### ISSUE TITLE
samples/simple-sphere.rb crashes on 64 bit systems

### ISSUE THREAD

**Issue by ccoupe** [Shoes3/shoes3#9]
If you turn the blur down to 25 from 30, it doesn't.

**Comment by passenger94** [comment]
changing **box_blur** method in effects.c (adding a cast) works for me
https://github.com/Shoes3/shoes3/blob/master/shoes/effects.c#L71
```c
      out[l2] = run[sums[0]];                        
      out[l2 + 1] = run[sums[1]];                    
      out[l2 + 2] = run[sums[2]];                    
      out[l2 + 3] = run[sums[3]]; 
```
to
```c
      out[l2] = run[(int)sums[0]];                        
      out[l2 + 1] = run[(int)sums[1]];                    
      out[l2 + 2] = run[(int)sums[2]];                    
      out[l2 + 3] = run[(int)sums[3]]; 
```
might be related to some changes from 32bits to 64bits OS and the "value" of unsigned char ...
    is casting to int the best option here ?

**Comment by ccoupe** [comment]
@passenger94, that is wonderful! It works for my 64 linux.  Please commit the change .

**Comment by BackOrder** [comment]
Is this confirmed on MacOS X? If so, let's close the issue.

**Comment by ccoupe** [comment]
Fixed on OSX as well.
