### ISSUE TITLE
Enter 3.2.22 Quiet Period?

### ISSUE THREAD

**Issue by ccoupe** [Shoes3/shoes3#90]
I'd like to release 3.2.22 soon. It's been a month or two since 3.2.21 and we have  bug fixes and some new features to share. Thanks to you. 

What happens in a quiet period? We all sync to github. We (re) build the platforms we care about and test what we think needs testing. I build betas for all platforms. We test them (if you want). We don't commit major changes to the 3.2.22 milestone. I write the changelog updates and blog post or two. We (re)fix anything we broke. Maybe we update the wiki if we are bored. 

It sounds onerous but you know me -- I only pretend to know what to do and reality trumps good intentions every time they meet.

Comments please.

**Comment by passenger94** [comment]
In a quiet period, lots of indistinguishable beasts are lurking around waiting for the chilled out fellow to catch them and summon them up to a state of idea and by the mysteries of old transmutation brings them to an easy mellow tempo of life
i'm tempted to say : relax and have a release !

**Comment by ccoupe** [comment]
3.2.22 has been uploaded to the beta site. http://walkabout.mvmanila.com/public/shoes. It does not include the additions that @passenger94 and I want to make to the manual (obviously) so there will be one or more builds to follow for the manual changes and anything else that pops up as a crisis must fix.  Download whatever you care to test.  The Shoes-3.2.22-osx-10.6.tgz (upper case S) is for the osx 10.6 built on 10.10.2 version. Please close open issues you've reported that are fixed in the 3.2.22 beta.   

There are 20 issues that are tagged with 3.2.22. Some probably can't be closed (rakefiles for example)  I'll update the changelog - that always make me smile.

**Comment by ccoupe** [comment]
I've done enough testing. I've moved the 3.2.22 downloads from the beta site to shoes.mvmanila.com/public/shoes and update the shoerb.com site.  After a blog post and mail listing notification I'll close a bunch of issues (which you can reopen or create new ones, if needed).

**Comment by ccoupe** [comment]
Blog post is http://walkabout.mvmanila.com/2015/03/27/shoes-3-2-22-released/
