### ISSUE TITLE
Gtk3 support is incomplete

### ISSUE THREAD

**Issue by ccoupe** [Shoes3/shoes3#92]
The Gtk3 code (conditional in gtk.c) is mostly complete except for managing the clip region for update. sample/simple-accordiian and simple-slide show the problem best.

**Comment by passenger94** [comment]
i think i have all the necessary headers for gtk3, i'm looking for how one  switch from gtk2 to gtk3 :
rakefile, makefile, ... ?

you are referring to this for clip region update, right ?
https://github.com/Shoes3/shoes3/blob/master/shoes/native/gtk.c#L511

**Comment by ccoupe** [comment]
make/linux/env.rb  lines 9 and 10 select the version of Gtk. 

Yes, that is the major function to fix but the fix can bleed to other functions.

**Comment by passenger94** [comment]
thanks !
i needed to change `ENV['GTK'] = "gtk+-3.0"` for `APP['GTK'] = "gtk+-3.0"` in env.rb

but doesn't compile
`/usr/bin/ld: dist/shoes.a(gtk.o): référence au symbole non défini «FcFileScan»
//usr/lib/x86_64-linux-gnu/libfontconfig.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
rake aborted!
Command failed with status (1): [gcc -o dist/shoes bin/main.o dist/shoes.a ...]
`
plus a bunch of warnings about deprecated things (expected)

**Comment by ccoupe** [comment]
We missing fontconfig (i get the same error). add this line to env.rb:
```LINUX_LIBS << " -lfontconfig" if APP['GTK'] == "gtk+-3.0"```
AFTER the line (61?) that reads
```LINUX_LIBS = "#{RUBY_LIB} #{GTK_LIB}  #{CAIRO_LIB} #{PANGO_LIB} #{MISC_LIB}"```

**Comment by ccoupe** [comment]
A useful document : https://developer.gnome.org/gtk3/stable/gtk-migrating-2-to-3.html

**Comment by passenger94** [comment]
thanks works now ! :-)

**Comment by passenger94** [comment]
simple-slide.rb and simple-accordion.rb are working for me now
check pull request from my gtk3 branch

**Comment by passenger94** [comment]
unrelated 
Resizing behave strangely/differently from gtk2, we are stuck as a minimum size for the app with the one acquired at initialization (can't go beyond that) making it bigger and back seems to works nicely, but Manual can't go back once you resized it !

what about a new branch ?

**Comment by ccoupe** [comment]
Sorry for not replying sooner. I do think you'll need a branch at github to match your local branch structure in order to push your changes up. Or, since your work is inside the #ifdef gtk3 brackets you can just merge your two local branches. That will have to be done now or later.  Do as you prefer.

The resizing problem could be that it was never addressed/fixed/tested when I wrote the gtk3 changes. There was bug that was fixed for resizable windows fixed in 3.2.17 or .18  (Nov 2014) - that would not have been done for gtk3.

**Comment by passenger94** [comment]
i do have a 'gtk3' branch on my forked repository :-) in which i push my changes from my local branch, i was asking i you want to create a branch in your repository so i can merge into that branch also and you can safely compile to see progress or failure :-)

do you remember which fix it was ?

**Comment by ccoupe** [comment]
My lack of knowledge about git is showing.  I didn't realize you had a fork - i was assuming a clone. I've made a gtk3 branch at shoes3.  Lets see if you can push to that and I can figure out how to fetch from it without confusing my master or yours. 

the resize fix was https://github.com/Shoes3/shoes3/commit/78bcf497ba2f7ca703a81fa6fd8918ca99d064bf  Doesn't seem to be related to gtk3

**Comment by passenger94** [comment]
ok made a test
just pushed from my local to your gtk3 branch

after updating my local with your repository i just do this to test :
`git checkout gtk3`
`rake`
`dist/shoes -m`

**Comment by passenger94** [comment]
the resize fix 78bcf49, doesn't look related indeed ...

investigating `gtk_window_set_geometry_hints` to see if i can emulate gtk2 behavior (resizing could go under initialization dimensions)
commenting these instructions in gtk2 gives the same behavior as in gtk3, so something is going on there ... ok rereading again https://developer.gnome.org/gdk3/stable/gdk3-Windows.html#GdkWindowHints  and https://developer.gnome.org/gdk3/stable/gdk3-Windows.html#GdkGeometry 

Manual problem cames from slot not having the  :width set ! When resizing back after growing, it seems gtk3 is confused about what to do with the 100% wide slot, both problems might be related

**Comment by ccoupe** [comment]
All I had to do was
```
git fetch
git checkout gtk3
rake clean
rake 
```
Looks pretty good. While playing with the samples I got a 
```
*** Error in `dist/shoes': double free or corruption (out): 0x00007f10d0207d70 ***
Aborted (core dumped)
```
but I can't reproduce it.

I also get a `** (shoes:19062): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-QN9JQcD4GQ: Connection refused` warning at startup.

**Comment by passenger94** [comment]
making progress on the resize department... new commits on gtk3 branch
still WIP, @ccoupe, please have a look at the manual especially comparing introduction page and "Furthermore" page to get what's going on with resizing, we need to manage width-for-height and height-for-width new gtk3 way of doing things there ...
suggestions ?

going to test list_box sample ... (probably related)

**Comment by passenger94** [comment]
maybe we need to put in place a whole new size request management for widgets with get_preferred_width etc...  https://developer.gnome.org/gtk3/stable/ch25s02.html#id-1.6.3.4.3

**Comment by passenger94** [comment]
made some test with list_box : no entry(text not editable, click anywhere on listbox pops up) like in gtk2, found a way to set desired width no matter the length of the text and added some ellipsis at the end of the text if too long
no scrollbar though, didn't found how to do that ...

**Comment by passenger94** [comment]
i had to subclass GtkFixed to revert back to same gtk2 resizing behavior 
it was a problem as in gtk3 gtkFixed always obey cumulative size of inside widgets so we could possibly end up with a overflowing slot in height without scrollbar
if this is confirmed to work smoothly, we might getting close to a working gtk3

**Comment by passenger94** [comment]
i don't know if it's relevant for shoes but what do you think of this :
http://balintreczey.hu/blog/beautiful-wireshark-on-os-x-using-homebrew-and-gtk3quartz/
could this possibly simplify things (only gtk for all platform) ?

**Comment by ccoupe** [comment]
I did try gtk on OSX about a year ago and it was a complete mess - probably because the instructions were out of date relative to what homebrew & recipies do now and I didn't know enough to understand some of the OSX vs X11 vs xquartz issues.  There were related problems with which dlylibs to include with a Shoes binary install and whether the end user had to install xquartz.  It's worth revisiting. The option/conditionals  probably still exists in gtk.c and some rakefile.

**Comment by passenger94** [comment]
i'm using this awesome software (on linux )
https://github.com/darktable-org/darktable
https://github.com/darktable-org/darktable/blob/master/src/gui/gtk.c

there's  an osx version using gtk, didn't had a chance to look at it on osx 
but from the linux experience i'm expecting something serious ...

**Comment by ccoupe** [comment]
' #include <Carbon/Carbon.h>' -- I thought Carbon was dead in  OSX?

**Comment by passenger94** [comment]
at the pace we're killing it nowadays it's going to be dead for everyone way too soon !

i think there is 2 integration in osx : MAC_INTEGRATION / GDK_WINDOWING_QUARTZ i guess it depends on osx version ...

**Comment by The-Cecil** [comment]
It's worth trying again. The wireshark example could work with Shoes. I see somethings I didn't do. We don't want the X11/Xquartz - just the gdk-quartz and only brew install the correct packages. It could make for an easier Shoes 3.3 if we only had to write Gtk based enhancements (and the current OSX has more than it's share of problems).

**Comment by The-Cecil** [comment]
I've started a wiki page to document the details of installing gtk on OSX without XQuartz. https://github.com/Shoes3/shoes3/wiki/OSX-and-Gtk3 . So far, it has not harmed building Shoes/OSX. The next step will be to create a new rake  target, `osx:setup:osxgtk` and the env.rb, task.rb and gtkosx-custom.yaml to see what can be built, run and distributed.

**Comment by passenger94** [comment]
Nice !!! :-)

**Comment by passenger94** [comment]
just in case ...
http://www.gtk.org/download/macos.php
https://github.com/GNOME/gedit/tree/master/osx/build

**Comment by ccoupe** [comment]
Short status report for a long effort. I got Shoes/OSX/gkt3 to compile and link.  Doesn't run however and there are no error messages about why. I suspect the current 3.2. OSX dependencies on X11 things  could also be reduced but there's potential to break the  homebrew dependencies. There's also a looming theme issue if it does run.

**Comment by passenger94** [comment]
ok ;-) it's not like everyone expected it to work at the first try ! right :-D

still having issues with resizing in gtk3 but this times on widgets, i actually tested it intensively with an edit_line, but i'm suspecting other widgets to act the same way ...
the widget refuse to shrink under a predefined size (probably minimum size/natural size at C level)
it refuses visually but somewhat integrates the expected behavior, see :

![gtk3_widgetwidth](https://cloud.githubusercontent.com/assets/10730930/7604582/fefa4b64-f944-11e4-845e-1c7b8f1a9d14.jpg)

```ruby
Shoes.app do
	w = 30
	stack do
		flow do
			para "text : "
			@author = edit_line "", :width => w
			para "long text to see what happens : ", margin: [0,20,0,0]
		end
		flow do
			para "text : "
			line 40,5,40+w,5, strokewidth: 5, stroke: blue
			inscription "edit_line and blue line width is #{w} pixels", margin_left: w+5
		end
	end
	w = 100
	stack do
		flow do
			para "text : "
			@author = edit_line "", :width => w
			para "long text to see what happens : ", margin: [0,20,0,0]
		end
		flow do
			para "text : "
			line 40,5,40+w,5, strokewidth: 5, stroke: blue
			inscription "edit_line and blue line width is #{w} pixels", margin_left: w+5
		end
	end	
	w = 165
	stack do
		flow do
			para "text : "
			@author = edit_line "", :width => w
			para "long text to see what happens : ", margin: [0,20,0,0]
		end
		flow do
			para "text : "
			line 40,5,40+w,5, strokewidth: 5, stroke: blue
			inscription "edit_line and blue line width is #{w} pixels", margin_left: w+5
		end
	end		
	w = 220
	stack do
		flow do
			para "text : "
			@author = edit_line "", :width => w
			para "long text to see what happens : ", margin: [0,20,0,0]
		end
		flow do
			para "text : "
			line 40,5,40+w,5, strokewidth: 5, stroke: blue
			inscription "edit_line and blue line width is #{w} pixels", margin_left: w+5
		end
	end
end
```

i guess it means another round at subclassing widgets ?

**Comment by ccoupe** [comment]
@passenger94. There is no reason to trust the gtk3 adjustment code changes I "converted, just to get gkt3 to compile. None. zip, zero, nada. The content region redraw also has a role but I gave up figuring it out.

**Comment by passenger94** [comment]
well i think you' done a great job but the whole resizing policy of gtk from 2 to 3 has changed and since the core of Shoes is a GtkFixed Layout and the resizing policy is tailored for layout that adapts automagically to whatever resizing, we are getting into troubles (gtk discourage the use of a GtfFixed)
but what makes Shoes special is the use of the GtkFixed as a base layout, _why made an impressive job at recreating an entire layout management based on that

**Comment by ccoupe** [comment]
I agree that GtkFixed Layout (and the cocoa equivalent ) is a major constraint going forward. The Shoes4 folks are determined to replicate it in SWT (without cairo) and have payed a heavy price. Since they are about to release something that will probably work for many "beginners" and existing Shoes scripts -they are  keeping the _why vision alive. 

I'm not sure that audience actually exists.  People who use 3.2 seem to be "developers" who like the packaging and MRI based gem features. Given the amount of work at the C level to move Shoes 3.2 to a very different layout/DSL paradigm or even Gtk 3.  We have to consider rewriting gtk.c to be qt.c which they (Shoes 4) assure me 'should work' but keep all the MRI gem/packaging goodness.  Truth be told, that probably would be the best way forward. A huge task in C terms and they haven't nailed down Shoes 4 enough  to deal with QT variants.  IMO.

Perhaps Shoes 3.2 has reached it's end-of-life. It happens.

**Comment by passenger94** [comment]
well i'm not surprised they (Shoes 4 crew) are determined to replicate the Fixed layout behavior, while it could be seen as constraint here, its precisely what brings the magic to Shoes, being multipurpose, from games to layout with text + images+ shapes etc, all in a simple light interface, always having the choice between the need of a strict rigid placement or letting an educated flow rule the placement of stuff and be done with it, and even loosely in all heretic goodness mix both worlds !
I'm not too deep into layouting witchcraft at the moment so maybe there is out there a better layout to voodoo around with but i think it's crucial to not allow a generic automatic layout management take control of things to achieve what was done here. That is what gtk3 is doing, pretending to know better, in it's out of the pack incarnation, so to take benefit from its otherwise sexyness, i think it's mandatory at some point to giggle in advance at the idea of getting hands dirty.

audience is an illusion, a fancy one admittedly, i've been told, it will let you down without even taking the time to lie as soon as today becomes a yesterday, but i might be digressing here

**Comment by passenger94** [comment]
subclassed Gtkentry to fix size issue, works on my side

![gtk3_widgetwidthfix](https://cloud.githubusercontent.com/assets/10730930/7960436/df3aba94-0a00-11e5-90f4-1628d3618828.jpg)

i think edit_box and list_box could be fixed the same, then gtk3 might be ok !

**Comment by passenger94** [comment]
ok unless problems arise elsewhere (and why shouldn't they) 
resizing mimics the gtk2 way, done for edit_line, edit_box, list_box, button (+ GtkFixed of course)

Needs testing ...

**Comment by ccoupe** [comment]
I just want to leave a note of appreciation for @passenger94 work on gtk3. Thank you so much.

**Comment by ccoupe** [comment]
The file http://shoes.mvmanila.com/public/shoesdeps/mingw/ShoesDeps.zip has the prebuilt Windows dependencies (both gtk2 and gtk3)

**Comment by passenger94** [comment]
Thanks @ccoupe  :-) in any case it was an interesting journey !

**Comment by ccoupe** [comment]
Who knew about GApplication/GtkApplication ? I didn't. Supposedly works on OSX and handles the top level menu stuff and command-keys that makes OSX difficult).  https://developer.gnome.org/gtk3/stable/GtkApplication.html.

That API would require very different Shoes startup (more sensible?) **If **it can work with an embedded ruby and threading issues. Of course I find it worth deeper investigation it could fix OSX bugs and enable some way of handling app-menus and per window menus.

**Comment by ccoupe** [comment]
The osxgtk variant builds but hangs (in gtk polling). I think that's about as far I'm going to go any time soon. Using GtkApplication (if it works with ruby and poll loops) is a big effort and the result on OSX could be a theme issue that can't be fixed. Also, I  don't think Gtk3/OSX is a particularly active project. and I don't like polling problems. Better to stick with Cocoa for OSX. If someone else wants to run with the osxgtk variat, that would be welcome.
