### ISSUE TITLE
Rethink set_window_title

### ISSUE THREAD

**Issue by ccoupe** [Shoes3/shoes3#93]
app.set_window_title() was not my best idea and using it for confirm,ask,alert #59, was convenient  but it's problematic. It only works if Shoes is run from the command line or carefully controlled situations. It won't effect Apps launched by the Shoes splash or Manual. It's not a global setting common to all Apps.  (A style hash to App wouldn't fix that unless all App inheirit it _ and_ the change to it could be propagated to all existing or newly opened Apps - not a completely bad idea) 

@BackOrder  has several related issues.  #64, #44 and probably more if we think about IRB lissues.

I'm very cautious about poking around in this part of Shoes but it seems to me to be a good time to think about it.

**Comment by passenger94** [comment]
Had a surprising issue with `Shoes.app(:title => "Shoes Custom Ask & Alert",... ` (test app for ask, alert, confirm)
in which the resulting default alert title (appttle) won't be used because of '&' i needed to escape it in the app title (with '&amp;') to have it correct in alert title !!!

**Comment by ccoupe** [comment]
There is an issue with gtk_message_dialog_new_with_markup() it - actually wants a format string and arguments (like sprintf would) which is not what we do currently. It's on my todo list.  It's possible '&' could be interpreted as something that needs that second arg.

**Comment by ccoupe** [comment]
Actually, it might be normal behavior for the markup style to deal with html stuff in the title. Ugg.

**Comment by BackOrder** [comment]
The sample [expert-colours.rb](https://github.com/Shoes3/shoes3/blob/master/samples/expert-colours.rb) is using effectively `set_window_title`. Is this issue still need to be open?

**Comment by ccoupe** [comment]
I don't think any more on it is likely - closing.
