### ISSUE TITLE
undocumented _snapshot method

### ISSUE THREAD

**Issue by passenger94** [Shoes3/shoes3#97]
might not be useful at all ?
```ruby
Shoes.app width: 400, height: 500 do 
    stack do
        para "snapshooting"
        image "#{DIR}/static/man-ele-image.png"
        button("shoot!") do
            _snapshot :filename => "#{DIR}/snapshotfile.pdf", :format => :pdf 
            alert "#{DIR}/snapshotfile.pdf", title: "snapshot saved to :"
        end
    end
end
```
there seems to be the need for a block but works without and does nothing anyway ...
https://github.com/passenger94/shoes3/blob/master/shoes/canvas.c#L1399

note that the button is not in the snapshot, only cairo stuff is part of snapshot !
was a work in progress method ?

**Comment by BackOrder** [comment]
This is an amazing find, @passenger94. Thank you.

I was thinking about suggesting this feature a while ago. It would be great to make it work though perhaps with **snapshot** method without underscore. 

To answer your question — I did a little search on Raisins and Curious releases and it was introduced in Raisins. https://github.com/shoes/shoes/blob/2/Raisins/shoes/canvas.c#L1372

**Comment by passenger94** [comment]
ouch !
https://github.com/Shoes3/shoes3/blob/master/lib/shoes/image.rb#L12
still i think it wasn't finished because it is written to make use of a block ! ...

**Comment by BackOrder** [comment]
Notice **svg** format? It seems that it would be used to convert shapes to PDF. The following code snippet is actually working.

```ruby
Shoes.app width: 400, height: 500 do
  stroke blue
  strokewidth 4
  fill black
  oval 10, 10, 50
  _snapshot :filename => "snapshotfile.pdf", :format => :pdf  do
  end
end
```

**NOTICE** this should probably be the correct form if a block is given.
```ruby
Shoes.app width: 400, height: 500 do
  _snapshot :filename => "snapshotfile.pdf", :format => :pdf  do
    stroke blue
    strokewidth 4
    fill black
    oval 10, 10, 50
  end
end
```

**Comment by BackOrder** [comment]
Your sample did work when removing **`#{DIR}/`** from the _snapshot line.

**Comment by passenger94** [comment]
yes one can save the snapshot in either pdf, svg or ps format !
??? sample was working with DIR at least for me

i tried with a block but the block is never called with the underscored method ...
i didn't find how to use the non underscored in image.rb

**Comment by passenger94** [comment]
ok with those changes
```
VALUE
shoes_canvas_snapshot(int argc, VALUE *argv, VALUE self)
{
  SETUP();
  rb_arg_list args;
  ID   s_filename = rb_intern ("filename");
  ID   s_format   = rb_intern ("format");
  VALUE _filename, _format;
  rb_parse_args(argc, argv, "h&", &args);      // < ----- changed
  //rb_parse_args(argc, argv, "h", &args);      // < ----- changed

  _filename = ATTR(args.a[0], filename);
  _format   = ATTR(args.a[0], format);
  if (NIL_P(args.a[1]) || NIL_P(_filename) || NIL_P(_format))
  {
    rb_raise(rb_eArgError, "wrong arguments for _snapshot({:filename=>'...',"
                              ":format=>:pdf|:ps|:svg}, &block)\n");
  }
  else
  {
    const char      * filename = RSTRING_PTR(_filename);
    cairo_surface_t * surface  = shoes_get_snapshot_surface(_format)
                                      (filename, canvas->width, canvas->height); //width/height : pixels given, points expected
    if (surface == NULL) {
        rb_raise(rb_eArgError, "Failed to create %s surface for file %s\n", 
           RSTRING_PTR(rb_inspect(_format)),
           RSTRING_PTR(rb_inspect(_filename)));
    }
    else
    {
      //cairo_t * waz_cr = canvas->cr;
      cairo_t * cr     = canvas->cr = cairo_create (surface);
      DRAW(self, canvas->app, rb_funcall(args.a[1], s_call, 0));     // < ----- changed
      // shoes_canvas_draw (self, self, Qfalse);
      shoes_canvas_draw (self, self, Qtrue);
      // canvas->cr = waz_cr;
      cairo_show_page (cr);
      cairo_destroy (cr);
      cairo_surface_destroy (surface);
      //  TODO  detect cairo outrages here
    }
  }
  return Qnil;
}
```

This works :
```ruby
Shoes.app width: 400, height: 400 do 
        ext = "svg"
        path = "#{DIR}/snapshotfile.#{ext}"
        
    stack do    
        button("shoot!") do
            _snapshot :filename => path, :format => ext.to_sym do |x|
                stroke blue
                strokewidth 4
                fill black
                oval 100, 100, 200
            end
            alert path, title: "snapshot saved to :"
        end
    end
end
```

**Comment by ccoupe** [comment]
Amazing. It was laying there in Shoes, undiscovered! Add a little polish and part of #54 support is 'just done'.  I also know what goes into the feature list for 3.2.23.  Well done. very well done.

**Comment by passenger94** [comment]
Wrapping the snapshot method into a **Shoes::Types::App** class in image.rb (not sure it's the best place) gives us access to it
```ruby
class Shoes::Types::App
     
  def snapshot(options = {}, &block)
    options[:format]   ||= :svg

    options[:filename] ||= ( tf_path = ( require 'tempfile'
                 tf = Tempfile.new(File.basename(__FILE__)).path ))

    _snapshot options do
      block.call
    end
    return File.read(options[:filename])
  ensure
    File.unlink(tf_path) if tf_path
  end
end
```
example provided works with snapshot in place of _snapshot

**Comment by passenger94** [comment]
where shall we place the doc in manual ?

**Comment by ccoupe** [comment]
If I understand snapshot correctly it's a peer of image &blk with the complication of not being a visible element. But, timers are not visible either and the are part of elements. That's where I'd put it but I'm only one voice.

**Comment by ccoupe** [comment]
@passenger94 Would you like to update the manual for this or do you want me to? I'd like to release 3.2.23 very soon and this is a blocker.

**Comment by passenger94** [comment]
hi @ccoupe,
i won't be able to do much until say monday/tuesday, i'll try to do at least a draft today and submit it to you ...
